### ISSUE TITLE
Didn't work properly on DS2422+

### ISSUE THREAD

**Issue by brimur** [007revad/Synology_HDD_db#1]
Hi. I tried the script but only 1 drive model became verified...

https://i.imgur.com/5PT1x7E.png

**Comment by 007revad** [comment]
Can you please run the following command and reply with result. Copy the result and paste it in your reply.

`for drive in /dev/sata*; do hdparm -i "$drive" | grep Model; done`

**Comment by 007revad** [comment]
Can you please try this version from the develop branch.
https://github.com/007revad/Synology_HDD_db/blob/develop/syno_hdd_db.sh

It will add a 2nd database entry for any drives named "WDC WDxxxxx". For example:
1. WDC WD60EFRX-68L0BN1
2. WD60EFRX-68L0BN1

It won't hurt to have the extra entries in the database.

**Comment by brimur** [comment]
> Can you please try this version from the develop branch. https://github.com/007revad/Synology_HDD_db/blob/develop/syno_hdd_db.sh
> 
> It will add a 2nd database entry for any drives named "WDC WDxxxxx". For example:
> 
> 1. WDC WD60EFRX-68L0BN1
> 2. WD60EFRX-68L0BN1
> 
> It won't hurt to have the extra entries in the database.

Output from the new branch...

```
bash-4.4# /volume1/homes/syno_hdd_db.sh
HDD/SSD models found: 10
WD140EMFZ-11A0WA0,81.00A81
WD80EFZX-68UW8N0,83.H0A83
WD80EMAZ-00WJTA0,83.H0A83
WD80EZAZ-11TDBA0,83.H0A83
WDC WD140EMFZ-11A0WA0,81.00A81
WDC WD80EFZX-68UW8N0,83.H0A83
WDC WD80EMAZ-00WJTA0,83.H0A83
WDC WD80EZAZ-11TDBA0,83.H0A83
WDC  WDS100T1R0A-68A4W0,411000WR
WDS100T1R0A-68A4W0,411000WR

NVMe drive models found: 1
WD Red SN700 1000GB,111150WD

WD140EMFZ-11A0WA0 already exists in ds2422+_host_v7.db
WD140EMFZ-11A0WA0 already exists in ds2422+_host_v7.db.new
WD80EFZX-68UW8N0 already exists in ds2422+_host_v7.db
WD80EFZX-68UW8N0 already exists in ds2422+_host_v7.db.new
WD80EMAZ-00WJTA0 already exists in ds2422+_host_v7.db
WD80EMAZ-00WJTA0 already exists in ds2422+_host_v7.db.new
WD80EZAZ-11TDBA0 already exists in ds2422+_host_v7.db
WD80EZAZ-11TDBA0 already exists in ds2422+_host_v7.db.new
WDC WD140EMFZ-11A0WA0 already exists in ds2422+_host_v7.db
WDC WD140EMFZ-11A0WA0 already exists in ds2422+_host_v7.db.new
WDC WD80EFZX-68UW8N0 already exists in ds2422+_host_v7.db
WDC WD80EFZX-68UW8N0 already exists in ds2422+_host_v7.db.new
WDC WD80EMAZ-00WJTA0 already exists in ds2422+_host_v7.db
WDC WD80EMAZ-00WJTA0 already exists in ds2422+_host_v7.db.new
WDC WD80EZAZ-11TDBA0 already exists in ds2422+_host_v7.db
WDC WD80EZAZ-11TDBA0 already exists in ds2422+_host_v7.db.new
WDC  WDS100T1R0A-68A4W0 already exists in ds2422+_host_v7.db
WDC  WDS100T1R0A-68A4W0 already exists in ds2422+_host_v7.db.new
WDS100T1R0A-68A4W0 already exists in ds2422+_host_v7.db
WDS100T1R0A-68A4W0 already exists in ds2422+_host_v7.db.new
WD Red SN700 1000GB already exists in ds2422+_host_v7.db
WD Red SN700 1000GB already exists in ds2422+_host_v7.db.new
```

**Comment by brimur** [comment]
Just rebooted the NAS and the drives are still reporting as unverified except for the one SSD , WDC  WDS100T1R0A-68A4W0

**Comment by 007revad** [comment]
There's an updated version available that will hopefully solve your issue. 
https://github.com/007revad/Synology_HDD_db/releases/tag/V1.0.6

**Comment by iraklis10** [comment]
> There's an updated version available that will hopefully solve your issue. https://github.com/007revad/Synology_HDD_db/releases/tag/V1.0.6

Thank you so much for this - I can confirm it worked perfectly on my DS2422+

```bash syno_hdd_db.sh
HDD/SSD models found: 1
HGST HDN726060ALE614,APGNW7JH

cat: '/sys/class/nvme/*/model': No such file or directory
cat: '/sys/class/nvme/*/firmware_rev': No such file or directory
No NVMe drives found

Added HGST HDN726060ALE614 to ds2422+_host_v7.db
Added HGST HDN726060ALE614 to ds2422+_host_v7.db.new

You may need to reboot the Synology to see the changes.

**Comment by brimur** [comment]
All good here too. Thanks very much! Great to login and see the green Healthy status :)
