### ISSUE TITLE
Please reincarnate true read-write SSD cache aka Sequential I/O checkbox when setting up new SSD cache

### ISSUE THREAD

**Issue by blogthis1** [007revad/Synology_HDD_db#111]
Hello!

I found you and your HDD-db and other Synology scripts on reddit today and nearly had a stroke I was so excited.  I am, like so many others, extremely grateful for your excellent ongoing work on Synology community projects!

My request is DIFFERENT than your existing similar-sounding Cache feature request-57: Enable changing the file size upper threshold for read cache - https://github.com/007revad/Synology_HDD_db/issues/57

This unique request/issue is likely "easy" for you with a very large positive impact on the community:

After much experimentation with "unsupported" downgrades of DSM, I've observed the original, true read-write SSD caching code from DSM 6.2.4 is STILL within DSM 7.0.1/7.1.1+.  However, the "Sequential I/O" checkbox to enable true read-write SSD cache (write-Back) in DSM 6.2.4 during its creation and setup, has been removed from the GUI in DSM 7.0.1+.

This means you can no longer re-enable by GUI the true read/write write-Back cache aka "Sequential I/O" when setting up the SSD cache, presumably to extend the lifespan of SSD's and/or to kill performance on lower-end units to promote sales of their "enterprise" products.

This ALSO means, if you downgrade a DSM to 6.2.4, I believe someone with your skills can see how the SSD cache parameters is being created (when that optional but hugely important "Sequential I/O" write-Back cache box is checked), to then carry it over to a new script for DSM 7.1+.

Note, I do not care about SSD lifespans or the M.2+SATA SSD cache mix, but I do have limited budgets, and desperately need it to again be as fast as possible at all times. Especially when writing many thousands of files to storage.  It used to cache them all in SSD and slowly write over time to the HDD's with low IOPS, which was able to do full 10G Ethernet wire-speed on my DS3617xs, but now it refuses to do so and has absolutely KILLED performance to LESS than HALF.

It is obvious to me, after finding you and your multiple scripts and reddit posts, that if anyone can fix this Synology sabotage of their own lower-end products to re-enable them to once again perform as good as they used to, now I know it is you!

Please see my old post/rant about Synology castrating their SSD caching subsystem for more details:
https://www.synoforum.com/threads/oh-no-dsm-7-1-removed-critical-ssd-nvme-cache-functionality.8899/

I humbly suggest this be a new script/project, as this SSD cache "re-enable" request isn't really in alignment with your amazing HDD-Database script where I am posting this now.

Thanks so much for your kind consideration and all that you do!

**Comment by 007revad** [comment]
> Please see my old post/rant about Synology castrating their SSD caching subsystem for more details:
> https://www.synoforum.com/threads/oh-no-dsm-7-1-removed-critical-ssd-nvme-cache-functionality.8899/

Reading your post on synoforum raises the question what was the behaviour in DSM 7.0? Was it the same as DSM 6.2.4? if it was it will be much easier for me to compare 7.0 to 7.0.1

**Comment by blogthis1** [comment]
Sorry I don't know.  I was too afraid of DSM 7.0.0 because it always said beta for DS3617xs, then jumped straight to 7.0.1 for release on DS3617xs - when is when I upgraded.

It's very possible the initial release of 7.0.0 or 7.0.1 WITHOUT any updates, may have the "Sequential I/O" option appear in the GUI wizard (during creating an SSD cache) - IF its option appears, as a checkbox option, then the answer to your question is Yes.

Note:  DSM 7.0.0 did not support E10M20-T1 on the DS3617xs, but in DSM 7.0.1 support was added for that card. Synology had to recompile a newer linux kernel for DS3617xs DSM 7.0.1 to support NVMe drives, so this is not just a simple matter of a setting.  Its as if that DSM version 7.0.0 was somewhat "in-between" kernel versions and advertised features of 6.2.4 vs 7.0.1...

Thanks so much for following up!

**Comment by 007revad** [comment]
> Thanks so much for following up!

Sorry I didn't reply earlier. Somehow I missed this issue. Or maybe I replied to easier to answer issues and forgot to come back to this more difficult one.

This may take a while to figure out.

**Comment by blogthis1** [comment]
I was being sincere when I said thanks for following up to your earlier reply, because you did reply to this right away (a couple weeks ago now).

Because the Sequential I/O is only a flag option set when creating new flash cache, and for sure we know the code is still there from storage pool cache created in DSM 6.2.4, I'm hoping it may be easier than you think (e.g. with flag or as an interactive scripting cache option, to add the cache with this option to existing storage pool).

**Comment by 007revad** [comment]
@blogthis1 

I've finally found the answer to enabling sequential I/O for SSD caches in DSM 7.2.1
https://github.com/007revad/Synology_enable_sequential_IO
