### ISSUE TITLE
Still getting the Firmware message :(

### ISSUE THREAD

**Issue by Yousif1702** [007revad/Synology_HDD_db#114]
Hi there,

awesome scripts - thank you for your work! I was successful in activating my Crucial NVME SSD for pool storage on my DS920+.
However I do it, though, I still get the following error message:

<img width="728" alt="Bildschirmfoto 2023-07-09 um 15 02 19" src="https://github.com/007revad/Synology_HDD_db/assets/139054748/1cb5a029-2dd5-4119-a30e-6b2560fe36e2">

What can I do about that? Other than that, everything is working fine, so it's not the end of the world. But would be nice to get it fixed. :)

Thank you again!!!

**Comment by 007revad** [comment]
What does the following command return:
`sudo -i jq . /var.defaults/lib/disk-compatibility/ds920+_host_v7.db | grep -A 1 CT500P3PSSD8`

**Comment by Yousif1702** [comment]
So I executed the mentioned command and the output.log is completely empty. Am I doing that wrong or is that plausible?

**Comment by 007revad** [comment]
Try this version: https://github.com/007revad/Synology_HDD_db/releases/tag/v3.1.60-RC

**Comment by 007revad** [comment]
Can you run the script again with the -snf options `syno_hdd_db.sh -snf` them copy the output and paste it in your reply.

**Comment by Yousif1702** [comment]
Synology_HDD_db v3.1.60
DS920+ DSM 7.2-64570-1 
Using options: -snf

HDD/SSD models found: 3
ST16000NM000J-2TW103,SCE2
ST4000VN008-2DR166,SC60
WD40EFPX-68C6CN0,81.00A81

M.2 drive models found: 1
CT500P3PSSD8,P9CR40A

No M.2 PCIe cards found

No Expansion Units found

[0;33mST16000NM000J-2TW103[0m already exists in [0;36mds920+_host.db[0m
[0;33mST16000NM000J-2TW103[0m already exists in [0;36mds920+_host_v7.db[0m
[0;33mST16000NM000J-2TW103[0m already exists in [0;36mds920+_host_v7.db.new[0m
[0;33mST16000NM000J-2TW103[0m already exists in [0;36mds920+_host.db.new[0m
[0;33mST4000VN008-2DR166[0m already exists in [0;36mds920+_host.db[0m
[0;33mST4000VN008-2DR166[0m already exists in [0;36mds920+_host_v7.db[0m
[0;33mST4000VN008-2DR166[0m already exists in [0;36mds920+_host_v7.db.new[0m
[0;33mST4000VN008-2DR166[0m already exists in [0;36mds920+_host.db.new[0m
[0;33mWD40EFPX-68C6CN0[0m already exists in [0;36mds920+_host.db[0m
[0;33mWD40EFPX-68C6CN0[0m already exists in [0;36mds920+_host_v7.db[0m
[0;33mWD40EFPX-68C6CN0[0m already exists in [0;36mds920+_host_v7.db.new[0m
[0;33mWD40EFPX-68C6CN0[0m already exists in [0;36mds920+_host.db.new[0m
[0;33mCT500P3PSSD8[0m already exists in [0;36mds920+_host.db[0m
[0;33mCT500P3PSSD8[0m already exists in [0;36mds920+_host_v7.db[0m
[0;33mCT500P3PSSD8[0m already exists in [0;36mds920+_host_v7.db.new[0m
[0;33mCT500P3PSSD8[0m already exists in [0;36mds920+_host.db.new[0m

Disabled support disk compatibility.

Support memory compatibility already enabled.

M.2 volume support already enabled.

Drive db auto updates already disabled.

      "model": "ST16000NM000J-2TW103",
      "firmware": "",
      "rec_intvl": [

      "model": "ST4000VN008-2DR166",
      "firmware": "SC60",
      "rec_intvl": [

      "model": "WD40EFPX-68C6CN0",
      "firmware": "",
      "rec_intvl": [

      "model": "CT500P3PSSD8",
      "firmware": "",
      "rec_intvl": [

DSM successfully checked disk compatibility.

You may need to [0;36mreboot the Synology[0m to see the changes.

**Comment by Yousif1702** [comment]
Rebooted the NAS after this and the firmware message still persits.

**Comment by 007revad** [comment]
I can see you previously had DSM 6 installed before updating to DSM 7

It's interesting (to me) that the last db file edited was an old DSM 6 file so the script showed edits made to the old ds920+_host.db file instead of the ds920+_host_v7.db file.

If you run this command again what does it output?
`sudo -i jq . /var.defaults/lib/disk-compatibility/ds920+_host_v7.db | grep -A 1 CT500P3PSSD8`

**Comment by Yousif1702** [comment]
Yea, that's correct. I upgraded from DSM 6 to 7 RC and then to the final version.
The log is empty for sudo -i jq . /var.defaults/lib/disk-compatibility/ds920+_host_v7.db | grep -A 1 CT500P3PSSD8

**Comment by Yousif1702** [comment]
Tried the same for the non-"v7".db:
jq: error: Could not open file /var.defaults/lib/disk-compatibility/ds920+_host.db: No such file or directory

**Comment by 007revad** [comment]
I'm assuming you have home folders enabled on your Synology.

Do NOT run the following as root. Run them as an admin or user.

Can you run these 2 commands:
```
mkdir $HOME/var.defaults
sudo -i cp /var.defaults/lib/disk-compatibility/* $HOME/var.defaults/
```

Then run these 2 commands:
```
mkdir $HOME/var
sudo -i cp /var/lib/disk-compatibility/* $HOME/var/
```

Then go to your home folder and zip or tar the **var.defaults** and **var** folders and attach the zip or tar files to your reply.

**Comment by 007revad** [comment]
If your user name in DSM is Yousif you would run the following 4 lines in task scheduler as root:
```
mkdir /var/services/homes/Yousif/var.defaults 
cp /var.defaults/lib/disk-compatibility/* /var/services/homes/Yousif/var.defaults/
mkdir /var/services/homes/Yousif/var 
cp /var/lib/disk-compatibility/* /var/services/homes/Yousif/var/
```
Obviously if your user name is not Yousif you'd change Yousif to your user name.

**Comment by Yousif1702** [comment]
Got the following output:
cp: -r not specified; omitting directory '/var.defaults/lib/disk-compatibility/rules'
cp: -r not specified; omitting directory '/var/lib/disk-compatibility/rules'

Folders were created, though. PFA

[home.zip](https://github.com/007revad/Synology_HDD_db/files/12002118/home.zip)

**Comment by 007revad** [comment]
Can you try these commands:
```
hdmodel=CT500P3PSSD8
sed -i "s/$hdmodel\",\"firmware\":\"/$hdmodel\",\"firmware\":\"P9CR40A/" "/var/lib/disk-compatibility/ds920+_host.db"
```

Then reboot.

**Comment by Yousif1702** [comment]
Still the same :(

**Comment by 007revad** [comment]
Have you previously run the Synology_enable_M2_volume script?

If yes, then run it with the --restore option then reboot. Note: the Synology may take up to 10 minutes to reboot.
