### ISSUE TITLE
Confirmed working on 918 :

### ISSUE THREAD

**Issue by Frankosor** [007revad/Synology_HDD_db#115]
DS918+ 
2. X Samsung NVMe M.2 SSD 970 EVO Plus  500Go
DS918+ Samsung SSD 970 EVO Plus  500Go
DSM 7.1.1-42962 Update 5
Script version : v3.1.60-RC
1 NVMe M.2 for read cache
1 NVMe M.2 for volume

Work perfectly!!!

**Comment by 1136623363** [comment]
How to achieve it？i have run `./syno_hdd_db.sh -fr`，but it cannot be achieved

`oot@LIANG:/volume1/scripts/Synology_HDD_db-3.1.64# ./syno_hdd_db.sh 
Synology_HDD_db v3.1.64
DS918+ DSM 7.2-64570-3 
Using options: 
Running from: /volume1/scripts/Synology_HDD_db-3.1.64/syno_hdd_db.sh

HDD/SSD models found: 1
SL500 250GB,ZD0R3G09

M.2 drive models found: 1
HYV1TBX3(Pro),H220906a

No M.2 PCIe cards found

No Expansion Units found

SL500 250GB already exists in ds918+_host_v7.db
HYV1TBX3(Pro) already exists in ds918+_host_v7.db

Re-enabled support disk compatibility.

Re-enabled support memory compatibility.

M.2 volume support already enabled.

Drive db auto updates already enabled.

DSM successfully checked disk compatibility.

You may need to reboot the Synology to see the changes.`

**Comment by 007revad** [comment]
> How to achieve it？i have run `./syno_hdd_db.sh -fr`，but it cannot be achieved

Try running with the -n option.

`./syno_hdd_db.sh -nr`
