### ISSUE TITLE
E10M20-T1 Integration

### ISSUE THREAD

**Issue by AndrewTapp** [007revad/Synology_HDD_db#116]
First, many thanks for all the hard work you do here, it's much appreciated and very useful.

I've just added a E10M20-T1 card to my DS1823xs+ (DSM 7.2-64570-1) and although the script appears to have run without issue and found the new card, none of it's functionality appears to be present i.e. the two M2 SSD drives and/or the 10Gb network port.

I've attached a couple pictures of my current setup and also the latest run of the script for your information.

I'm expecting to see the two additional M2 SSD's from the card, in addition to the built-in M2 SSD's, making 4 in total, all are using  the KINGSTON SFYRD4000G,EIFK31.6 SSD.

I don't know if it's possible to use the 10Gb network port on the card as well, as that also seems to not be present.

Any help would be appreciated.

[001.txt](https://github.com/007revad/Synology_HDD_db/files/12037855/001.txt)
![001a](https://github.com/007revad/Synology_HDD_db/assets/83402277/46c9e0ea-0219-4063-a111-d7286fbeaf2b)
![001b](https://github.com/007revad/Synology_HDD_db/assets/83402277/795817ec-cfae-47b6-9919-2dc84209250a)

**Comment by 007revad** [comment]
Can you try this version of the script then reboot:
https://github.com/007revad/Synology_HDD_db/releases/tag/v3.1.60-RC

**Comment by AndrewTapp** [comment]
Many many thanks for that, works a treat with no issues at all.

All SSD's and the network port now show.

Have created an SSD cache against Volume 2 with the PCIe card, so both volumes are now cached.

Have also created a network bond with the with the internal 10Gb port plus the 10Gb port from the PCIe card.

If I can be of any help in the future please do not hesitate to reach out.

Again many thanks for all your hard work here, take care.

![002a](https://github.com/007revad/Synology_HDD_db/assets/83402277/818acf5b-30fe-49a9-be84-22f2bd8aa8e4)
![002b](https://github.com/007revad/Synology_HDD_db/assets/83402277/fc58ec58-e0b0-4c3f-bab7-f670a229bb18)

**Comment by 007revad** [comment]
Awesome.
