### ISSUE TITLE
[Wanted] Someone with an expansion unit to help with detecting the expansion unit model.

### ISSUE THREAD

**Issue by 007revad** [007revad/Synology_HDD_db#12]
As I don't have an expansion unit I'm looking for help working out how to detect if an expansion unit is connected, and what model it is.

In DSM 7 on my DS1821+ the /etc.defaults/synoinfo.conf contains:
support_ew_20="yes"
support_ew_20_eunit="Synology-DX517,Synology-RX418"

And /var.defaults/lib/disk-compatibility/ has the following expansion unit db files:
dx5_v7.db
dx213_v7.db
dx510_v7.db
dx513_v7.db
**dx517_v7.db**
dx1211_v7.db
dx1215_v7.db
dx1215ii_v7.db
dx1222_v7.db
fx2421_v7.db
rx4_v7.db
rx410_v7.db
rx415_v7.db
**rx418_v7.db**
rx1211_v7.db
rx1211rp_v7.db
rx1213sas_v7.db
rx1214_v7.db
rx1214rp_v7.db
rx1216sas_v7.db
rx1217_v7.db
rx1217rp_v7.db
rx1217sas_v7.db
rx1222sas_v7.db
rx1223rp_v7.db
rx1224rp_v7.db
rx2417sas_v7.db
rx6022sas_v7.db
rxd1215sas_v7.db
rxd1219sas_v7.db

That's 30 different expansion unit models, even though synoinfo.conf seems to suggest that only 2 of them are supported.

If I run the following command it returns DX517:

`sudo cat /sys/firmware/devicetree/base/DX517/name`

I've never had a DX517 connected to this Synology, but I did buy it 2nd hand so maybe the previous has a DX517.

**Comment by aferende** [comment]
Hi 007revad,
I'm not a linux expert but I'm ready and happy to collaborate.
I have like you a DS1821+ with 2 DX517 expansion units attached and the 2 full M2 slots with 2 NVME 2 TB (Crucial CT2000P3SSD8)

I confirm that I get the same results as you.

I am attaching my sysinfo.conf file, the command output
[synoinfo.conf.txt](https://github.com/007revad/Synology_HDD_db/files/11008087/synoinfo.conf.txt)

`sudo lspci -t -vv`

![ss2](https://user-images.githubusercontent.com/13355101/226097062-f6e00719-3d9d-46e8-b468-3e2b2950dd27.jpg)

and some screenshots of my NAS in case it's helpful.

![ss1](https://user-images.githubusercontent.com/13355101/226097061-0f99f80b-1715-4ca6-8c0a-dfc328a26255.jpg)

![ss3](https://user-images.githubusercontent.com/13355101/226097063-19c94524-bd59-43ab-9374-e5277415a7fb.jpg)


Let me know if you need more specific info.
Andrea.

**Comment by dwabraxus** [comment]
I also have multiple expansion units, this CLI command works to show connected units in my RS3614XS+. Willing to do more testing as needed.

`cat /var/log/disk_log.xml | grep -Eow "([RXD]{2}[0-9]{4})" | uniq`

**Comment by aferende** [comment]
File `/var/log/disk_log.xml` doesn't exists on my DS1821+

**Comment by 007revad** [comment]
My old Synology running DSM 6.2.4 has a /var/log/disk_log.xml but it only has entries from 2015 to 2018 (and they only list drive errors).

But there is a /var/log/disk.log (which I think is what @dwabraxus meant). The disk.log seems to get updated at boot and when you hotplug a drive.

Can you try:

cat /var/log/disk.log | grep -Eow "([FRD]XD?[0-9]{3,4})(RP|II|sas){0,2}" | uniq

I'd actually like to see the whole line as well:

cat /var/log/disk.log | grep -E "([FRD]XD?[0-9]{3,4})"

**Comment by aferende** [comment]
In my NAS both command returns an empty result

**Comment by 007revad** [comment]
Can you run the following command as a user which will copy your disk.log file to your home folder.

`sudo cp /var/log/disk.log ~`

Then attach the disk.log file to your reply.

**Comment by aferende** [comment]
Here the file
[disk.log](https://github.com/007revad/Synology_HDD_db/files/11009889/disk.log)

**Comment by dwabraxus** [comment]
I actually have a `disk_log.xml` file. But it appears like it might be leftover from an older OS, no recent changes.

Had to add `.txt` to get it to upload

[disk_log.xml.txt](https://github.com/007revad/Synology_HDD_db/files/11009892/disk_log.xml.txt)

**Comment by dwabraxus** [comment]
I also found the info here:
`/var/log/diskprediction`

```
cd /var/log/diskprediction

ash-4.3# cat data-2023-03-18.json | grep container | jq .disks[1].container
"RS3614xs"
ash-4.3# cat data-2023-03-18.json | grep container | jq .disks[20].container
"RX1217-1"
ash-4.3# cat data-2023-03-18.json | grep container | jq .disks[19].container
"RX1217-1"
ash-4.3# cat data-2023-03-18.json | grep container | jq .disks[15].container
"RX1217-1"
ash-4.3# cat data-2023-03-18.json | grep container | jq .disks[30].container
"RX1214-2"
```

**Comment by 007revad** [comment]
> But it appears like it might be leftover from an older OS, no recent changes.

Yep. I noticed the last entry was 2018.

**Comment by 007revad** [comment]
Can someone try this:

`for f in /var/log/diskprediction/*.json; do grep -Eow "([FRD]XD?[0-9]{3,4})(RP|II|sas){0,2}" "$f" | uniq; done`

On my test files it is returning:
```
DX517
DX1215II
RX1216RPsas
FX2421
RX6022sas
RX1223RP
```

**Comment by 007revad** [comment]
I'm curious if the following command  includes the expansion unit model:

`synodisk --enum -t ebox`

**Comment by dwabraxus** [comment]
Uniq is only applied to each file, not overall, so I have lots of dupes

```ash-4.3# for f in /var/log/diskprediction/*.json; do grep -Eow "([FRD]XD?[0-9]{3,4})(RP|II|sas){0,2}" "$f" | uniq; done
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
RX1217
RX1214
ash-4.3#```

**Comment by dwabraxus** [comment]
No expansion info in the below command

```ash-4.3# synodisk --enum -t ebox
************ Disk Info ***************
>> Disk id: 1
>> Slot id: -1
>> Disk path: /dev/sdma
>> Disk model: WD8001FFWX-68J1UN0
>> Total capacity: 7452.04 GB
>> Tempeture: 40 C
************ Disk Info ***************
>> Disk id: 2
>> Slot id: -1
>> Disk path: /dev/sdmb
>> Disk model: WD8001FFWX-68J1UN0
>> Total capacity: 7452.04 GB
>> Tempeture: 40 C
************ Disk Info ***************
>> Disk id: 3
>> Slot id: -1
>> Disk path: /dev/sdmc
>> Disk model: WD8001FFWX-68J1UN0
>> Total capacity: 7452.04 GB
>> Tempeture: 39 C
************ Disk Info ***************
>> Disk id: 4
>> Slot id: -1
>> Disk path: /dev/sdna
>> Disk model: WD8001FFWX-68J1UN0
>> Total capacity: 7452.04 GB
>> Tempeture: 37 C
************ Disk Info ***************
>> Disk id: 5
>> Slot id: -1
>> Disk path: /dev/sdnb
>> Disk model: WD8001FFWX-68J1UN0
>> Total capacity: 7452.04 GB
>> Tempeture: 42 C
************ Disk Info ***************
>> Disk id: 6
>> Slot id: -1
>> Disk path: /dev/sdnc
>> Disk model: WD8001FFWX-68J1UN0
>> Total capacity: 7452.04 GB
>> Tempeture: 42 C
************ Disk Info ***************
>> Disk id: 7
>> Slot id: -1
>> Disk path: /dev/sdoa
>> Disk model: WD8001FFWX-68J1UN0
>> Total capacity: 7452.04 GB
>> Tempeture: 38 C
************ Disk Info ***************
>> Disk id: 8
>> Slot id: -1
>> Disk path: /dev/sdob
>> Disk model: WD8003FFBX-68B9AN0
>> Total capacity: 7452.04 GB
>> Tempeture: 39 C
************ Disk Info ***************
>> Disk id: 9
>> Slot id: -1
>> Disk path: /dev/sdoc
>> Disk model: WD8003FFBX-68B9AN0
>> Total capacity: 7452.04 GB
>> Tempeture: 44 C
************ Disk Info ***************
>> Disk id: 10
>> Slot id: -1
>> Disk path: /dev/sdpa
>> Disk model: WD8003FFBX-68B9AN0
>> Total capacity: 7452.04 GB
>> Tempeture: 43 C
************ Disk Info ***************
>> Disk id: 11
>> Slot id: -1
>> Disk path: /dev/sdpb
>> Disk model: SDLF1DAM-800G-1HA1
>> Total capacity: 745.21 GB
>> Tempeture: 37 C
************ Disk Info ***************
>> Disk id: 12
>> Slot id: -1
>> Disk path: /dev/sdpc
>> Disk model: SDLF1DAM-800G-1HA1
>> Total capacity: 745.21 GB
>> Tempeture: 37 C
************ Disk Info ***************
>> Disk id: 1
>> Slot id: -1
>> Disk path: /dev/sdqa
>> Disk model: WD30EFRX-68EUZN0
>> Total capacity: 2794.52 GB
>> Tempeture: 36 C
************ Disk Info ***************
>> Disk id: 2
>> Slot id: -1
>> Disk path: /dev/sdqb
>> Disk model: WD30EFRX-68AX9N0
>> Total capacity: 2794.52 GB
>> Tempeture: 36 C
************ Disk Info ***************
>> Disk id: 3
>> Slot id: -1
>> Disk path: /dev/sdqc
>> Disk model: WD30EFRX-68AX9N0
>> Total capacity: 2794.52 GB
>> Tempeture: 36 C
************ Disk Info ***************
>> Disk id: 4
>> Slot id: -1
>> Disk path: /dev/sdra
>> Disk model: WD30EFRX-68AX9N0
>> Total capacity: 2794.52 GB
>> Tempeture: 35 C
************ Disk Info ***************
>> Disk id: 5
>> Slot id: -1
>> Disk path: /dev/sdrb
>> Disk model: WD30EFRX-68EUZN0
>> Total capacity: 2794.52 GB
>> Tempeture: 36 C
************ Disk Info ***************
>> Disk id: 6
>> Slot id: -1
>> Disk path: /dev/sdrc
>> Disk model: WD30EFRX-68EUZN0
>> Total capacity: 2794.52 GB
>> Tempeture: 37 C
************ Disk Info ***************
>> Disk id: 7
>> Slot id: -1
>> Disk path: /dev/sdsa
>> Disk model: WD8003FFBX-68B9AN0
>> Total capacity: 7452.04 GB
>> Tempeture: 42 C
************ Disk Info ***************
>> Disk id: 8
>> Slot id: -1
>> Disk path: /dev/sdsb
>> Disk model: WD8003FFBX-68B9AN0
>> Total capacity: 7452.04 GB
>> Tempeture: 41 C
************ Disk Info ***************
>> Disk id: 9
>> Slot id: -1
>> Disk path: /dev/sdsc
>> Disk model: WD8003FFBX-68B9AN0
>> Total capacity: 7452.04 GB
>> Tempeture: 43 C
************ Disk Info ***************
>> Disk id: 10
>> Slot id: -1
>> Disk path: /dev/sdta
>> Disk model: WD8003FFBX-68B9AN0
>> Total capacity: 7452.04 GB
>> Tempeture: 42 C
************ Disk Info ***************
>> Disk id: 11
>> Slot id: -1
>> Disk path: /dev/sdtb
>> Disk model: CT500MX500SSD1
>> Total capacity: 465.76 GB
>> Tempeture: 42 C
************ Disk Info ***************
>> Disk id: 12
>> Slot id: -1
>> Disk path: /dev/sdtc
>> Disk model: CT500MX500SSD1
>> Total capacity: 465.76 GB
>> Tempeture: 38 C
```

**Comment by dwabraxus** [comment]
Updated command here seems to work for me without dupes

```ls -lah /var/log/diskprediction | tail -n1 | awk -F " " '{print $NF}' | grep -Eow "([FRD]XD?[0-9]{3,4})(RP|II|sas){0,2}" "$f" | sort -n |  uniq```

**Comment by 007revad** [comment]
> No expansion info in the below command

Thank you. So `synodisk --enum -t ebox` just provides info on the disks in the expansion boxes.

**Comment by 007revad** [comment]
This looks like the solution as both DSM 6 and DSM 7 have `/var/log/diskprediction/data-yyyy-mm-dd.json` files.

ls -lah /var/log/diskprediction | tail -n1 | awk -F " " '{print $NF}' | grep -Eow "([FRD]XD?[0-9]{3,4})(RP|II|sas){0,2}" "$f" | sort -n |  uniq

**Comment by aferende** [comment]
In my NAS command result is "no such file or directory" ... but file exists:

![ss0](https://user-images.githubusercontent.com/13355101/226168057-45cf7abf-6413-43d0-8fc6-29a1818d051a.jpg)

Opening most recent json file and searching for my expansion unit I found this:

![ss1](https://user-images.githubusercontent.com/13355101/226168099-173b55ef-09ed-4b7e-8c6f-9e9a14aa1fab.jpg)

I attach json file:

[data-2023-03-19.json.txt](https://github.com/007revad/Synology_HDD_db/files/11010641/data-2023-03-19.json.txt)

**Comment by 007revad** [comment]
Try these 2 lines, one at a time, in order:

`path="/var/log/diskprediction"`

`file=$(ls $path | tail -n1) `

`grep -Eow "([FRD]XD?[0-9]{3,4})(RP|II|sas){0,2}" "$path/$file"`

You should see:
DX517
DX517

**Comment by aferende** [comment]
Here results:

`DX517
DX517
DX517
DX517
DX517
DX517
DX517
DX517
DX517
DX517`

**Comment by 007revad** [comment]
Excellent. I'm using those 3 lines to add the expansion units to an array, which then gets sorted to remove duplicates.

Do you want to test the develop version of the script?
https://github.com/007revad/Synology_HDD_db/blob/develop/syno_hdd_db.sh

**Comment by aferende** [comment]
Here results:

`syno_hdd_db.sh: line 190: rev: command not found
HDD/SSD models found: 3
ST16000NE000-2RW103,EN02
ST16000NM001G-2KK103,SN03
WDC WDS100T1R0A-68A4W0,00WR

M.2 drive models found: 1
CT2000P3SSD8,P9CR30A

Expansion Unit models found: 1
DX517

[41mERROR 3[0m /var/lib/disk-compatibility/_host_v7.db not found!
`

**Comment by 007revad** [comment]
That last error was because of the first error (rev: command not found). I just remembered you're using DSM 6.2.4 which doesn't have the rev command.

I've just updated develop version to fix that "rev: command not found" error.
https://github.com/007revad/Synology_HDD_db/blob/develop/syno_hdd_db.sh

**Comment by aferende** [comment]
HI Dave,
I'm using DSM 7.1.1 update 4.

Here script result:

`HDD/SSD models found: 3
ST16000NE000-2RW103,EN02
ST16000NM001G-2KK103,SN03
WDC WDS100T1R0A-68A4W0,00WR

M.2 drive models found: 1
CT2000P3SSD8,P9CR30A

Expansion Unit models found: 1
DX517

[41mERROR 3[0m /var/lib/disk-compatibility/ds920+
ds1821+`
ds920+_host_v7.db not found!

**Comment by 007revad** [comment]
So that means the rev command is new in DSM 7.2 beta.

Did you migrate some of the drive from a DS920+ to a DS1821+?

I've just updated develop version, again, to fix the model detection.
https://github.com/007revad/Synology_HDD_db/blob/develop/syno_hdd_db.sh

**Comment by aferende** [comment]
Yes, before the DS1821+ I had the DS920.
This is the result of the updated script:
```

HDD/SSD models found: 3
ST16000NE000-2RW103,EN02
ST16000NM001G-2KK103,SN03
WDC WDS100T1R0A-68A4W0,00WR

M.2 drive models found: 1
CT2000P3SSD8,P9CR30A

Expansion Unit models found: 1
DX517

[0;33mST16000NE000-2RW103[0m already exists in [0;36mds1821+_host_v7.db[0m
[0;33mST16000NE000-2RW103[0m already exists in [0;36mds1821+_host_v7.db.new[0m
[0;33mST16000NE000-2RW103[0m already exists in [0;36mdx517_v7.db[0m
[0;33mST16000NM001G-2KK103[0m already exists in [0;36mds1821+_host_v7.db[0m
[0;33mST16000NM001G-2KK103[0m already exists in [0;36mds1821+_host_v7.db.new[0m
[0;33mST16000NM001G-2KK103[0m already exists in [0;36mdx517_v7.db[0m
[0;33mWDC WDS100T1R0A-68A4W0[0m already exists in [0;36mds1821+_host_v7.db[0m
[0;33mWDC WDS100T1R0A-68A4W0[0m already exists in [0;36mds1821+_host_v7.db.new[0m
[0;33mWDC WDS100T1R0A-68A4W0[0m already exists in [0;36mdx517_v7.db[0m
[0;33mCT2000P3SSD8[0m already exists in [0;36mds1821+_host_v7.db[0m
[0;33mCT2000P3SSD8[0m already exists in [0;36mds1821+_host_v7.db.new[0m


M.2 volume support already enabled.

```

**Comment by 007revad** [comment]
That's perfect.

**Comment by dwabraxus** [comment]
I also tested on 6.2.4
Works on rs812 with rx412
Works on rs812+ with rx417
Works on rx3614xs+ with rx1214 and rx1217

Output from rx3614xs+
```
ash-4.3# ./syno_hdd_db.sh
HDD/SSD models found: 7
CT500MX500SSD1,M3CR
SDLF1DAM-800G-1HA1,ZR07
SSD 870 EVO 2TB,SVT0
WD30EFRX-68AX9N0,80.0
WD30EFRX-68EUZN0,82.0
WD8001FFWX-68J1UN0,83.H
WD8003FFBX-68B9AN0,83.0

No M.2 drives found

Expansion Unit models found: 2
RX1214
RX1217

Added CT500MX500SSD1 to rs3614xs_host.db
Added CT500MX500SSD1 to rs3614xs_host.db.new
CT500MX500SSD1 already exists in rx1214.db
Added CT500MX500SSD1 to rx1217.db
Added SDLF1DAM-800G-1HA1 to rs3614xs_host.db
Added SDLF1DAM-800G-1HA1 to rs3614xs_host.db.new
Added SDLF1DAM-800G-1HA1 to rx1214.db
Added SDLF1DAM-800G-1HA1 to rx1217.db
Added SSD 870 EVO 2TB to rs3614xs_host.db
Added SSD 870 EVO 2TB to rs3614xs_host.db.new
Added SSD 870 EVO 2TB to rx1214.db
Added SSD 870 EVO 2TB to rx1217.db
Added WD30EFRX-68AX9N0 to rs3614xs_host.db
Added WD30EFRX-68AX9N0 to rs3614xs_host.db.new
WD30EFRX-68AX9N0 already exists in rx1214.db
WD30EFRX-68AX9N0 already exists in rx1217.db
WD30EFRX-68EUZN0 already exists in rs3614xs_host.db
WD30EFRX-68EUZN0 already exists in rs3614xs_host.db.new
WD30EFRX-68EUZN0 already exists in rx1214.db
WD30EFRX-68EUZN0 already exists in rx1217.db
Added WD8001FFWX-68J1UN0 to rs3614xs_host.db
Added WD8001FFWX-68J1UN0 to rs3614xs_host.db.new
Added WD8001FFWX-68J1UN0 to rx1214.db
Added WD8001FFWX-68J1UN0 to rx1217.db
WD8003FFBX-68B9AN0 already exists in rs3614xs_host.db
WD8003FFBX-68B9AN0 already exists in rs3614xs_host.db.new
WD8003FFBX-68B9AN0 already exists in rx1214.db
WD8003FFBX-68B9AN0 already exists in rx1217.db

Backed up synoinfo.conf

Drive db auto updates already enabled.

You may need to reboot the Synology to see the changes.
ash-4.3# 
```

**Comment by AndrewTapp** [comment]
Many thanks for your hard work, much appreciated.

Am new to this, all looks good after running the script, not that I had any issues in the first place, but thought I would post my setup and output from the script for information.  Currently running DSM 7.1.1-42962 Update 4.

![image](https://user-images.githubusercontent.com/83402277/226185793-ffbc2a08-309c-43f8-9b1f-4f02d9bad66a.png)

![image](https://user-images.githubusercontent.com/83402277/226185842-21ec9aac-d76f-453c-a943-81e2830bb989.png)

HDD/SSD models found: 3
WD101KFBX-68R56N0,0A03
WD181KRYZ-01AGBB0,1H01
WD8001FFWX-68J1UN0,0A03

M.2 drive models found: 1
Samsung SSD 980 PRO 2TB,5B2QGXA7

Added WD101KFBX-68R56N0 to ds1821+_host_v7.db
Added WD101KFBX-68R56N0 to ds1821+_host_v7.db.new
Added WD181KRYZ-01AGBB0 to ds1821+_host_v7.db
Added WD181KRYZ-01AGBB0 to ds1821+_host_v7.db.new
Added WD8001FFWX-68J1UN0 to ds1821+_host_v7.db
Added WD8001FFWX-68J1UN0 to ds1821+_host_v7.db.new
Added Samsung SSD 980 PRO 2TB to ds1821+_host_v7.db
Added Samsung SSD 980 PRO 2TB to ds1821+_host_v7.db.new
Backed up synoinfo.conf to synoinfo.conf.bak
Disabled drive db auto updates.

Changes to ds1821+_host_v7.db
    },
    "WD101KFBX-68R56N0": {
      "default": {
        "compatibility_interval": [
          {
            "compatibility": "support",
            "not_yet_rolling_status": "support",
            "fw_dsm_update_status_notify": false,
            "barebone_installable": true
          }
        ]
      }
    },
    "WD181KRYZ-01AGBB0": {
      "default": {
        "compatibility_interval": [
          {
            "compatibility": "support",
            "not_yet_rolling_status": "support",
            "fw_dsm_update_status_notify": false,
            "barebone_installable": true
          }
        ]
      }
    },
    "WD8001FFWX-68J1UN0": {
      "default": {
        "compatibility_interval": [
          {
            "compatibility": "support",
            "not_yet_rolling_status": "support",
            "fw_dsm_update_status_notify": false,
            "barebone_installable": true
          }
        ]
      }
    },
    "Samsung SSD 980 PRO 2TB": {
      "default": {
        "compatibility_interval": [
          {
            "compatibility": "support",
            "not_yet_rolling_status": "support",
            "fw_dsm_update_status_notify": false,
            "barebone_installable": true
          }
        ]
      }
    }
  },
  "nas_model": "ds1821+"
}

DSM successfully checked disk compatibility.

**Comment by aferende** [comment]
@007revad what about storage pool creation using M2 slot with 7.2 beta?
Are you able to create it using unsupported NVME drive or we need a new script release?
Ty,
Andrea

**Comment by 007revad** [comment]
Using unsupported NVME drives to create a storage pool in DSM 7.2 beta is next on my to do list.
