### ISSUE TITLE
Compatibility with DX1222 expansion unit.

### ISSUE THREAD

**Issue by wisepds** [007revad/Synology_HDD_db#125]
I have a DS3622sx+ with a DX1222 expansion unit and the script doesn't work with this unit.
All units inside NAS works, but in the expansion unit = Red and not compatible.
Please, check this 
Thank you for your amazing work!

**Comment by 007revad** [comment]
Sorry, I forgot about you.

Does the script show that it found the DX1222 expansion unit?

Can you paste a copy of the script output?
