### ISSUE TITLE
Still cannot use NVMe storage pool with PCIe?

### ISSUE THREAD

**Issue by llitkr** [007revad/Synology_HDD_db#126]
Hi. Thanks for useful tool.

I read the article that NVMe SSD storage pool with PCIe card doesn't work more on DSM 7.2 u2.

Is it still unsolved? I'm confusing update my NAS' DSM or not.

**Comment by 007revad** [comment]
Synology says NVMe storage pools has never worked with PCIe cards. 

You need to run this script https://github.com/007revad/Synology_M2_volume to create the storage pool on NVMe drives in a PCIe card.

**Comment by llitkr** [comment]
Thank you @007revad . I updated my DSM to U2 and NVMe volume already exist was not disappeared.
