### ISSUE TITLE
Worm / Immutable snapshot not fully enabled

### ISSUE THREAD

**Issue by HOAP81** [007revad/Synology_HDD_db#127]
I tried enabling Immutable snapshots with your script but it left the function broken.

RS1219+ runing DSM 7.2 64570u2

After running the script the WORM and immutable snapshot functions appear in the GUI.
I can also set the system as a replication target with immutable snapshot enabled.

But
I cannot create a WORM-share on the system. It gives the error "The operation failed. Please sign in to DSM again and retry" on the confirm settings page (enterprise mode. I have not tried compliance mode).
Marking an existing snapshot as immutable is possible (or creating one using the system as a replication target) but the expiry timer is not counting down. So it appears my snapshot is immutable for ever.

Also setting the support_worm value back to "no" doesn't do anything. But I guess that would be by design.

**Comment by 007revad** [comment]
Don't try compliance mode or you'll have to wait 3.5 years to be able to edit or delete the files (or connect the drives a computer and format them).

Thanks for confirming that I need to do more to fully enable Worm on models older than '20 series. 

When I added the option to enable Worm I made the following note to myself:

> Synology says Immutable Snapshots are only available on '20 series and newer models. But we can enable them on other models that are using DSM 7.2 by running the following command:
> 
> `sudo synosetkeyvalue /etc.defaults/synoinfo.conf support_worm yes`
> 
> Will that work on all models using DSM 7.2... **I don't know**.
