### ISSUE TITLE
1.1.14 Fails to work on DS3622xs+

### ISSUE THREAD

**Issue by YerBabiE** [007revad/Synology_HDD_db#13]
I have 2 volumes:
First is a raid 6 pool, synology 18TB drives, no issue.
Second is a Raid 5 set of 3 drives consistensing of 3 x Unknown MZ7LM960HCHP-000V3 00Y), All the Same Firmeare GXT3CB31. It does not say so, but I believe these are a Samsung Drive from a Lenov Server. I have been using them for years with no issues. (Samsung PM863 MZ7LM960HCHP-00003 2.5in SFF).

The script runs fine:

HDD/SSD models found: 2
HAT5310-18T,1401
MZ7LM960HCHP-000V3 00Y,GXT3

HAT5310-18T already exists in ds3622xs+_host_v7.db
Added MZ7LM960HCHP-000V3 00Y to ds3622xs+_host_v7.db

and on second run:

HAT5310-18T already exists in ds3622xs+_host_v7.db
MZ7LM960HCHP-000V3 00Y already exists in ds3622xs+_host_v7.db

I have rebooted after install, but the drive status has not changed, still unverified.

System is a brand new DS3622xs+ running DSM 7.1.1-42962 Update 1.

Hope this helps... and is fixable, as at the moment I can't migrate my old server to this one with an "at risk" volume. THe migration fails.....

thanks,
YB

**Comment by YerBabiE** [comment]
Here is a copy of the db file:

{"disk_compatbility_info":{"SAT5200-1920G":{"SCEMJ2.1":{"fw_buildnumber":1,"firm_bin":"SCEMJ2.1.bin","compatibility_interval":[{"compatibility":"support"}]},"default":{"compatibility_interval":[{"compatibility":"support"}]}},"SAT5200-960G":{"SCEMJ2.1":{"fw_buildnumber":1,"firm_bin":"SCEMJ2.1.bin","compatibility_interval":[{"compatibility":"support"}]},"default":{"compatibility_interval":[{"compatibility":"support"}]}},"SAT5200-480G":{"SCEMJ2.1":{"fw_buildnumber":1,"firm_bin":"SCEMJ2.1.bin","compatibility_interval":[{"compatibility":"support"}]},"default":{"compatibility_interval":[{"compatibility":"support"}]}},"HAT5300-8T":{"1401":{"fw_buildnumber":1,"firm_bin":"MG06_SATA_1401.ftd","compatibility_interval":[{"compatibility":"support"}]},"default":{"compatibility_interval":[{"compatibility":"support"}]}},"HAT5300-12T":{"1401":{"fw_buildnumber":1,"firm_bin":"MG07_SATA_1401.ftd","compatibility_interval":[{"compatibility":"support"}]},"default":{"compatibility_interval":[{"compatibility":"support"}]}},"SAT5200-3840G":{"SCEMJ2.1":{"fw_buildnumber":1,"firm_bin":"SCEMJ2.1.bin","compatibility_interval":[{"compatibility":"support"}]},"default":{"compatibility_interval":[{"compatibility":"support"}]}},"HAT5300-16T":{"1401":{"fw_buildnumber":1,"firm_bin":"MG08_SATA_1401.ftd","compatibility_interval":[{"compatibility":"support"}]},"1402":{"fw_buildnumber":2,"firm_bin":"MG08_SATA_1402.ftd","compatibility_interval":[{"compatibility":"support"}]},"default":{"compatibility_interval":[{"compatibility":"support"}]}},"HUS726T4TALE6L4":{"VKGNW40H":{"compatibility_interval":[{"compatibility":"support"}]},"default":{"compatibility_interval":[{"compatibility":"support"}]}},"SAT5210-3840G":{"SCEMH3.1":{"fw_buildnumber":1,"firm_bin":"SCEMH3.1.bin","compatibility_interval":[{"compatibility":"support"}]},"SCEMH3.2":{"fw_buildnumber":2,"firm_bin":"SCEMH3.2.bin","compatibility_interval":[{"compatibility":"support"}]},"default":{"compatibility_interval":[{"compatibility":"support"}]}},"SAT5210-1920G":{"SCEMH3.1":{"fw_buildnumber":1,"firm_bin":"SCEMH3.1.bin","compatibility_interval":[{"compatibility":"support"}]},"SCEMH3.2":{"fw_buildnumber":2,"firm_bin":"SCEMH3.2.bin","compatibility_interval":[{"compatibility":"support"}]},"default":{"compatibility_interval":[{"compatibility":"support"}]}},"SAT5210-480G":{"SCEMH3.1":{"fw_buildnumber":1,"firm_bin":"SCEMH3.1.bin","compatibility_interval":[{"compatibility":"support"}]},"SCEMH3.2":{"fw_buildnumber":2,"firm_bin":"SCEMH3.2.bin","compatibility_interval":[{"compatibility":"support"}]},"default":{"compatibility_interval":[{"compatibility":"support"}]}},"SAT5210-960G":{"SCEMH3.1":{"fw_buildnumber":1,"firm_bin":"SCEMH3.1.bin","compatibility_interval":[{"compatibility":"support"}]},"SCEMH3.2":{"fw_buildnumber":2,"firm_bin":"SCEMH3.2.bin","compatibility_interval":[{"compatibility":"support"}]},"default":{"compatibility_interval":[{"compatibility":"support"}]}},"HAT5300-4T":{"1401":{"fw_buildnumber":1,"firm_bin":"MG08_SATA_4T_1401.ftd","compatibility_interval":[{"compatibility":"support"}]},"1402":{"fw_buildnumber":2,"firm_bin":"MG08_SATA_4T_1402.ftd","compatibility_interval":[{"compatibility":"support"}]},"default":{"compatibility_interval":[{"compatibility":"support"}]}},"HAT5310-8T":{"1401":{"fw_buildnumber":1,"firm_bin":"MG08_SATA_8T_1401.ftd","compatibility_interval":[{"compatibility":"support"}]},"default":{"compatibility_interval":[{"compatibility":"support"}]}},"HAT5310-18T":{"1401":{"fw_buildnumber":1,"firm_bin":"MG09_SATA_18T_1401.ftd","compatibility_interval":[{"compatibility":"support"}]},"default":{"compatibility_interval":[{"compatibility":"support"}]}}},"nas_model":"ds3622xs+"}

**Comment by 007revad** [comment]
Google doesn't find many results when I search for "MZ7LM960HMJP-000V3 00Y". The closest I could find was on ebay Italy https://www.ebay.it/itm/294924530306 which is selling some decade old Lenovo SSDs. 

- MZ7LM240HCGR-000V3 00YC390
- MZ7LM240HCGR-000V3 00YC391
- MZ7LM240HCGR-000V3 00YC394

I searched in the disk compatibility files for a RS4021xs+ and found none of them have a " 00Y" string at the end.

> "MZ7LM240HMHQ": {
         "MZ7LH960HAJR-00005": {
         "MZILT1T9HAJQ/007": {
         "MZ-7PC512BWW": {```. 

So it looks like it needs to be "MZ7LM960HCHP-000V3" instead of "MZ7LM960HCHP-000V3 00Y".

Rather than just removing the " 00Y" I'd prefer see if I can get the model number without the "00Y".

Also can you run the following command which will copy your ds3622xs+_host_v7.db file to your home folder as ds3622xs+_host_v7.db.txt

`sudo cp /var/lib/disk-compatibility/ds3622xs+_host_v7.db ~/ds3622xs+_host_v7.db.txt`

Then attach the ds3622xs+_host_v7.db.txt file to your reply.

If possible, can you also attach photo of one of the MZ7LM960HCHP-000V3 drive's label.

**Comment by 007revad** [comment]
That host db file you pasted into your reply looks like the backup or it hasn't been edited. Was it from `/var.defaults/lib/disk-compatibility` or `/var/lib/disk-compatibility` ?

Can you run the following command which will copy your ds3622xs+_host_v7.db file to your home folder as ds3622xs+_host_v7.db.txt

`sudo cp /var/lib/disk-compatibility/ds3622xs+_host_v7.db ~/ds3622xs+_host_v7.db.txt`

Then attach the ds3622xs+_host_v7.db.txt file to your reply.

And if possible attach a photo of the label of one of the MZ7LM960HCHP-000V3 drives.

**Comment by YerBabiE** [comment]
Hi, the command I ran to get the above file was: sudo cp /var.defaults/lib/disk-compatibility/ds3622xs+_host_v7.db /volume1/test/ds3622xs+_host.db.txt

**Comment by YerBabiE** [comment]
![IMG_8106](https://user-images.githubusercontent.com/5387041/226151846-7796435a-a335-4a22-9242-1dd4f7aebe04.jpeg)
This is a picture of one of the drives.

**Comment by YerBabiE** [comment]
Here is the other DB file:

{"disk_compatbility_info":{"SAT5200-1920G":{"SCEMJ2.1":{"fw_buildnumber":1,"firm_bin":"SCEMJ2.1.bin","compatibility_interval":[{"compatibility":"support"}]},"default":{"compatibility_interval":[{"compatibility":"support"}]}},"SAT5200-960G":{"SCEMJ2.1":{"fw_buildnumber":1,"firm_bin":"SCEMJ2.1.bin","compatibility_interval":[{"compatibility":"support"}]},"default":{"compatibility_interval":[{"compatibility":"support"}]}},"SAT5200-480G":{"SCEMJ2.1":{"fw_buildnumber":1,"firm_bin":"SCEMJ2.1.bin","compatibility_interval":[{"compatibility":"support"}]},"default":{"compatibility_interval":[{"compatibility":"support"}]}},"HAT5300-8T":{"1401":{"fw_buildnumber":1,"firm_bin":"MG06_SATA_1401.ftd","compatibility_interval":[{"compatibility":"support"}]},"default":{"compatibility_interval":[{"compatibility":"support"}]}},"HAT5300-12T":{"1401":{"fw_buildnumber":1,"firm_bin":"MG07_SATA_1401.ftd","compatibility_interval":[{"compatibility":"support"}]},"default":{"compatibility_interval":[{"compatibility":"support"}]}},"SAT5200-3840G":{"SCEMJ2.1":{"fw_buildnumber":1,"firm_bin":"SCEMJ2.1.bin","compatibility_interval":[{"compatibility":"support"}]},"default":{"compatibility_interval":[{"compatibility":"support"}]}},"HAT5300-16T":{"1401":{"fw_buildnumber":1,"firm_bin":"MG08_SATA_1401.ftd","compatibility_interval":[{"compatibility":"support"}]},"1402":{"fw_buildnumber":2,"firm_bin":"MG08_SATA_1402.ftd","compatibility_interval":[{"compatibility":"support"}]},"default":{"compatibility_interval":[{"compatibility":"support"}]}},"HUS726T4TALE6L4":{"VKGNW40H":{"compatibility_interval":[{"compatibility":"support"}]},"default":{"compatibility_interval":[{"compatibility":"support"}]}},"SAT5210-3840G":{"SCEMH3.1":{"fw_buildnumber":1,"firm_bin":"SCEMH3.1.bin","compatibility_interval":[{"compatibility":"support"}]},"SCEMH3.2":{"fw_buildnumber":2,"firm_bin":"SCEMH3.2.bin","compatibility_interval":[{"compatibility":"support"}]},"default":{"compatibility_interval":[{"compatibility":"support"}]}},"SAT5210-1920G":{"SCEMH3.1":{"fw_buildnumber":1,"firm_bin":"SCEMH3.1.bin","compatibility_interval":[{"compatibility":"support"}]},"SCEMH3.2":{"fw_buildnumber":2,"firm_bin":"SCEMH3.2.bin","compatibility_interval":[{"compatibility":"support"}]},"default":{"compatibility_interval":[{"compatibility":"support"}]}},"SAT5210-480G":{"SCEMH3.1":{"fw_buildnumber":1,"firm_bin":"SCEMH3.1.bin","compatibility_interval":[{"compatibility":"support"}]},"SCEMH3.2":{"fw_buildnumber":2,"firm_bin":"SCEMH3.2.bin","compatibility_interval":[{"compatibility":"support"}]},"default":{"compatibility_interval":[{"compatibility":"support"}]}},"SAT5210-960G":{"SCEMH3.1":{"fw_buildnumber":1,"firm_bin":"SCEMH3.1.bin","compatibility_interval":[{"compatibility":"support"}]},"SCEMH3.2":{"fw_buildnumber":2,"firm_bin":"SCEMH3.2.bin","compatibility_interval":[{"compatibility":"support"}]},"default":{"compatibility_interval":[{"compatibility":"support"}]}},"HAT5300-4T":{"1401":{"fw_buildnumber":1,"firm_bin":"MG08_SATA_4T_1401.ftd","compatibility_interval":[{"compatibility":"support"}]},"1402":{"fw_buildnumber":2,"firm_bin":"MG08_SATA_4T_1402.ftd","compatibility_interval":[{"compatibility":"support"}]},"default":{"compatibility_interval":[{"compatibility":"support"}]}},"HAT5310-8T":{"1401":{"fw_buildnumber":1,"firm_bin":"MG08_SATA_8T_1401.ftd","compatibility_interval":[{"compatibility":"support"}]},"default":{"compatibility_interval":[{"compatibility":"support"}]}},"HAT5310-18T":{"1401":{"fw_buildnumber":1,"firm_bin":"MG09_SATA_18T_1401.ftd","compatibility_interval":[{"compatibility":"support"}]},"default":{"compatibility_interval":[{"compatibility":"support"}]}},"MZ7LM960HCHP-000V3 00Y":{"default":{"compatibility_interval":[{"compatibility":"support","not_yet_rolling_status":"support","fw_dsm_update_status_notify":false,"barebone_installable":true}]}}},"nas_model":"ds3622xs+"}

**Comment by 007revad** [comment]
To remove the "space and the 00Y" at the end of MZ7LM960HCHP-000V3 00Y in /var/lib/disk-compatibility/ds3622xs+_host_v7.db run the following command:

`sudo sed -i "s/ 00Y//" "/var/lib/disk-compatibility/ds3622xs+_host_v7.db"`

Then so you don't have to reboot run this:

`/usr/syno/sbin/synostgdisk --check-all-disks-compatibility`

I'm curious if the disk.log shows **MZ7LM960HCHP-000V3 00Y** or **MZ7LM960HCHP-000V3**. Can you report back what the following command returns:

`sudo grep "MZ7LM960HCHP" "/var/log/disk.log"`

**Comment by YerBabiE** [comment]
The change fixed the problem. :)

This is the dump from the log: 
sudo grep "MZ7LM960HCHP" "/var/log/disk.log"
2023-03-17T00:32:42-07:00 SynologyNAS hotplugd[12858]: hotplugd.c:1457 ==== SATA disk [sdk] Model: [MZ7LM960HCHP-000V3   00Y] ====
2023-03-17T00:32:42-07:00 SynologyNAS hotplugd[12858]: hotplugd.c:1457 ==== SATA disk [sdl] Model: [MZ7LM960HCHP-000V3   00Y] ====
2023-03-17T00:32:43-07:00 SynologyNAS hotplugd[12858]: hotplugd.c:1457 ==== SATA disk [sdj] Model: [MZ7LM960HCHP-000V3   00Y] ====
2023-03-18T18:21:31+10:00 STORAGE23 hotplugd[14384]: hotplugd.c:1457 ==== SATA disk [sdk] Model: [MZ7LM960HCHP-000V3   00Y] ====
2023-03-18T18:21:31+10:00 STORAGE23 hotplugd[14384]: hotplugd.c:1457 ==== SATA disk [sdl] Model: [MZ7LM960HCHP-000V3   00Y] ====
2023-03-18T18:21:31+10:00 STORAGE23 hotplugd[14384]: hotplugd.c:1457 ==== SATA disk [sdj] Model: [MZ7LM960HCHP-000V3   00Y] ====
2023-03-18T20:10:47+10:00 STORAGE23 hotplugd[14639]: hotplugd.c:1457 ==== SATA disk [sdk] Model: [MZ7LM960HCHP-000V3   00Y] ====
2023-03-18T20:10:47+10:00 STORAGE23 hotplugd[14639]: hotplugd.c:1457 ==== SATA disk [sdl] Model: [MZ7LM960HCHP-000V3   00Y] ====
2023-03-18T20:10:47+10:00 STORAGE23 hotplugd[14639]: hotplugd.c:1457 ==== SATA disk [sdj] Model: [MZ7LM960HCHP-000V3   00Y] ====
2023-03-19T13:27:41+10:00 STORAGE23 hotplugd[14656]: hotplugd.c:1457 ==== SATA disk [sdk] Model: [MZ7LM960HCHP-000V3   00Y] ====
2023-03-19T13:27:41+10:00 STORAGE23 hotplugd[14656]: hotplugd.c:1457 ==== SATA disk [sdl] Model: [MZ7LM960HCHP-000V3   00Y] ====
2023-03-19T13:27:41+10:00 STORAGE23 hotplugd[14656]: hotplugd.c:1457 ==== SATA disk [sdj] Model: [MZ7LM960HCHP-000V3   00Y] ====

**Comment by 007revad** [comment]
I'm glad that worked.

But also disappointed that the disk.log shows the model with the " 00Y". Actually it is good to know that the disk.log includes the extra 00Y so I can avoid using it to check drive model numbers.

I'll probably just modify the script to remove " 00Y" from any drive models starting with MZ.
