### ISSUE TITLE
No M.2 volumes with 7.2 u3

### ISSUE THREAD

**Issue by Ssuper2k** [007revad/Synology_HDD_db#141]
![image](https://github.com/007revad/Synology_HDD_db/assets/98287120/b878d935-6315-48d0-a022-00c92b98222d)

![image](https://github.com/007revad/Synology_HDD_db/assets/98287120/3c4170b3-82c7-40af-9d34-8e63e4102061)

M.2 drives are directly connected to the mobo slots (NO pcie adaptors)

Any idea how to get my M.2 volumes back with update 3?

I can help/try on testing any possible fix

Thanks!

**Comment by Ssuper2k** [comment]
![image](https://github.com/007revad/Synology_HDD_db/assets/98287120/ce5f7879-131a-458a-b870-054b94bea564)
![image](https://github.com/007revad/Synology_HDD_db/assets/98287120/d1ca7777-9525-426f-accf-7b0aa1e31804)
![image](https://github.com/007revad/Synology_HDD_db/assets/98287120/7986504c-28d5-417b-a850-a37ae0ff6881)

**Comment by 007revad** [comment]
Which PCIe card do you have?

7.2 update 3 has caused issues for people with M2 cards. Someone has kindly donated an M2 card but they haven't posted it yet. I'll do some testing with 7.2 update 3 once the card arrives.

In the meantime you can go back to 7.2 update 1 with https://github.com/007revad/Synology_DSM_reinstall but:

- A DSM install needs internet access to start the installation.
- But you need to kill the Internet access before DSM tries to update itself to update 3.

**Comment by 007revad** [comment]
Try running the script and rebooting 2 or 3 times.

**Comment by Ssuper2k** [comment]
I have managed to create a an storage and volume on the M.2 980pro (no adaptor, mrect M.2 slot, Z790 board)
(arpl-i18n-23.9.0.img and DSM_DS3622xs+_7.2-64570 (with Update 1).pat)

But the VMM performance is veeery poor on my 13700k

have tried many other broadwellnk DSM firmwares, but all of then are very laggy on VMM

my 'old' XPE with 5960x if much faster on VMM (works as it should)

So I'm guessing XPE/DSM is still Not ready for Alder Lake /Raptor Lake CPUs

What is the Latest intel CPU (Xeon/Core i7/9) on any real Synology?

**Comment by 007revad** [comment]
I'm not sure which Xeon CPUs are the newer ones, but Synology does have a list of what CPU is in every model NAS they've ever made: https://kb.synology.com/en-us/DSM/tutorial/What_kind_of_CPU_does_my_NAS_have 

Synology's hardware is always a few years behind what's currently available.

**Comment by anschluss-org** [comment]
I managed to create a new M2 volume on a new DS1821+ with 7.2u3 while this loop was running in a terminal window:

# while true; do /usr/local/bin/syno_hdd_db.sh -r ; done

Only running it once would not let me create the volume due to "unsupported drives".

**Comment by 007revad** [comment]
I notice you didn't use the -n option to prevent DSM downloading Synology's default drive database files.

I wish I'd made the -n option enabled by default.
