### ISSUE TITLE
Script not working with single drive

### ISSUE THREAD

**Issue by xazac** [007revad/Synology_HDD_db#146]
I installed a single WD_Black SN850X NVMe drive and I used the "**syno_create_m2_volume.sh**" script to get it work.

I have a Synology DS723+ running DSM 7.2-U3.

Now, after every boot, I got a "Missing Pool" error message even if I scheduled "**syno_hdd_db.sh**" to run as root on every reboot. 
It seems like the script doesn't work with just one single drive installed as the error message reports that "there are not enough drives in this storage pool":

![Screenshot 2023-09-20 210722](https://github.com/007revad/Synology_HDD_db/assets/10470552/33553b55-128f-424d-9bc6-0036eb14c697)

How can I fix this?
Thanks.

**Comment by 007revad** [comment]
What does `sudo -i cat /proc/mdadm` show?

You didn't need to use syno_create_m2_volume. It's only needed for older Synology models or older DSM versions or NVMe drives in a Synology PCIe adaptor card.

If you have a backup of what's on the NVMe drive I would do the following: 
1. Delete the storage pool.
2. Run syno_hdd_db again ( with the -n option).
3. If that wasn't enough to allow you to create the NVMe volume from Storage Manager then run [syno_enable_m2_volume](https://github.com/007revad/Synology_enable_M2_volume).

**Comment by xazac** [comment]
Hello @007revad, thank you for your reply!

> What does `sudo -i cat /proc/mdadm` show?

![Screenshot 2023-09-21 100845](https://github.com/007revad/Synology_HDD_db/assets/10470552/d0c60669-fb63-4942-8613-4b4f4bc76867)

> You didn't need to use syno_create_m2_volume. It's only needed for older Synology models or older DSM versions or NVMe drives in a Synology PCIe adaptor card.
> 
> If you have a backup of what's on the NVMe drive I would do the following:
> 
> 1. Delete the storage pool.
> 2. Run syno_hdd_db again ( with the -n option).

**I've done that, but it didn't recognize my NVMe:**

![Screenshot 2023-09-21 101137](https://github.com/007revad/Synology_HDD_db/assets/10470552/0ebd58cd-24be-4c14-b8a6-0c7f108f3722)

> 3. If that wasn't enough to allow you to create the NVMe volume from Storage Manager then run [syno_enable_m2_volume](https://github.com/007revad/Synology_enable_M2_volume).

**So I used "syno_enable_m2_volume.sh":**

![Screenshot 2023-09-21 102120](https://github.com/007revad/Synology_HDD_db/assets/10470552/73ef2a98-1d3b-4739-accc-31a157a8be39)

**After reboot I still can't see any drive available to create a storage pool:**

![Screenshot 2023-09-21 102643](https://github.com/007revad/Synology_HDD_db/assets/10470552/9925a3af-be56-4c1a-9c23-6ac5d17a8ed0)

![Screenshot 2023-09-21 102653](https://github.com/007revad/Synology_HDD_db/assets/10470552/91742e85-78a9-4c14-b942-1f3cd1eaf3fb)

You told me to don't use **"syno_create_m2_volume.sh"**, so now how can I get my NVMe to work?
Thanks

**Comment by 007revad** [comment]
This seems to be caused by DSM 7.2 Update 3 but I haven't figured out what it's doing differently yet.

Do you want install DSM 7.2 Update 1, and then run syno_create_m2_volume.sh again? You won't lose any data or settings.

You'd need this DSM_DS723+_64570.pat file from Synology:
https://global.synologydownload.com/download/DSM/release/7.2/64570-1/DSM_DS723+_64570.pat

And then use this script https://github.com/007revad/Synology_DSM_reinstall making sure you include steps 1, 6 and 8 to prevent DSM updating itself to Update 3.

**Comment by xazac** [comment]
> This seems to be caused by DSM 7.2 Update 3 but I haven't figured out what it's doing differently yet.
> 
> Do you want install DSM 7.2 Update 1, and then run syno_create_m2_volume.sh again? You won't lose any data or settings.
> 
> You'd need this DSM_DS723+_64570.pat file from Synology: https://global.synologydownload.com/download/DSM/release/7.2/64570-1/DSM_DS723+_64570.pat
> 
> And then use this script https://github.com/007revad/Synology_DSM_reinstall making sure you include steps 1, 6 and 8 to prevent DSM updating itself to Update 3.

I can't downgrade due to third-party software compatibility.
Anyway, I will wait for an update about your script.

Really thanks!

**Comment by xazac** [comment]
> This seems to be caused by DSM 7.2 Update 3 but I haven't figured out what it's doing differently yet.
> 
> Do you want install DSM 7.2 Update 1, **and then run syno_create_m2_volume.sh** again? You won't lose any data or settings.
> 
> You'd need this DSM_DS723+_64570.pat file from Synology: https://global.synologydownload.com/download/DSM/release/7.2/64570-1/DSM_DS723+_64570.pat
> 
> And then use this script https://github.com/007revad/Synology_DSM_reinstall making sure you include steps 1, 6 and 8 to prevent DSM updating itself to Update 3.

Hello, I tried to downgrade but even after .pat reinstallation, my NAS is still running DSM 7.2-64570 Update 3.
I tried twice, I followed your guide step by step, I even downloaded the firmware called "64570 (with Update 1) directly from Synology, but it still run Update 3.

Anyway, you initially told me to don't use "syno_create_m2_volume.sh" as I have to use "syno_enable_m2_volume.sh" instead; now you are telling me to run it: so which one do I have to use? Create or Enable?

PS: why did you write that scripts must be **run on boot** but in the guide you wrote they must be **run on shutdown**?
https://github.com/007revad/Synology_enable_M2_volume/blob/v1.0.10/how_to_schedule.md

Thanks

**Comment by 007revad** [comment]
Sorry, that was a typo. All you should need is syno_hdd_db.sh. If that on it's own doesn't allow you to create a NVMe volume from  storage manager then use syno_**enable**_m2-volume.sh. 

Originally all my scripts were to be run at start-up. The idea was they would after any DSM update.

But later, because syno_**enable**_m2-volume.sh requires a reboot after it is run I changed the recommendation to run it at shutdown. 

DSM 7.2 Update 1 would only have been able update itself to Update 3 if the Synology was able to access the Internet while it was updating. You must have clicked OK **and then clicked Update** before you disconnected your router from the Internet.

**Comment by xazac** [comment]
> Sorry, that was a typo. All you should need is syno_hdd_db.sh. If that on it's own doesn't allow you to create a NVMe volume from storage manager then use syno_**enable**_m2-volume.sh.
> 
> Originally all my scripts were to be run at start-up. The idea was they would after any DSM update.
> 
> But later, because syno_**enable**_m2-volume.sh requires a reboot after it is run I changed the recommendation to run it at shutdown.
> 
> DSM 7.2 Update 1 would only have been able update itself to Update 3 if the Synology was able to access the Internet while it was updating. You must have clicked OK **and then clicked Update** before you disconnected your router from the Internet.

Thank you for you reply.
Anyway, I was very careful to detach the Ethernet cable from NAS as soon as reboot started.

The problem is that the NAS yesterday updated to DSM 7.2.1 and downgrade is not possible anymore since Storage Manager, SAN Manager and File Station packages have been updated as well and they don’t work when I downgrade from 7.2.1 to whatever.

I just bought an original Synology NVME so I don’t have to bother about that anymore.

Really thanks!
