### ISSUE TITLE
Permission denied with sudo -i

### ISSUE THREAD

**Issue by 19Homer73** [007revad/Synology_HDD_db#153]
Hello,

I can't run the script via putty.
There ist a permission denied message, when I tried to run the .sh:

![grafik](https://github.com/007revad/Synology_HDD_db/assets/24566412/16994b38-b2e5-467d-b803-f8702d71aaa5)

Could someone please give me a hint to resolve this issue?

Thanks!

**Comment by 007revad** [comment]
What folder did put the syno_hdd_db.sh file in?

**Comment by 19Homer73** [comment]
It's in the screenshot: /volume1/scripts/

**Comment by 007revad** [comment]
But is the script actually in /volume1/scripts ?

What does `ls -l /volume1/scripts` return?

**Comment by 19Homer73** [comment]
![grafik](https://github.com/007revad/Synology_HDD_db/assets/24566412/d8009d81-7cd5-4968-a313-cc616d39fb3a)

**Comment by 19Homer73** [comment]
OK - found the problem...
Changed permission to 777 then it worked!

**Comment by 007revad** [comment]
You beat me to it :)

Run the following command to make the script executable:
`chmod 750 /volume1/scripts/syno_hdd_db.sh`

You should then be to run the script with:
`sudo -i /volume1/scripts/syno_hdd_db.sh -nr`
