### ISSUE TITLE
Error in running hdd_db script

### ISSUE THREAD

**Issue by tianli9** [007revad/Synology_HDD_db#154]
![image](https://github.com/007revad/Synology_HDD_db/assets/95733738/5ab3a005-4554-451e-830c-b2aac121deb5)

**Comment by 007revad** [comment]
Did you get the same error the first time you ran syno_hdd-db?

It looks like your HDDs were migrated from a different Synology model?

What does this command return:
`ls /sys/block | grep -E "(sata|sd)"`

Can you save a copy of ds920+_host.db
`cp /var/lib/disk-compatibility/ds920+_host.db /volume1/BACKUP`

Then go to your BACKUP shared folder, zip ds920+_host.db and attach the zip file to your reply here.

**Comment by tianli9** [comment]
Thanks for feedback.
I cant remember what happened on the very first time to run this script, it may works at that time, or not, at least i run it for times, it is not a one time success action. 
This is the result i run your command
![image](https://github.com/007revad/Synology_HDD_db/assets/95733738/28259f9e-8bc5-47ae-a60e-2945f672aaae)
and i saved the ds920+_host.db and here is the copy.
[ds920+_host.zip](https://github.com/007revad/Synology_HDD_db/files/13055023/ds920%2B_host.zip)
Thanks again for helping on this.

**Comment by 007revad** [comment]
Can you run the script again, and let the script update itself to the new version.

Or download the new version here:
https://github.com/007revad/Synology_HDD_db/releases/tag/v3.1.65

**Comment by tianli9** [comment]
It works！Thanks！
![image](https://github.com/007revad/Synology_HDD_db/assets/95733738/1f8d054d-fe08-4f05-af55-84cac7efc564)
So, i need to run this script after every DSM update right?

**Comment by 007revad** [comment]
> It works！

Excellent.

> So, i need to run this script after every DSM update right?

Yes. And after adding any different drives.

Or you can schedule the script to run when the Synology boots up. https://github.com/007revad/Synology_HDD_db/blob/main/how_to_schedule.md

**Comment by tianli9** [comment]
Awesome! Have a nice day!
