### ISSUE TITLE
DS1823xs+ with E10M20-T1 isn't recognised in GUI

### ISSUE THREAD

**Issue by AndrewTapp** [007revad/Synology_HDD_db#158]
Again, many thanks for all the hard work you do here, it's much appreciated and very useful.

I've been running DSM 7.2-64570-2 for ages with no issues, however this morning I upgraded to DSM 7.2.1-69057-1 and although the script appears to have run without issue and found the card, none of it's functionality appears to be present i.e. the two M2 SSD drives and/or the 10Gb network port.

Any help would be appreciated.

```
Task: Check HDD Database
Start time: Wed, 01 Nov 2023 08:59:38 GMT
Stop time: Wed, 01 Nov 2023 08:59:45 GMT
Current status: 0 (Normal)
Standard output/error:
Synology_HDD_db v3.1.65
DS1823xs+ DSM 7.2.1-69057-1 
Using options: --showedits --ram --autoupdate=2
Running from: /volume1/homes/AndrewTapp/Scripts/syno_hdd_db.sh

HDD/SSD models found: 2
WD181KRYZ-01AGBB0,01.01H01
WD221KRYZ-01BBAB0,01.01H01

M.2 drive models found: 1
KINGSTON SFYRD4000G,EIFK31.6

M.2 PCIe card models found: 1
E10M20-T1

Expansion Unit models found: 1
DX517

 [0;33mWD181KRYZ-01AGBB0 [0m already exists in  [0;36mds1823xs+_host_v7.db [0m
 [0;33mWD181KRYZ-01AGBB0 [0m already exists in  [0;36mds1821+_host_v7.db [0m
 [0;33mWD181KRYZ-01AGBB0 [0m already exists in  [0;36mds1823xs+_host_v7.db.new [0m
 [0;33mWD181KRYZ-01AGBB0 [0m already exists in  [0;36mds1821+_host_v7.db.new [0m
 [0;33 mWD181KRYZ-01AGBB0 [0m already exists in  [0;36mdx517_v7.db [0m
 [0;33mWD221KRYZ-01BBAB0 [0m already exists in  [0;36mds1823xs+_host_v7.db [0m
 [0;33mWD221KRYZ-01BBAB0 [0m already exists in  [0;36mds1821+_host_v7.db [0m
 [0;33mWD221KRYZ-01BBAB0 [0m already exists in  [0;36mds1823xs+_host_v7.db.new [0m
 [0;33mWD221KRYZ-01BBAB0 [0m already exists in  [0;36mds1821+_host_v7.db.new [0m
 [0;33mWD221KRYZ-01BBAB0 [0m already exists in  [0;36mdx517_v7.db [0m
 [0;33mKINGSTON SFYRD4000G [0m already exists in  [0;36mds1823xs+_host_v7.db [0m
 [0;33mKINGSTON SFYRD4000G [0m already exists in  [0;36mds1821+_host_v7.db [0m
 [0;33mKINGSTON SFYRD4000G [0m already exists in  [0;36mds1823xs+_host_v7.db.new [0m
 [0;33mKINGSTON SFYRD4000G [0m already exists in  [0;36mds1821+_host_v7.db.new [0m
 [0;33mKINGSTON SFYRD4000G [0m already exists in  [0;36mds1821+_e10m20-t1_v7.db [0m
 [0;33mKINGSTON SFYRD4000G [0m already exists in  [0;36mds1823xs+_e10m20-t1_v7.db [0m

 [0;33 mE10M20-T1 NIC [0m already enabled for  [0;36mDS1823xs+ [0m
 [0;33mE10M20-T1 NVMe [0m already enabled for  [0;36mDS1823xs+ [0m
 [0;33mE10M20-T1 SATA [0m already enabled for  [0;36mDS1823xs+ [0m
 [0;33mE10M20-T1 [0m already enabled in  [0;36mmodel.dtb [0m

Support disk compatibility already enabled.

Support memory compatibility already disabled.

Max memory already set to 64 GB.

M.2 volume support already enabled.

Drive db auto updates already enabled.

"WD181KRYZ-01AGBB0": {
"01.01H01": {
"compatibility_interval": [
{
"compatibility": "support",
"not_yet_rolling_status": "support",
"fw_dsm_update_status_notify": false,
"barebone_installable": true
}
]
},
"default": {

"WD221KRYZ-01BBAB0": {
"01.01H01": {
"compatibility_interval": [
{
"compatib ility": "support",
"not_yet_rolling_status": "support",
"fw_dsm_update_status_notify": false,
"barebone_installable": true
}
]
},
"default": {

"KINGSTON SFYRD4000G": {
"EIFK31.6": {
"compatibility_interval": [
{
"compatibility": "support",
"not_yet_rolling_status": "support",
"fw_dsm_update_status_notify": false,
"barebone_installable": true
}
]
},
"default": {

DSM successfully checked disk compatibility.

You may need to  [0;36mreboot the Synology [0m to see the changes.
```

**Comment by 007revad** [comment]
What does the following command return:
`cat /run/adapter_cards.conf`

Can you run this script and reply with what it outputs:
https://github.com/007revad/Synology_HDD_db/blob/test/m2_card_check.sh

**Comment by AndrewTapp** [comment]
These return as follow.

root@DS1823xs: cat /run/adapter_cards.conf
M2D20_sup_nvme=no
E10M20-T1_sup_sata=no
E10M20-T1_sup_nic=no
M2D17_sup_sata=no
E10M20-T1_sup_nvme=no
M2D18_sup_sata=no
M2D17_sup_nic=no
M2D18_sup_nic=no
M2D20_sup_sata=no
M2D17_sup_nvme=no
M2D18_sup_nvme=no
FX2422N_sup_nic=no
FX2422N_sup_nvme=no
FX2422N_sup_sata=no
M2D20_sup_nic=no
root@DS1823xs:


root@DS1823xs:/volume1/homes/AndrewTapp/Scripts# ./m2_card_check.sh
DSM 7.2.1-69057 Update 1
2023-11-01 10:54:11

 Checking support_m2_pool setting
/etc.defaults/synoinfo.conf: yes
/etc/synoinfo.conf:          yes

 Checking supportnvme setting
/etc.defaults/synoinfo.conf: yes
/etc/synoinfo.conf:          yes

 Checking permissions and owner of libsynonvme.so.1
 Which should be -rw-r--r-- 1 root root
-rw-r--r-- 1 root root 58314 Jun 21 11:28 /usr/lib/libsynonvme.so.1

 Checking permissions and owner of synonvme
 Which should be -rwxr-xr-x 1 root root
-rwxr-xr-x 1 root root 17273 Jun 21 11:28 /usr/syno/bin/synonvme

 Checking permissions and owner of model.dtb files
 Which should be -rw-r--r-- 1 root root
-rw-r--r-- 1 root root 5482 Sep 23 16:12 /etc.defaults/model.dtb
-rw-r--r-- 1 root root 3515 Oct 18  2021 /etc/model.dtb
-rw-r--r-- 1 root root 5482 Nov  1 08:57 /run/model.dtb

 Checking power_limit="100,100,100,100" is in model.dtb files
Missing in /etc.defaults/model.dtb
Missing in /etc/model.dtb
Missing in /run/model.dtb

 Checking E10M20-T1 is in model.dtb files
Missing in /etc/model.dtb

 Checking M2D20 is in model.dtb files
Missing in /etc/model.dtb

 Checking M2D18 is in model.dtb files
Missing in /etc.defaults/model.dtb
Missing in /etc/model.dtb
Missing in /run/model.dtb

 Checking permissions and owner of adapter_cards.conf files
 Which should be -rw-r--r-- 1 root root
-rw-r--r-- 1 root root 3418 Nov  1 08:57 /usr/syno/etc.defaults/adapter_cards.conf
-rw-r--r-- 1 root root 2652 Sep 22  2021 /usr/syno/etc/adapter_cards.conf
-rw-r--r-- 1 root root 283 Nov  1 08:57 /run/adapter_cards.conf

 Checking /usr/syno/etc.defaults/adapter_cards.conf
E10M20-T1_sup_nic NOT set to yes
E10M20-T1_sup_nvme NOT set to yes
E10M20-T1_sup_sata NOT set to yes
M2D20_sup_nvme NOT set to yes
M2D18_sup_nvme NOT set to yes
M2D18_sup_sata NOT set to yes

 Checking /usr/syno/etc/adapter_cards.conf
E10M20-T1_sup_nic NOT set to yes
E10M20-T1_sup_nvme NOT set to yes
E10M20-T1_sup_sata NOT set to yes
M2D20_sup_nvme NOT set to yes
M2D18_sup_nvme NOT set to yes
M2D18_sup_sata NOT set to yes

 Checking /run/adapter_cards.conf
E10M20-T1_sup_nic NOT set to yes
E10M20-T1_sup_nvme NOT set to yes
E10M20-T1_sup_sata NOT set to yes
M2D20_sup_nvme NOT set to yes
M2D18_sup_nvme NOT set to yes
M2D18_sup_sata NOT set to yes

 Checking synodisk --enum -t cache
************ Disk Info ***************
>> Disk id: 1
>> Disk path: /dev/nvme2n1
>> Disk model: KINGSTON SFYRD4000G
>> Total capacity: 3726.02 GB
>> Tempeture: 19 C
************ Disk Info ***************
>> Disk id: 2
>> Disk path: /dev/nvme3n1
>> Disk model: KINGSTON SFYRD4000G
>> Total capacity: 3726.02 GB
>> Tempeture: 20 C

 Checking syno_slot_mapping
----------------------------------------
System Disk
Internal Disk
01: /dev/sata1
02: /dev/sata2
03: /dev/sata3
04: /dev/sata4
05: /dev/sata10
06: /dev/sata11
07: /dev/sata12
08: /dev/sata13

Esata port count: 2
Eunit port 1 - DX517
01: /dev/sata5
02: /dev/sata6
03: /dev/sata7
04: /dev/sata8
05: /dev/sata9

Esata port 2
01:

USB Device
01:
02:
03:

Internal SSD Cache:
01: /dev/nvme2n1
02: /dev/nvme3n1

----------------------------------------

 Checking udevadm nvme paths
nvme0: /devices/pci0000:00/0000:00:01.1/0000:01:00.0/0000:02:04.0/0000:06:00.0/nvme/nvme0
nvme1: /devices/pci0000:00/0000:00:01.1/0000:01:00.0/0000:02:08.0/0000:07:00.0/nvme/nvme1
nvme2: /devices/pci0000:00/0000:00:01.3/0000:0f:00.0/nvme/nvme2
nvme3: /devices/pci0000:00/0000:00:01.4/0000:10:00.0/nvme/nvme3

 Checking devicetree Power_limit
14.85,9.075

 Checking if nvme drives in PCIe card are detected with synonvme
nvme0: Not M.2 adapter card
nvme1: Not M.2 adapter card
nvme2: Not M.2 adapter card
nvme3: Not M.2 adapter card

 Checking if nvme drives in PCIe card are detected with synodisk
nvme0: E10M20-T1
nvme1: E10M20-T1
nvme2: Not M.2 adapter card
nvme3: Not M.2 adapter card

 Checking PCIe slot path(s)
[pci]
pci1="0000:00:01.1"

 Checking nvme drives in /run/synostorage/disks
nvme2n1
nvme3n1

 Checking nvme block devices in /sys/block
nvme0n1
nvme1n1
nvme2n1
nvme3n1

 Checking synostgd-disk log
----------------------------------------
Current date/time:   2023-11-01 10:54:11
date: invalid date ‘@’
Last boot date/time:
date: invalid date ‘@’
----------------------------------------
2023-11-01T08:53:55+00:00 DS1823xs synostgd-disk[12931]: smartctl/smartctl_ata_smart_info_get.c:539 Failed to get smart info on /dev/sata9, 0xA00
2023-11-01T08:53:55+00:00 DS1823xs synostgd-disk[12931]: smartctl/smartctl_ata_smart_info_update.c:49 Failed to update smart info on /dev/sata9, 0xA00
2023-11-01T08:53:55+00:00 DS1823xs synostgd-disk[12931]: smartctl/smartctl_total_status_cache_update.c:46 Failed to update smart info on device /dev/sata9, 0xA00
2023-11-01T08:53:55+00:00 DS1823xs synostgd-disk[12931]: disk_monitor.c:57 Failed to update smart cache on /dev/sata9
2023-11-01T08:53:55+00:00 DS1823xs synostgd-disk[12913]: smartctl/smartctl_ata_smart_info_get.c:539 Failed to get smart info on /dev/sata6, 0xA00
2023-11-01T08:53:55+00:00 DS1823xs synostgd-disk[12913]: smartctl/smartctl_ata_smart_info_update.c:49 Failed to update smart info on /dev/sata6, 0xA00
2023-11-01T08:53:55+00:00 DS1823xs synostgd-disk[12913]: smartctl/smartctl_total_status_cache_update.c:46 Failed to update smart info on device /dev/sata6, 0xA00
2023-11-01T08:53:55+00:00 DS1823xs synostgd-disk[12913]: disk_monitor.c:57 Failed to update smart cache on /dev/sata6
----------------------------------------
root@DS1823xs:/volume1/homes/AndrewTapp/Scripts#

**Comment by AndrewTapp** [comment]
Just for information, how it looks in the GUI.

![image](https://github.com/007revad/Synology_HDD_db/assets/83402277/f40cc1fc-c877-49dc-98da-a3c0e7ac1ea3)

**Comment by 007revad** [comment]
Try running these 4 commands then rebooting:
```
sudo set_section_key_value /usr/syno/etc.defaults/adapter_cards.conf E10M20-T1_sup_nic DS1823xs+ yes
sudo set_section_key_value /usr/syno/etc.defaults/adapter_cards.conf E10M20-T1_sup_nvme DS1823xs+ yes

sudo set_section_key_value /usr/syno/etc/adapter_cards.conf E10M20-T1_sup_nic DS1823xs+ yes
sudo set_section_key_value /usr/syno/etc/adapter_cards.conf E10M20-T1_sup_nvme DS1823xs+ yes
```

**Comment by AndrewTapp** [comment]
That has worked, after rebooting the NVME cache and storage pool, plus network adapter are showing as expected.  Many thanks.

On a side note, I see on the logs from running syno_hdd_db.sh that there are a number of references to DS1821+ config files, left around when I migrated from that DiskStation to my current DS1823xs+  Do you know if these now required and should they be removed?

![image](https://github.com/007revad/Synology_HDD_db/assets/83402277/dce987f8-4876-4b8e-9c6a-8623ee68c36a)

![image](https://github.com/007revad/Synology_HDD_db/assets/83402277/a04ba8e4-2265-4b1e-887b-d6d8b964820d)

**Comment by 007revad** [comment]
> That has worked

Excellent.

To delete the old ds1821+ db files run this command:
`cd /var/lib/disk-compatibility && for db in ./ds1821+*; do rm -i $db; done`

You will need to enter **y** to delete each file. This just gives you the chance to confirm it is going to delete the correct file.

**Comment by AndrewTapp** [comment]
Once again many thanks for your help, take care.

**Comment by 007revad** [comment]
@jyubonk 

I won't use a read/write cache (they are too dangerous). I've heard of many people losing their data after a DSM update.

Just install 32 or 64GB of memory in DS1823xs+ instead. Memory is faster than a NVMe write cache and DSM only caches small files less than 1MB.
