### ISSUE TITLE
error Crucial Unrecognised firmware version

### ISSUE THREAD

**Issue by April-ha** [007revad/Synology_HDD_db#162]
Hello,
I have just installed 2 new Crucial drives in my DS720+.
I have run the "enabled" and "db" scripts several times but the disks always remain with "Unrecognised firmware version".
I also tried the db script with -f and rebooted the NAS.
They seem to work like that, is there a problem using them like that?
https://ibb.co/0YP6Swc
https://ibb.co/RHPqTKJ

**Comment by 007revad** [comment]
For a DS720+ running DSM 7.2 or later you don't need syno_m2_enable.

1. Disable any schedule you have setup for syno_m2_enable.
2. Run syno_m2_enable with the --restore option.
3. Reboot.
4. Run syno_hdd-db with the -n option.

**Comment by April-ha** [comment]
Thank you! You're the best!
I was beginning to despair at not finding a solution.
Your answer works very well, thank you again.
