### ISSUE TITLE
Unknow database type ds3622xs+_host_v7.db

### ISSUE THREAD

**Issue by 7ussana** [007revad/Synology_HDD_db#175]
I have the following error "Unknown database type ds3622xs+_host_v7.db"
After the command syno_hdd_db.sh -fr

Do you have any ideas?

**Comment by 007revad** [comment]
Can you save a copy of your ds3622xs+_host_v7.db file, zip it and then reply with the zip file attached (just drag and drop the zip file onto the reply before clicking on the Comment button).

To copy the ds3622xs+_host_v7.db file to your home directory:

`sudo -i cp /var/lib/disk-compatibility/ds3622xs+_host_v7.db $HOME`

**Comment by 007revad** [comment]
@7ussana not responding.

**Comment by mrmuiz** [comment]
Same error here ; ERROR Unknown database type ds213j_host_v7.db.new!
[ds213j_host_v7.zip](https://github.com/user-attachments/files/16401308/ds213j_host_v7.zip)
[ds213j_host_v7.db.zip](https://github.com/user-attachments/files/16401311/ds213j_host_v7.db.zip)

**Comment by 007revad** [comment]
@mrmuiz 

The script did correctly add your WD10EZRX-00A8LB0 and HD204UI to ds213j_host_v7.db

Your ds213j_host_v7.db.new file is 0 bytes (empty). So I'm not surprized the script was unable to determine the version.

Try deleting the ds213j_host_v7.db.new file. I'll update the script to deal with empty db and db.new files so other people don't get the same error.

**Comment by 007revad** [comment]
@mrmuiz 

I've released a new version that ignores empty .db.new files so it won't show an error.
https://github.com/007revad/Synology_HDD_db/releases/tag/v3.5.97
