### ISSUE TITLE
Unable to use ssd as storage pool

### ISSUE THREAD

**Issue by snakealanis** [007revad/Synology_HDD_db#189]
Hi,

I am a new user of a 1823xs+

I ran the script (3.3.72), it seems to work, all my HDD & SSD's are green now 

![storage](https://github.com/007revad/Synology_HDD_db/assets/154628480/fddfc2d4-e64b-4dd5-a365-8be6008043b0)

Despite this, i can't use my ssd's as storage pool (WD SN850X 4 TB)

![error](https://github.com/007revad/Synology_HDD_db/assets/154628480/286be011-5965-4c58-a64c-aa3604a23169)

I am able to use them as cache, so the "normal synology behaviour"

Am i doing something wrong ?

**Comment by 007revad** [comment]
You should able to use the M.2 SSDs as a cache or a volume.

What version of DSM is on the DS1823xs+?

Have you rebooted after running the script?

**Comment by snakealanis** [comment]
Hi,

I have version 7.2.1 69057
Yes i restarted several times. Part of the script works as all my drives are green now, but it still refuses to create a pool with my ssd's

**Comment by WanpengQian** [comment]
The DSM UI has a button to manually update compatible database. you can press that button, without a reboot, it should works.

My DS1821+ also encounter same situation last week. after execute the script, reboot, it cannot add as described neither.

I have a theory that DSM cache the db somewhere, directly change db file will not clear that cache.

**Comment by snakealanis** [comment]
there is indeed this db update button

if i click "update now" it says the db is already up to date
i tried to manually update it with the synology db available on their site, it updates, but still doesn't work. I rebooted, and still no luck

**Comment by WanpengQian** [comment]
sorry for unclear information

the procedure:
execute this script
reboot
press ui update button
and it should works.

the script already set the db update url to localhost, so the ui update button will not fetch official db files, just to let DSM reread the modify db files.

hope it explains.

**Comment by snakealanis** [comment]
Hi, thanks for the help
I tried as you said
i re run the script, rebooted
immediately tried to push the update button, but now i get this message
![DBupdateerror](https://github.com/007revad/Synology_HDD_db/assets/154628480/3a9d5645-f5dd-438e-9bbb-e1038f9fc12e)

and i still cannot create the pool :o(

**Comment by 007revad** [comment]
The script makes DSM check the disk compatibility at the end of the script with:
`sudo -i synostgdisk --check-all-disks-compatibility`

Manual db updates only work if there is a newer db version available AND the update drive db URL is not set.  

To restore the drive db URL run the script without the -n option.

In DMS 7 each .db file has a .version file. A few also have a .release file. For a NAS without an expansion unit or M.2 PCIe card we're only interested in the host files.

If you run the following commands you'll see the version number and release date:
```
cat /var/lib/disk-compatibility/ds1821+_host_v7.version && echo
cat /var/lib/disk-compatibility/ds1821+_host_v7.release && echo
```

On my DS1821+ with DSM 7.2.1-69057 Update 3 they return:
```
8043
20230915
```

I assume they would both need to be changed to smaller numbers before a manual drive database update would work.
```
sudo -i
echo -n 8000 > /var/lib/disk-compatibility/ds1821+_host_v7.version
echo -n 20230101 > /var/lib/disk-compatibility/ds1821+_host_v7.release
```

**Comment by 007revad** [comment]
What options did you run the script with?

I always use the -n option. This prevents DSM updating the drive databases (which is what you want).

You can run the script with the --restore option to undo all the changes it made... then reboot.

**Comment by 007revad** [comment]
> I have a theory that DSM caches the database somewhere, and directly changing the database file will not update that cache.

I experienced something similar yesterday when testing my [syno_enabled_dedupe](https://github.com/007revad/Synology_enable_Deduplication) script. After running it with the --restore option and rebooting the Data Deduplication was still available for my HDD volumes.

**Comment by snakealanis** [comment]
well you guessed, i f... up with the parameters, i ran with -nr and that's what was wrong
i used the --restore option, rebooted
re ran the script with -r parameters
and without even rebooting it worked
I then rebooted to check and everything is working now

thanks a lot for you help

**Comment by 007revad** [comment]
It sounds like the xs models check if the drive db URL has been changed.
