### ISSUE TITLE
add rx1214 and rx1214rp to script

### ISSUE THREAD

**Issue by cyonixx** [007revad/Synology_HDD_db#197]
I use your script in a mixed system with rx1217 and rx1214. 
please add the rx1214 and rx1214rp in your script

thank you

**Comment by 007revad** [comment]
The script should already find the rx1214 and rx1214rp.

What does the following commands return:
```
sudo -i
syno_disk_data_collector record
file=$(ls /var/log/diskprediction | tail -n1)
grep -Eowi "([FRD]XD?[0-9]{3,4})(rp|ii|sas){0,2}" "/var/log/diskprediction/$file" | uniq
```

**Comment by 007revad** [comment]
@cyonixx not responding

**Comment by 007revad** [comment]
If it's still not working can you reply with the output from the script.
