### ISSUE TITLE
error running script

### ISSUE THREAD

**Issue by hyllm** [007revad/Synology_HDD_db#198]
getting this.. :( running with --nr parameter

Model DS1823xs+, DSM 7.2.1 Update 3

`/volume1/Scripts/syno_hdd_db.sh: command substitution: line 2: syntax error near unexpected token `('
/volume1/Scripts/syno_hdd_db.sh: command substitution: line 2: `find $dbpath -maxdepth 1 \\( -name \"*.db.new.bak\" -o -name \"*.db.bak\" \\)))","    # Sort array","    IFS=$'\\n'","    dbbakfiles=($(sort <<<\"${dbbaklist[*]}\"))","    unset IFS","","    echo \"\"","    if [[ ${#dbbakfiles[@]} -gt \"0\" ]] || [[ -f ${synoinfo}.bak ]] ||\\","        [[ -f ${dtb_file}.bak ]] || [[ -f ${adapter_cards}.bak ]] ; then","","        # Restore synoinfo.conf from backup","        if [[ -f ${synoinfo}.bak ]]; then","            keyvalues=(\"support_disk_compatibility\" \"support_memory_compatibility\")","            keyvalues+=(\"mem_max_mb\" \"supportnvme\" \"support_m2_pool\" \"support_wdda\")","            for v in \"${!keyvalues[@]}\"; do","                defaultval=\"$(get_key_value ${synoinfo}.bak \"${keyvalues[v]}\")\"","                currentval=\"$(get_key_value ${synoinfo} \"${keyvalues[v]}\")\"","                if [[ $currentval != \"$defaultval\" ]]; then","                    if synosetkeyvalue \"$synoinfo\" \"${keyvalues[v]}\" \"$defaultval\";","
`

**Comment by 007revad** [comment]
Did you download the .zip file from here: https://github.com/007revad/Synology_HDD_db/releases/tag/v3.3.73 and save it to a shared folder on the Synology?

Then unzip the downloaded zip file and run the script from that folder?

**Comment by hyllm** [comment]
such a stupid looser i am. :D uploaded only script. 🤦 now everything works. 💯

**Comment by 007revad** [comment]
Your not the first person to do that... which is why I knew the answer.
