### ISSUE TITLE
Error: Cannot find hostdb file - DS1817+ running DSM6

### ISSUE THREAD

**Issue by sthulin** [007revad/Synology_HDD_db#2]
I have a DS1817+ running DSM6, after listing my disks i get the following error:

ERROR: /var/lib/disk-compatibility/ds1817+-j_host.db not found!

when i run "cat /proc/sys/kernel/syno_hw_version" i get back "ds1817+-j" so perhaps the last 2 characters need to be trimmed off in your script?

**Comment by 007revad** [comment]
Did you migrate the HDDs from a J model to the 1817+ ?

Do the following also include -j after ds1817+ ?

`get_key_value /etc/synoinfo.conf unique`
`get_key_value /etc.defaults/synoinfo.conf unique`

**Comment by sthulin** [comment]
> Did you migrate the HDDs from a J model to the 1817+ ?
> 
> Do the following also include -j after ds1817+ ?
> 
> `get_key_value /etc/synoinfo.conf unique` `get_key_value /etc.defaults/synoinfo.conf unique`

No i bought this new and put new drives in it.  Output for both of those commands are: "synology_avoton_1817+"

**Comment by 007revad** [comment]
What about: `cat /proc/cmdline`

**Comment by sthulin** [comment]
that also says "syno_hw_version=DS1817+" along with a bunch of other stuff

**Comment by 007revad** [comment]
Very strange. I'll need to dig deeper into where `cat /proc/cmdline` and `cat /proc/sys/kernel/syno_hw_version` get the model number from.

In the meantime I'll add a check for -j at the end of the model number and remove it.

**Comment by 007revad** [comment]
I've just updated the script with a change to remove "'-j" from the model.

**Comment by sthulin** [comment]
that worked and the script ran.  It added my HDDs.
