### ISSUE TITLE
HD6500扩展柜无法屏蔽硬盘验证

### ISSUE THREAD

**Issue by 1314Kissy** [007revad/Synology_HDD_db#206]
rx6022sas能否用此脚本来屏蔽硬盘兼容性的问题吗  显示未验证。

**Comment by 007revad** [comment]
Yes. It works for SAS drives in expansion units.

是的。它适用于扩展单元中的 SAS 驱动器。

**Comment by 1314Kissy** [comment]
![微信图片_20240109153754](https://github.com/007revad/Synology_HDD_db/assets/156056548/82ad5d69-e0bf-4d9b-be6c-96aaa61572ab)
When running the command, it will get stuck and not continue to run. Could you please help me check what the problem is

**Comment by 1314Kissy** [comment]
We can pay the fee and hope you can resolve it promptly

**Comment by 007revad** [comment]
@1314Kissy 

Sorry, I thought this had been resolved a week ago.

1. Try the latest version of the script: https://github.com/007revad/Synology_HDD_db/releases/tag/v3.4.80 
2. Try moving the script to a folder that does not have a space in the name or path.
3. And run it with -n option. You should not need the -f option.

**Comment by 007revad** [comment]
@1314Kissy not responding
