### ISSUE TITLE
Update of script fails with code errors

### ISSUE THREAD

**Issue by herbingk** [007revad/Synology_HDD_db#208]
Update of script fails with code errors. Seems like the chmod für CHANGES.txt wasn't updated to the new name and some trouble with closing fi

```
chmod: cannot access '/volume1/admin/Synology_HDD_db/CHANGES.txt': No such file or directory
ERROR Failed to set permissions on:
/volume1/admin/Synology_HDD_db/CHANGES.txt
ERROR Failed to cd to /tmp!
/volume1/admin/Synology_HDD_db/syno_hdd_db.sh: line 466: syntax error near unexpected token `fi'
/volume1/admin/Synology_HDD_db/syno_hdd_db.sh: line 466: `            fi'

```

**Comment by 007revad** [comment]
I know what caused the chmod error.

It obviously changed directory to temp okay or it would not have got to the chmod error. So I'm not sure why it ended up at line 465 and 466.

**Comment by 007revad** [comment]
Do you want to run it again, and let it update itself to v3.4.79 if see if those errors are gone.

If you still get the `syntax error near unexpected token 'fi'` error can you:
1. Edit the version number in syno_hdd_db.sh to make a lower number.
2. Run it with the --debug option.
3. Report back with the output.

**Comment by herbingk** [comment]
3.4.78 brings the same error when updating to 43.4.79.
3.4.79 seems to have fixed the problem. When editing the version no back to 3.4.78 running the update again, it does without problems.
