### ISSUE TITLE
Doesn't work with Synology Plus HDD

### ISSUE THREAD

**Issue by afocke** [007revad/Synology_HDD_db#224]
Accidentally bought the 5.400rpm version of Syno's Plus HDD which is not supported on DS1823xs+ (!?!).
The scripts works with WD red, but does not with Synology HAT3300-8T. Storage manager shows "Healthy" for WD Red, but "Unverified" for the Synology disks.

Does Synology block them in a different way?
Any ideas?

Script output:
``` Task: hdd_comp_update
Start time: Mon, 22 Jan 2024 07:59:33 GMT
Stop time: Mon, 22 Jan 2024 07:59:55 GMT
Current status: 0 (Normal)
Standard output/error:
Synology_HDD_db v3.4.80
DS1823xs+ DSM 7.2.1-69057-3
StorageManager 1.0.0-0017

Using options: -nr --autoupdate=3
Running from: /volume1/tech/synology/scripts/syno_comp/syno_hdd_db.sh

[0;36mThere is a newer version of this script available. [0m
Current version: v3.4.80
Latest version: v3.4.81
Skipping as v3.4.81 is less than 3 days old.

HDD/SSD models found: 2
HAT3300-8T,PL01
WD100EFAX-68LHPN0,83.H0A83

No M.2 drives found

No M.2 PCIe cards found

No Expansion Units found

[0;33mHAT3300-8T [0m already exists in [0;36mds1823xs+_host_v7.db [0m
Added [0;33mWD100EFAX-68LHPN0 [0m to [0;36mds1823xs+_host_v7.db [0m

Support disk compatibility already enabled.

Support memory compatibility already disabled.

Max memory is set to 32 GB.

Drive db auto updates already disabled.

DSM successfully checked disk compatibility.

You may need to [0;36mreboot the Synology [0m to see the changes.
```

**Comment by 007revad** [comment]
If you schedule the script with the `-e` or `--email` it will prevent those `[0;36m`, `[0;33m` and `[0m` from appearing in the task scheduler emails and task scheduler's "Action > View result".

I just had a look in the DS1823xs+ drive database file and even though it only contains Synology drives there are different compatibility values for different drives:
1. support
2. unverified
3. not_support

I've never noticed the "unverified" before. All of the HAT3300, SAT5210 and SNV3410 drives are "unverified" for the DS1823xs+.

**Try the following commands via SSH:**
```
sudo -i
sed -i 's/unverified/support/g' /var/lib/disk-compatibility/ds1823xs+_host_v7.db
/usr/syno/sbin/synostgdisk --check-all-disks-compatibility
```

**Or as a scheduled task run as root:**
```
sed -i 's/unverified/support/g' /var/lib/disk-compatibility/ds1823xs+_host_v7.db
/usr/syno/sbin/synostgdisk --check-all-disks-compatibility
```

You should not need to reboot. But if you have storage manager open you'll need to refresh the browser tab.

Let me know if that works and I'll add it to the script.

**Comment by afocke** [comment]
It worked! Will update the script once you found the time to add this to it.
You are great, thank you!

**Comment by 007revad** [comment]
Updated script here https://github.com/007revad/Synology_HDD_db/releases/tag/v3.4.82
