### ISSUE TITLE
command provided on readme does not work

### ISSUE THREAD

**Issue by leonpano2006** [007revad/Synology_HDD_db#227]
<pre>DS:<font color="#26A269">DiskStation</font><font color="#D0CFCC"><b>[</b></font><font color="#26A269"><b>~/Synology_HDD_db</b></font><font color="#D0CFCC"><b>]</b></font><font color="#A2734C"><b>$ </b></font>sudo -i ./syno_hdd_db.sh -nr
Loading module &apos;filesystem&apos; ...
Loading module &apos;kernel&apos; ...
Loading module &apos;message&apos; ...
Loading module &apos;mount&apos; ...
Loading module &apos;platform&apos; ...
Loading module &apos;utils&apos; ...
Loading module &apos;volume&apos; ...
-ash: ./syno_hdd_db.sh: No such file or directory</pre>

so i use this insisted
<pre>DS:<font color="#26A269">DiskStation</font><font color="#D0CFCC"><b>[</b></font><font color="#26A269"><b>~/Synology_HDD_db</b></font><font color="#D0CFCC"><b>]</b></font><font color="#A2734C"><b>$ </b></font>sudo su
DS:<font color="#26A269">DiskStation</font><font color="#D0CFCC"><b>[</b></font><font color="#26A269"><b>/volume1/homes/leonpano/Synology_HDD_db</b></font><font color="#D0CFCC"><b>]</b></font><font color="#A2734C"><b># </b></font>./syno_hdd_db.sh -nr
Synology_HDD_db v3.4.82
DS2419+ DSM 7.2.1-69057-3 
StorageManager 1.0.0-0017

Using options: -nr
Running from: /volume1/homes/leonpano/Synology_HDD_db/syno_hdd_db.sh
</pre>
... output after is not needed for this issue

**Comment by 007revad** [comment]
Thanks.

If the script is in your home folder and you try to run the script with `sudo -i ./syno_hdd_db.sh` you'll get the "No such file or directory" error. This is because sudo -i uses root's profile, and the script is not located in root's home.

I've changed the readme to show `sudo -s` which doesn't change to root's profile.
