### ISSUE TITLE
ERROR No drives found!

### ISSUE THREAD

**Issue by stevenpDU** [007revad/Synology_HDD_db#23]
When running the script, this is my output:

Synology_HDD_db v1.2.17
RS2421rp+ DSM 7.1.1

ERROR No drives found!

I have 11 disks in RAID 6 (Synology £HAT5300-16T) and 1 hot spare (Seagate ST16000NE000-2RW103) in my RS2421rp+

**Comment by 007revad** [comment]
I'm not sure what happened there. I suspect maybe your drives firmware version may be in `/sys/block/<drive>/device/firmware_rev` instead of `/sys/block/<drive>/device/rev`

Can you try the following commands report back what each of them return:

`cat /sys/block/sata1/device/model`

`cat /sys/block/sata1/device/rev`

`cat /sys/block/sata1/device/firmware_rev`

If you don't get anything from 2 or more of those commands let me know what this command returns:

`ls -1 /sys/block/sata/device`

If it returns nothing then try:

`ls -1 /sys/block/sda/device`

**Comment by stevenpDU** [comment]
Hello, my outputs are: 

ash-4.4# cat /sys/block/sata1/device/model
HAT5300-16T
ash-4.4# cat /sys/block/sata1/device/rev
1402
ash-4.4# cat /sys/block/sata1/device/firmware_rev
cat: /sys/block/sata1/device/firmware_rev: No such file or directory
ash-4.4# ls -1 /sys/block/sata/device
ls: cannot access '/sys/block/sata/device': No such file or directory
ash-4.4# ls -1 /sys/block/sda/device
ls: cannot access '/sys/block/sda/device': No such file or directory

**Comment by stevenpDU** [comment]
Outcome:
![image](https://user-images.githubusercontent.com/128604316/227488153-8e48012f-c953-4667-bb3b-1f23bda72cd5.png)

**Comment by stevenpDU** [comment]
![image](https://user-images.githubusercontent.com/128604316/227488483-4aeb9097-76c0-4f87-9242-b1c2395d14bc.png)

**Comment by stevenpDU** [comment]
same outcome when running with sudo -i

**Comment by 007revad** [comment]
I wonder if they're incorrectly being detected as removable drives which would cause the script to skip them. 

Can you run the following command:
`sudo cat "/sys/block/sata1/removable"`

And this command:
`sudo for d in /sys/block/*; do hdmodel=$(cat "$1/device/model") && echo "$cardmodel"; done`

**Comment by stevenpDU** [comment]
First command:
sudo cat "/sys/block/sata1/removable"
1
----
Second command:
sudo for d in /sys/block/*; do hdmodel=$(cat "$1/device/model") && echo "$cardmodel"; done
-sh: syntax error near unexpected token `do'

**Comment by 007revad** [comment]
It's weird that `cat /sys/block/sata1/removable` returned 1 for you. For me it returns 0, and only USB or eSATA drives return 1.

For some reason sudo is causing an error in for ... do ... done. Thankfully I can run the command without sudo.

This should list all your drives:
`for d in /sys/block/[sh][ad]*; do hdmodel=$(cat "$d/device/model") && echo "$hdmodel" "$d"; done`

This should list if DSM thinks your drives are removable:
`for d in /sys/block/[sh][ad]*; do removable=$(cat "$d/removable") && echo "$removable" "$d"; done`

**Comment by 007revad** [comment]
I've released a new version, v1.2.24, to fix your issue.

**Comment by Greg-ATG** [comment]
It appears this issue occurs for any RS2421RP+ (we're running DSM6 and see internal drives with "removable = 1")

![image](https://user-images.githubusercontent.com/130684415/231813627-e05c0f90-000f-42a8-b3ca-7d0e0cb58b4d.png)

**Comment by 007revad** [comment]
Thanks @Greg-ATG 

I actually have a comment to myself in the script that says "Some DSM 7 RS models return 1 for internal drives!". It sounds like RS models return 1 for internal drives in both DSM 7 and DSM 6.

I added the removable drive check to prevent adding USB drives to the .db files to resolve an issue someone had. I'll find their issue and see if I can solve their issue another way.

**Comment by 007revad** [comment]
The latest version of syno_hdd_db no longer checks if "removable = 1". It's using a different method to check if a block device is a USB drive or not.

```
# $1 is /sys/block/sata1 or sys/block/sda etc
usb=$(grep $(basename -- "$1") /proc/mounts | grep usb | cut -d" " -f1-2)
```

**Comment by Greg-ATG** [comment]
Can you confirm which version this is fixed on?  I'm still seeing "No drives found" on v2.1.37.

Thanks for your work on this!

**Comment by 007revad** [comment]
Oops. I forgot to pull the changes from develop to main.

v2.1.38 is there now.

**Comment by Greg-ATG** [comment]
That did it!  Our disk is now being detected correctly.
