### ISSUE TITLE
Not working for WDC WUH722222ALE6L4

### ISSUE THREAD

**Issue by tgb-sw** [007revad/Synology_HDD_db#24]
New DS1823xs+ installed ST8000VN0022-2EL112, and KINGSTON SFYRD4000G worked without problems.
Today inserted WDC WUH722222ALE6L4 drives, script run without error:

Synology_HDD_db v1.2.18
DS1823xs+ DSM 7.1.1

HDD/SSD models found: 2
ST8000VN0022-2EL112,SC61
WDC WUH722222ALE6L4,W730

M.2 drive models found: 1
KINGSTON SFYRD4000G,EIFK31.6

No Expansion Units found

ST8000VN0022-2EL112 already exists in ds1823xs+_host_v7.db
ST8000VN0022-2EL112 already exists in ds1823xs+_host_v7.db.new
Added WDC WUH722222ALE6L4 to ds1823xs+_host_v7.db
Added WDC WUH722222ALE6L4 to ds1823xs+_host_v7.db.new
KINGSTON SFYRD4000G already exists in ds1823xs+_host_v7.db
KINGSTON SFYRD4000G already exists in ds1823xs+_host_v7.db.new

M.2 volume support already enabled.

Drive db auto updates already enabled.

DSM successfully checked disk compatibility.

Unfortunately the WDC drives still show as not verified

Is there anything I can check or provide additional information?

**Comment by 007revad** [comment]
I used to remove the "WDC " from WD SSD drives but I removed that part of the script after I though I'd a way to get the model number without the "WDC ". It looks like I might have to re-instate that bit of the script.

There's a new version, v.1.2.21, that should fix your issue.

**Comment by tgb-sw** [comment]
Great, using v1.2.23 fixed it. Thank you very much
