### ISSUE TITLE
No drive found and "bad substitution" errors

### ISSUE THREAD

**Issue by ev1lm0nk3y** [007revad/Synology_HDD_db#241]
Using the 3.4 release:

$ sudo -s <path to script>/syno_hdd_db.sh -snr
Password:
/volume1/homes/ryan/Synology_HDD_db-3.4.84/syno_hdd_db.sh: line 105: ${1,,}: bad substitution
Synology_HDD_db v3.4.84
DS923+ DSM 7.2.1-69057-3
/volume1/homes/ryan/Synology_HDD_db-3.4.84/syno_hdd_db.sh: line 166: ${model,,}: bad substitution
StorageManager 1.0.0-0017

Using options: -snr
Running from: /volume1/homes/ryan/Synology_HDD_db-3.4.84/syno_hdd_db.sh
/volume1/homes/ryan/Synology_HDD_db-3.4.84/syno_hdd_db.sh: line 659: ${vid,,}: bad substitution
/volume1/homes/ryan/Synology_HDD_db-3.4.84/syno_hdd_db.sh: line 592: ${1,,}: bad substitution

ERROR No drives found!
bebop% /usr/bin/env bash --version
GNU bash, version 3.2.54(1)-release (i686-pc-linux-gnu)
Copyright (C) 2007 Free Software Foundation, Inc.

===

M2 Drive is a WD Red SN700 1000GB and I didn't see that listed in the vendor list so I discovered the vendor id "1b96" and edited the file, but still no luck. The drive can't be used as a write cache at all, so it is kinda useless, decent for video playback i suppose

**Comment by 007revad** [comment]
The script needs to be located on the Synology. Not on your computer.

**Comment by 007revad** [comment]
The brands listed in the vendor list are brands that DSM does not already have in it's vendor id list. DSM already includes vendor id "1b96" as Sandisk.

**Comment by ev1lm0nk3y** [comment]
Sure, but it can only be used as a read-only cache and I would like to make
it into a RW cache. I thought that this would help me get that done. If
not, then I'll keep looking

**Comment by 007revad** [comment]
You need 2 identical NVMe drives to be able to create a read/write cache.

And you don't this script to be able to do that.
