### ISSUE TITLE
DS423+ Supported with 1 nvme driver only

### ISSUE THREAD

**Issue by pergolafabio** [007revad/Synology_HDD_db#243]
First of all, thnx a lot for this script!!! Works great

Usefull for other people:

DS423+ here, added only 1 x Samsung 970 evo plus TB
Running this script only is enough to make a storage pool from 1 nvme driver only
DSM 7.2.1-69057 Update 4 ( at this moment)

**Comment by pergolafabio** [comment]
hey @007revad , can you explain below?

I got a new DS423+ , i had an old SATA disk, only 1 disk present in the 4 bays, this was pure for testing the DS423
Also inserted one nvme syno drive , also for testing and your script worked, i was able to create a storage pool on the nvme

Now i purchased 4 new SATA drives, removed the old DISK, inserted 4 new DISKs ... i rerpesented me the wizard to setup a new DS423+ ... all OK

What i noticed, the DS423+ already recognized the storage pool on the nvme drive? without running your script...
How is that possible? Is it because the drive is already created as a storage pool before?

Maybe it will survive an DSM update anyway ?

**Comment by 007revad** [comment]
The DS423+ is one of the 8 Synology models that officially support NVMe volumes, so you didn't the script.

**Comment by pergolafabio** [comment]
yes and no, in order to create storage volumes officially on DS423+ , you need 2 x nvme drives
if only 1 is used, its only cacche

When i first installed DSM on the test drive, and i inserted the nvme drive later, i was not able to create a volume on the nvme, only after i runned your script

**Comment by pergolafabio** [comment]
I also think creating volumes you need an official synology brand for nvme drives , (if 2 x nvme are installed)

**Comment by 007revad** [comment]
DSM should let you create an NVMe volume with just 1 Synology NVMe drive.

With my script I don't need Synology branded NVMe drives and can create a Basic or SHR storage pool and volume on just 1 NVMe drive. All my script does is make DSM think my NVMe drive is a Synology NVMe drive.

**Comment by pergolafabio** [comment]
Yeah, but i have an "Samsung EVO 970 plus drive" :-) , it should not be possible

It was not possible when i first installed the DS423+ ... after running the sript, i was able to create the volume , not before
After replacing the DISKS in drive bay and reinstalling the DS423+ , the volume on the nvme was default visible

**Comment by 007revad** [comment]
Okay. In your 2nd comment you mentioned "inserted one nvme syno drive" so I thought you had a Synology NVMe drive.

DSM copies the system partition to all drives that have a storage pool on them (including NVMe drives even though DSM never runs from an NVMe drive).

So when you removed the single HDD the settings changes made by the script remained on the NVMe drive, which DSM would have copied to the new HDDs.

**Comment by pergolafabio** [comment]
Ok that makes sense :-)
