### ISSUE TITLE
TEAMGROUP SPCC

### ISSUE THREAD

**Issue by deja-geek** [007revad/Synology_HDD_db#254]
Installed 2 2TB SiliconPower NVMe Gen 3x4 drives (drives show last TEAMGROUP SPCC) in my 720+.  Ran the script, and the output said `SPCC M.2 PCIe SSD already exists in ds720+_host_v7.db`.  Rebooted and the drives showed as 'This Drive has not been tested or validated for m.2 ssd storage pools' and was not able to create a storage pool.

Reran the script with -i and the error went away and I was able to create a storage pool.  Perhaps TEAMGROUP needs to be added to the database.

**Comment by 007revad** [comment]
DSM already includes SPCC in the drive database but it has them set as incompatible. That's why I added the -i option.
