### ISSUE TITLE
Connnection lost and resumed repeatedly getting it every 

### ISSUE THREAD

**Issue by MirHekmat** [007revad/Synology_HDD_db#255]
<img width="1004" alt="image" src="https://github.com/007revad/Synology_HDD_db/assets/148930802/a3e35e39-54ea-4251-8ed3-7aafae81969f">
<img width="1210" alt="image" src="https://github.com/007revad/Synology_HDD_db/assets/148930802/2b71ffea-e909-4d13-b527-817eab1cc816">

Getting this error over 10-15 times a day in my emails it just doesn't seem to stop no matter what I do. 

Could you please suggest a fix for this

**Comment by MirHekmat** [comment]
Pretty sure its not my ISP because I have a 2nd backup Synology device with 10GB network with (E10G18-T1) and NOT the E10M20-T1, worth mention they are connected to the same network same switch same ISP. I do totally understand I have received those errors when I have restarted the modem due to slow internet etc, so I know what you mean by that.

that 2nd device with E10G18-T1 has never sent me any errors. Only this device with E10M20-T1, Also I have never had trouble accessing any data on any of these NAS while receiving these errors just random connect disconnect notification and they exist in the log center too. Do you think it could be a faulty E10M20-T1?

**Comment by MirHekmat** [comment]
here is a screen shot of the log centre. Pardon some of the scribbles because these are public form I am parnoid of some random hacker might cause me inconvenience. Also please let me know if I do leave some private info that pops out to you straight away so I can fix it. 

I do get alot more notification than the log centre registered here. 

<img width="1159" alt="image" src="https://github.com/007revad/Synology_HDD_db/assets/148930802/98c972de-f397-41ed-85e1-30a21fb46e85">

**Comment by 007revad** [comment]
Are both DS1821=+'s connected to the same UPS?

Are LAN 1, 2, 3 and 4 on a VLAN or separate LAN to the E10M20-T1?

Do you have the fan speed set to full?

I'm curious if the problem would move to the other DS1821+ if you swapped the E1018_T1 and E10M20-T1 between the 2 NAS (without running any scripts on the other NAS). 
- If you are using NVMe drives in the E10M20-T1 as a cache you'd need to delete the cache from the volume their assigned to.
- If you are using NVMe drives in the E10M20-T1 as a volume you can either remove them before installing the card, or just leave the NVMe drives installed and not do an online assemble.

**Comment by 007revad** [comment]
Do you have the same DNS servers set on both DS1821+?

**Comment by MirHekmat** [comment]
Are both DS1821+'s connected to the same UPS? **Yes it was**

Are LAN 1, 2, 3 and 4 on a VLAN or separate LAN to the E10M20-T1? **I don't remember connecting any cables to LAN 1~4 on the mentioned date so I am confused ( LAN 1~4 is built in 1GBE ports isn't it ) I don't use VLAN**

Do you have the fan speed set to full? **yes I changed the fan speed to full as I thought maybe its heating up**

I'm curious if the problem would move to the other DS1821+ if you swapped the E1018_T1 and E10M20-T1 between the 2 NAS (without running any scripts on the other NAS). **I wouldn't risk changing hardware on the 2nd device as thats my only backup trying to keep that as compatible hardware as possible**

If you are using NVMe drives in the E10M20-T1 as a cache you'd need to delete the cache from the volume their assigned to.
**Not applicable for me as I don't use Cache on those NVME's I use it as volume**
If you are using NVMe drives in the E10M20-T1 as a volume you can either remove them before installing the card, or just leave the NVMe drives installed and not do an online assemble. **Not keen on moving hardware across, if there is another solution to this happy to hear**

**Comment by 007revad** [comment]
Go to "Control Panel > Network > General" and check if  "Manually configure DSN server" is selected. If it is note what the Preferred and Alternative DNS server addresses are. Then compare that to the backup NAS.

**Comment by 007revad** [comment]
Those log entries at 15:03:07 show LAN 1, 2, 3 and 4 getting an IP address and subnet mask via DHCP.

I just rebooted my DS720+ and only the LAN port that has a cable plugged in shows up in the log.

If you go to  "Control Panel > Network > Network Interface" are LAN 1, 2, 3 and 4 showing as Disconnected with IP addresses starting with 169.254 ?

**Comment by MirHekmat** [comment]
<img width="881" alt="image" src="https://github.com/007revad/Synology_HDD_db/assets/148930802/6b129eeb-4e59-4cc4-a685-ea2668ec8ddc">
<img width="422" alt="image" src="https://github.com/007revad/Synology_HDD_db/assets/148930802/203ee8ae-2da4-41f0-b5c5-baa553147c42">

**Comment by 007revad** [comment]
Does the backup NAS also have "Manually configure DSN server" disabled?

**Comment by MirHekmat** [comment]
I'll have to check that one for you as I have turned of too move it to an offsite location.
