### ISSUE TITLE
System partitions on nvme storage pool 

### ISSUE THREAD

**Issue by vdovhanych** [007revad/Synology_HDD_db#256]
Will Synology install its system components on the nvme volume if it's created through Storage Manager after adding the drives to the supported list using this script? 

I've used the script on my ds918+, and it let me create a storage pool and volume on the two nvme drives directly in the storage manager, but from what I can see, the drives were not added to `/dev/md0` and `/dev/md1` which should be Synology system raid partitions. It created the system partitions on the NVME drives, but it's not being used in any way for system stuff. 

Also, I don't know if the officially supported NVME storage pool fe. on DS423+ installs the system stuff on the NVME drive partitions.

**Comment by 007revad** [comment]
I asked a similar question 9 months ago on reddit : https://www.reddit.com/r/synology/comments/13swjo6/installing_dsm_on_an_nvme_drive_with_no_sata/ 

DSM creates an NVMe storage pool the same as HDD storage pools, but the boot loader does not normally mount the system or swap partitions that are on NVMe drives. But the replies in that reddit thread outlined a couple of ways to get DSM to run off the NVMe drives. Though neither method is something I would do for the small benefit.

**Comment by vdovhanych** [comment]
Thanks for the post.

> Though neither method is something I would do for the small benefit.

After reading the thread, I'm with you on this one. The benefit would be really small compared to the troubles you'd have to go through to set it up in the first place.

Thanks for the reply. I'll close this issue as it is not really relevant here.
