### ISSUE TITLE
DS1821+ E10m20-t1 "no m.2 PCIe cards found

### ISSUE THREAD

**Issue by Storchinup** [007revad/Synology_HDD_db#262]
I'm new to github as well as Synology but I've managed to get the 970 nvme ssds on the internal slots working fine as a volume, I have a E10m20-t1 card installed and mainly just want to use it as a 10g nic till I get more nvme drives to use for caching later, but every time I run the script via PuTTY it says no m.2 PCIe cards found, ive tried the 3.1.60-RC and the regular 3.4.86 
any help is appreciated very much!
![Screenshot 2024-03-08 191709](https://github.com/007revad/Synology_HDD_db/assets/162763030/1580f23b-6f48-4e7d-b40f-75fa62d857c3)
![Screenshot 2024-03-08 191809](https://github.com/007revad/Synology_HDD_db/assets/162763030/68c9c256-7e3b-4135-9066-1cf276bddf99)
![Screenshot 2024-03-08 191842](https://github.com/007revad/Synology_HDD_db/assets/162763030/27275ffb-5149-4a67-a4cd-c4daea9f8ed1)

**Comment by 007revad** [comment]
For some strange reason Synology never enabled the M.2 slots in the E10M20-T1, M2D20, M2D18 or M2D17 for the DS1821+, DS1621+ and the FS2500. 

So I wrote https://github.com/007revad/Synology_enable_M2_card to add the missing support.

If you want to use 3 or 4 NVMe drives as 1 storage pool you can use RAID F1 if you enable RAID F1 with https://github.com/007revad/Synology_SHR_switch

**Comment by Storchinup** [comment]
Incredible! worked first try thank you so much! I don't have any extra nvme drives to test but now the Nic is working beautifully and I'm very happy I don't have to return the E10M20-T1, thank you so much! and you responded so quickly!
