### ISSUE TITLE
Disable non-Synology recommended memory module configurations message.

### ISSUE THREAD

**Issue by costispavlou** [007revad/Synology_HDD_db#272]
what is the command to disable this message? 

![image](https://github.com/007revad/Synology_HDD_db/assets/57916603/82d0668e-5f2f-4fa9-883d-6d64b839d3d5)

I tried 

```
sudo -s /volume1/data/Backup/Synology/Synology_HDD_db-3.4.87/syno_hdd_db.sh --ram
Synology_HDD_db v3.4.87
DS1618+ DSM 7.1.1-42962-6
ds1618+_host_v7 version 8046

Using options: --ram
Running from: /volume1/data/Backup/Synology/Synology_HDD_db-3.4.87/syno_hdd_db.sh

HDD/SSD models found: 3
MG06ACA800E,0108
ST14000NE0008-2JK101,EN01
ST6000VX0023-2EF110,SC60

No M.2 drives found

No M.2 PCIe cards found

No Expansion Units found

MG06ACA800E already exists in ds1618+_host_v7.db
MG06ACA800E already exists in ds1618+_host_v7.db.new
ST14000NE0008-2JK101 already exists in ds1618+_host_v7.db
ST14000NE0008-2JK101 already exists in ds1618+_host_v7.db.new
ST6000VX0023-2EF110 already exists in ds1618+_host_v7.db
ST6000VX0023-2EF110 already exists in ds1618+_host_v7.db.new

Support disk compatibility already enabled.

Max memory is set to 32 GB.

Drive db auto updates already enabled.

DSM successfully checked disk compatibility.

You may need to reboot the Synology to see the changes.
```

but still pops up after restart.

**Comment by 007revad** [comment]
Run the script with `-nr` or `--noupdate --ram`

The `-n` or `--noupdate` will prevent DSM updating the drive databases when the NAS boots, when you insert a different drive etc.

Is there any reason why your DS1618+ is still on DSM 7.1.1 when 7.2.1 is available?

**Comment by costispavlou** [comment]
so it should be 

`sudo -s /volume1/data/Backup/Synology/Synology_HDD_db-3.4.87/syno_hdd_db.sh --nr `  ?

I haven't noticed to be honest about there was an update eh.

**Comment by costispavlou** [comment]
using the above command does nothing

![image](https://github.com/007revad/Synology_HDD_db/assets/57916603/a3dda503-f58d-4b9b-bcb9-a778e7d2af42)

**Comment by costispavlou** [comment]
> Run the script with `-nr` or `--noupdate --ram`
> 
> The `-n` or `--noupdate` will prevent DSM updating the drive databases when the NAS boots, when you insert a different drive etc.
> 
> Is there any reason why your DS1618+ is still on DSM 7.1.1 when 7.2.1 is available?

![image](https://github.com/007revad/Synology_HDD_db/assets/57916603/ed28e139-869f-4d53-85ac-aabddac56b67)

no idea what's going on..

**Comment by 007revad** [comment]
> so it should be
> 
> `sudo -s /volume1/data/Backup/Synology/Synology_HDD_db-3.4.87/syno_hdd_db.sh -nr ` ?

Correct.
 
> I haven't noticed there was an update. it shows I'm up to date. any ideas?

If I remember correctly for some older models DSM 7.1.1 did not notify you that DSM 7.2 was available. So people with models older than '20 series needed to download the 7.2 pat. 

https://www.synology.com/en-global/support/download/DS1618+?version=7.2#system

**Comment by 007revad** [comment]
> no idea what's going on..

That's weird because the Synology website says you can go from 7.1.1 to "7.2.1 (with update 1)"... which actually surprised me because because normally it says things like "7.1.1 to 7.2 to 7.2.1"

Try 7.2
https://global.synologydownload.com/download/DSM/release/7.2/64570-1/DSM_DS1618%2B_64570.pat

Then 7.2.1 (with update 1)
https://global.synologydownload.com/download/DSM/release/7.2.1/69057-1/DSM_DS1618%2B_69057.pat

Then 7.2.1 update 4
https://global.synologydownload.com/download/DSM/criticalupdate/update_pack/69057-4/synology_denverton_1618%2B.pat

**Comment by 007revad** [comment]
> it doesn't work.. after boot it still sends the same message

Did you clear the old message?

**Comment by costispavlou** [comment]
> > it doesn't work.. after boot it still sends the same message
> 
> Did you clear the old message?

i did yeah.

**Comment by costispavlou** [comment]
is it -s or -i ?

**Comment by 007revad** [comment]
You can use sudo -i or sudo -s
- sudo -s runs the command as you but with root privileges.
- sudo -i runs the command as root.

You are better off scheduling the script to run at boot up.
https://github.com/007revad/Synology_HDD_db/blob/main/how_to_schedule.md

For step of setting up the scheduled task you would enter:
`/volume1/data/Backup/Synology/Synology_HDD_db-3.4.87/syno_hdd_db.sh -nr`

Did you manage to update to DSM 7.2.1 ?

**Comment by costispavlou** [comment]
> You can use sudo -i or sudo -s
> 
> * sudo -s runs the command as you but with root privileges.
> * sudo -i runs the command as root.
> 
> You are better off scheduling the script to run at boot up. https://github.com/007revad/Synology_HDD_db/blob/main/how_to_schedule.md
> 
> For step 8 in the screenshot, or step 9 in instructions, of setting up the scheduled task you would enter: `/volume1/data/Backup/Synology/Synology_HDD_db-3.4.87/syno_hdd_db.sh -nr`
> 
> Did you manage to update to DSM 7.2.1 ?

i've found the fix yes, but did not update yet, i'll probably do it today though. I'm just afraid that it will auto update an app (surveillence station) that i do not want to update. But i'll probably reinstall it later since if that happens. 

As far as the script goes, does it need to always run at boot? or once and then never again ? 

What i did was to run the script and then reboot to check if it worked (which it didnt). 
I tried both -s and -i. But i did not schedule it to run at boot.

**Comment by 007revad** [comment]
The script only needs to be run after a DSM update, but it's easier to just schedule it at boot up because DSM can update itself sometimes.

Do both the following commands return "127.0.0.1" ?
```
synogetkeyvalue /etc.defaults/synoinfo.conf drive_db_test_url
synogetkeyvalue /etc/synoinfo.conf drive_db_test_url
```

**Comment by costispavlou** [comment]
you mean ssh on it and run these two commands? 
it's off right now but i will test in an hour or so when it boots and report back with the result of the two commands. 
Thanks for your help!

**Comment by 007revad** [comment]
> you mean ssh on it and run these two commands?

Yes.

I'm wondering if this unique to the DS1618+. Like the DVA1622 and DVA1321 which have the same problem and I had to add an extra command in syno_hdd_db.sh for those models.

Try this command and see if it stops the memory warnings:
```
sudo -s synosetkeyvalue /usr/lib/systemd/system/SynoMemCheck.service ExecStart /bin/true
```

**Comment by 007revad** [comment]
Interesting.

I just checked synoninfo.conf for all 115 NAS models that support DSM 7.2 and 77 of them do not have support_memory_compatibility

So setting `support_memory_compatibility="no"` only works on 38 NAS models.

The other 77 need `synosetkeyvalue /usr/lib/systemd/system/SynoMemCheck.service ExecStart /bin/true`

**Comment by x-magic** [comment]
> > you mean ssh on it and run these two commands?
> 
> Yes.
> 
> I'm wondering if this unique to the DS1618+. Like the DVA1622 and DVA1321 which have the same problem and I had to add an extra command in syno_hdd_db.sh for those models.
> 
> Try this command and see if it stops the memory warnings:
> 
> ```
> sudo -s synosetkeyvalue /usr/lib/systemd/system/SynoMemCheck.service ExecStart /bin/true
> ```

DS1819+ won't work with `support_memory_compatibility` either. Needs to stop the service to disable the message.

**Comment by 007revad** [comment]
@x-magic 

I notice that only 11 models have support_memory_limitation instead of support_memory_compatibility

What happens if you disable support_memory_limitation but leave SynoMemCheck.service enabled ?

If the script was run with the -r or --ram option, and support_memory_compatibility does not exist in synoinfo.conf, the script disables the SynoMemCheck.service

**Comment by x-magic** [comment]
@007revad I'll try it out. Just not sure when will my NAS reboot next time, but will certainly follow up.
