### ISSUE TITLE
Can't Create Storate pool on M.2 SSD

### ISSUE THREAD

**Issue by dateno1** [007revad/Synology_HDD_db#278]
DSM is Lastest (7.2.1 U5)

I was connect SSSTC CL1-8D256 (for test) on DS3622xs by NVMe PCIe Adaptor

Download lastest version (3.5.89) and Upload it on HDD volume -> Extract -> Edit syno_hdd_vendor_ids.txt (add 0x1e95) -> run -> Reboot

but can't create volume on it
![image](https://github.com/007revad/Synology_HDD_db/assets/12645246/87b96575-c9eb-43e5-9190-ae7affee8e90)

reboot -> try -> fail
reboot -> rerun script -> try -> fail

Script result no warning or error

**Comment by 007revad** [comment]
Is the NVMe PCIe Adaptor a M2D20, M2D18 or E10M20-T1?

Did the script find the SSSTC CL1-8D256?

Did the "M.2 Drive 1-1" show in Storage Manager before you ran the script?

If you go to "Storage Manager > Overview" do you see the PCIe Adaptor?

That "Manage Available Drives" window is new. What version does the Storage Manager package show in Package Center?

**Comment by dateno1** [comment]
> Is the NVMe PCIe Adaptor a M2D20, M2D18 or E10M20-T1?
> 
> Did the script find the SSSTC CL1-8D256?
> 
> Did the "M.2 Drive 1-1" show in Storage Manager before you ran the script?
> 
> If you go to "Storage Manager > Overview" do you see the PCIe Adaptor?
> 
> That "Manage Available Drives" window is new. What version does the Storage Manager package show in Package Center?

PCIe Adaptor is not synology model (for PC)

Script can recognized CL1-8D256 and added SSSTC on HDDDB

Yes i can find M.2 on Storage manager before used script (It just changed unknown -> SSSTC)

Storage Manager v1.0.0-0017@7.2.1 U5 (Lastest@Lastest)

Used HDD*4@RAID5 + SATA SSD*2@RAID1 (Cache)

Now i want to add new volume for fast speed by NVMe disk (Maybe use Oracle F320 or Intel P3600. SSSTC CL1-8D256 is test purpose)

**Comment by 007revad** [comment]
Which brand and model PCIe adaptor do you have?

In "Control Panel > Info Center" what does it show for "PCIe Slot 1" ?

When you get the "Cannot perform this action. No drive are available or meet the requirements." can you click on the "View drive requirements" link and tell me what it says?

Try:
```
sudo set_section_key_value /usr/syno/etc.defaults/adapter_cards.conf FX2422N_sup_nvme DS3622xs+ yes
sudo set_section_key_value /usr/syno/etc/adapter_cards.conf FX2422N_sup_nvme DS3622xs+ yes
sudo set_section_key_value /usr/syno/etc.defaults/adapter_cards.conf M2D18_sup_nvme DS3622xs+ yes
sudo set_section_key_value /usr/syno/etc/adapter_cards.conf M2D18_sup_nvme DS3622xs+ yes
```

What do these command return?
```
sudo grep 'notSupportM2Pool_addOnCard' /var/packages/StorageManager/target/ui/storage_panel.js
```

Can you run this script and paste the output, or a screenshot?
https://github.com/007revad/Synology_HDD_db/blob/test/nvme_check.sh

**Comment by 007revad** [comment]
You can use https://github.com/007revad/Synology_M2_volume to create the storage pool and volume.

But I'd also like to know the answers to my questions in my previous comment so I can add support for non-Synology PCIe adaptors.

**Comment by 007revad** [comment]
You could also try these commands to enable creating the NVMe storage pool in Storage Manager.
```
strgmgr="/usr/local/packages/@appstore/StorageManager/ui/storage_panel.js"
sudo sed -i 's/notSupportM2Pool_addOnCard:this.T("disk_info","disk_reason_m2_add_on_card"),//g' "$strgmgr"
sudo sed -i 's/},{isConditionInvalid:0<this.pciSlot,invalidReason:"notSupportM2Pool_addOnCard"//g' "$strgmgr"
```

**Comment by dateno1** [comment]
> Which brand and model PCIe adaptor do you have?
I don't know

I was bought it from aliexpress at few years ago

It just dummy converter (PCIe-NVMe) 


> In "Control Panel > Info Center" what does it show for "PCIe Slot 1" ?
> 
> When you get the "Cannot perform this action. No drive are available or meet the requirements." can you click on the "View drive requirements" link and tell me what it says?

![Result1](https://github.com/007revad/Synology_HDD_db/assets/12645246/e5948327-0d60-410d-966d-d0353606425b)

> What do these command return?
> 
> ```
> sudo grep 'notSupportM2Pool_addOnCard' /var/packages/StorageManager/target/ui/storage_panel.js
> ```

[notSupportM2Pool_addOnCard.txt](https://github.com/007revad/Synology_HDD_db/files/14939562/notSupportM2Pool_addOnCard.txt)

> Can you run this script and paste the output, or a screenshot? https://github.com/007revad/Synology_HDD_db/blob/test/nvme_check.sh

DS3622xs+
DSM 7.2.1-69057 Update 5
2024-04-11 10:01:34

 Checking support_m2_pool setting
/etc.defaults/synoinfo.conf: yes
/etc/synoinfo.conf:          yes

 Checking supportnvme setting
/etc.defaults/synoinfo.conf: yes
/etc/synoinfo.conf:          yes

 Checking synodisk --enum -t cache
************ Disk Info ***************
>> Disk id: 1
>> Slot id: 1
>> Disk path: /dev/nvme0n1
>> Disk model: SSSTC CL1-8D256
>> Total capacity: 238.47 GB
>> Tempeture: 30 C

 Checking syno_slot_mapping
----------------------------------------
./nvme_check.sh: line 53: syno_slot_mapping: command not found
----------------------------------------

 Checking udevadm nvme paths
nvme0: /devices/pci0000:00/0000:00:01.0/0000:05:00.0/nvme/nvme0

 Checking if nvme drives are detected with synonvme
nvme0: It is a NVMe SSD
nvme0: Vendor name: SSDT
nvme0: Model name: SSSTC CL1-8D256

 Checking nvme drives in /run/synostorage/disks
nvme0n1

 Checking nvme block devices in /sys/block
nvme0n1

 Checking logs
----------------------------------------
Current date/time:   2024-04-11 10:01:34
Last boot date/time: 2024-04-11 09:37:21
----------------------------------------

**Comment by dateno1** [comment]
> Try:
> 
> ```
> sudo set_section_key_value /usr/syno/etc.defaults/adapter_cards.conf FX2422N_sup_nvme DS3622xs+ yes
> sudo set_section_key_value /usr/syno/etc/adapter_cards.conf FX2422N_sup_nvme DS3622xs+ yes
> sudo set_section_key_value /usr/syno/etc.defaults/adapter_cards.conf M2D18_sup_nvme DS3622xs+ yes
> sudo set_section_key_value /usr/syno/etc/adapter_cards.conf M2D18_sup_nvme DS3622xs+ yes
> ```



> You could also try these commands to enable creating the NVMe storage pool in Storage Manager.
> 
> ```
> strgmgr="/usr/local/packages/@appstore/StorageManager/ui/storage_panel.js"
> sudo sed -i 's/notSupportM2Pool_addOnCard:this.T("disk_info","disk_reason_m2_add_on_card"),//g' "$strgmgr"
> sudo sed -i 's/},{isConditionInvalid:0<this.pciSlot,invalidReason:"notSupportM2Pool_addOnCard"//g' "$strgmgr"
> ```

both not work (same result)

**Comment by 007revad** [comment]
You should be able to use https://github.com/007revad/Synology_M2_volume to create the storage pool.

**Comment by dateno1** [comment]
I was give up it

Create volume by terminal

Now all work well

Thanks for help
