### ISSUE TITLE
M2 FireCuda 530 Not Detected on Synology DS923+

### ISSUE THREAD

**Issue by aelmardi** [007revad/Synology_HDD_db#292]
Hello,

I'm experiencing an issue where my M2 storage FireCuda 530 is not being detected on my Synology DS923+, currently running DSM 7.2.0.

Ive executing the script here's the result :

<img width="551" alt="image" src="https://github.com/007revad/Synology_HDD_db/assets/114397057/8d157e0b-8044-4362-a5b5-1ca91472bc84">

I reboot but still not working, It only detected my SSD SATA :
<img width="1499" alt="image" src="https://github.com/007revad/Synology_HDD_db/assets/114397057/17ff0afa-71e8-44f6-8a9a-236de6e7ac56">

**Comment by 007revad** [comment]
Did storage manager show the NVMe drive before you ran the script?

**Comment by aelmardi** [comment]
Actually, everything was working perfectly on DSM version 7.1.1, but then I updated DSM to its latest version and it started saying that the M2 disk was unknown. I completely formatted my DSM and now I realize it no longer detects my M2 disk even before running the script, and even after running the script, the disk remains undetectable. I suspect it might be due to the latest DSM version 7.1.2, but I'm not certain.

**Comment by 007revad** [comment]
Schedule syno_hdd_db.sh to run the with -n option at startup as root: `/volume1/test/syno_hdd_db.sh -n`
https://github.com/007revad/Synology_HDD_db/blob/main/how_to_schedule.md

Then reboot. If the NVMe drive is still missing, reboot again.

**Comment by aelmardi** [comment]
I've scheduled the script and restart multiple times, but I still can't see my disk appearing.

**Comment by 007revad** [comment]
Make sure the only script scheduled to run at boot is `syno_hdd_db.sh -n`

Then remove the NVMe drive. Reboot the NAS. Shut down the NAS and reinstall the NVMe drive. Then boot the NAS.

While the NVMe drive is out of the NAS you could delete all the partitions that are on it (if you can connect it to a computer).

**Comment by aelmardi** [comment]
I followed the procedure but the disk is still not found on DSM.

I formatted the disk and deleted all the partitions, but it didn't help. The only script scheduled to run at boot is syno_hdd_db.sh -n.

Despite these steps, the disk remains undetected on DSM.

**Comment by 007revad** [comment]
Can you run this script and reply with a screenshot of the output: https://github.com/007revad/Synology_HDD_db/blob/test/nvme_check.sh

**Comment by aelmardi** [comment]
Here's the result :

/volume1/Scripts$ sudo ./nvme_check.sh
Password:
DS923+
DSM 7.2.1-69057 Update 5
2024-06-02 11:50:29

 Checking support_m2_pool setting
/etc.defaults/synoinfo.conf: yes
/etc/synoinfo.conf:          yes

 Checking supportnvme setting
/etc.defaults/synoinfo.conf: yes
/etc/synoinfo.conf:          yes

 Checking synodisk --enum -t cache

 Checking syno_slot_mapping
----------------------------------------
System Disk
Internal Disk
01: /dev/sata1
02:
03:
04:
05:
06:
07:
08:
09:
10:
11:
12:
13:
14:
15:
16:

Esata port count: 0
USB Device
01:
02:
03:
04:
05:
06:
07:
08:
09:
10:
11:
12:
13:
14:
15:
16:
17:
18:

Internal SSD Cache:
01:

----------------------------------------

 Checking udevadm nvme paths
nvme0: /devices/pci0000:00/0000:00:1d.0/0000:6d:00.0/nvme/nvme0

 Checking if nvme drives are detected with synonvme
nvme0: It is a NVMe SSD
nvme0: Vendor name: Seagate
nvme0: Model name: Seagate FireCuda 530 ZP2000GM30

 Checking nvme drives in /run/synostorage/disks

 Checking nvme block devices in /sys/block
nvme0n1

 Checking logs
----------------------------------------
Current date/time:   2024-06-02 11:50:29
Last boot date/time: 2024-06-02 11:46:07
----------------------------------------

**Comment by 007revad** [comment]
Your NVMe drive is missing in syno_slot_mapping and /run/synostorage/disks. If I remember correctly this can be caused by the device tree blob (model.dtb) not containing the correct nvme information, or it's missing the power_limit which Synology added in DSM 7.2.1 Update 1.

Someone else has 2 NVMe drives that DSM is not seeing and they're sending those NVMe drives to me so I can work out why DSM is not seeing them.

You could reinstall DSM 7.2.1 which will restore any corrupt or missing files. It's no different than doing a DSM update. 
1. Disable the syno_hdd_db schedule.
2. Run https://github.com/007revad/Synology_DSM_reinstall 
3. Manually install https://global.synologydownload.com/download/DSM/release/7.2.1/69057-1/DSM_DS923%2B_69057.pat
4. DSM will automatically update itself to DSM 7.2.1 update 5.
5. Check if the drive shows in storage manager as a M.2 Cache drive.

**Comment by aelmardi** [comment]
I followed the steps exactly as described, and it successfully reinstalled DSM. However, when I go to Storage Manager, nothing is displayed.

**Comment by aelmardi** [comment]
Is it possible to downgrade to version 7.1.1 to confirm that the problem is with the new version ?

**Comment by 007revad** [comment]
You can downgrade to 7.1.1 but it's not easy. And you lose all the data on the drives.

If you're going to try it you'd want to: 
1. Shut down the DS923+.
2. Remove the existing drives.
3. Insert any old spare HDD.
4. Boot the DS923+.
5. Use Synology Assistant to find the DS923+
6. Do the initial setup process.

Then see if you can downgrade to DSM 7.1.1

I'd follow these steps https://www.blackvoid.club/dsm-7-to-dsm-6-downgrade/ but modify them for 7.2 to 7.1.1

In steps 3 and 5 change the contents of the VERSION file to this:
```
majorversion="7"
minorversion="1"
major="7"
minor="1"
micro="0"
productversion="7.1"
buildphase="GM"
buildnumber="42661"
smallfixnumber="0"
nano="0"
base="42661"
builddate="2022/04/01"
buildtime="17:48:27"
```

In step 5 if the Telnet password is not `101-0101` you can generate the DSM telnet 'password of the day' with the following on any computer that can run bash:
```
#!/bin/bash

# Get current month and day
month=$(date +%m) # Month (01 to 12)
day=$(date +%d) # Day of the month (01 to 31)

# Function to calculate greatest common divisor in Bash
gcd(){ 
    # $1 decimal month as decimal
    # $2 decimal day as decimal
    if [ $2 -eq 0 ]; then
        echo $1
    else
        gcd $2 $(($1 % $2))
    fi
}

# Calculate greatest common divisor between month and day
gcd_result=$(gcd $month $day)

# Format and print the password
printf "Password for today is: %x%02d-%02x%02d\n\n" $month $month $day $gcd_result
```

Or if you prefer python: https://blog.thomasmarcussen.com/synology-nas-recovery-password-telnet/

In step 6 use this pat file: https://global.synologydownload.com/download/DSM/release/7.1.1/42962/DSM_DS923%2B_42962.pat

**Comment by aelmardi** [comment]
Hello sorry for the delay.

I downgraded to version 7.1.1 and it actually works well :

<img width="1245" alt="Screenshot 2024-06-22 at 13 18 31" src="https://github.com/007revad/Synology_HDD_db/assets/114397057/d4d0dbd8-668e-4f27-8c41-47294d7c478d">

**Comment by 007revad** [comment]
Weird that the M.2 drive isn't detected by DSM 7.2.1 but is in DSM 7.1.1
