### ISSUE TITLE
How to delete the storage space created by ssd

### ISSUE THREAD

**Issue by anxinJ** [007revad/Synology_HDD_db#302]
In DS1520 DSM7.2, I successfully set up the SSD as a storage space, but now I want to delete it. After clicking delete, the storage space status changed to 'destroyed.' What should I do?
![image](https://github.com/007revad/Synology_HDD_db/assets/10701711/efcd7722-f50f-4a1f-a3cf-f2e6169f10dc)

**Comment by 007revad** [comment]
See if it will let you delete volume 4. If that works then try to delete storage pool 4 again.

If that doesn't work try this: 
1. Shut down the DS1520+.
2. Remove the NVMe drive.
3. Start the DS1520+.
4. Delete the storage pool.
5. Shut down the DS1520+.
6. Install the NVMe drive.
7. Start the DS1520+.
