### ISSUE TITLE
When you are in an all-SSD environment, you may find an HDD error

### ISSUE THREAD

**Issue by proxy2008** [007revad/Synology_HDD_db#303]
By blocking the code below, it works fine

```
# Check hdds array isn't empty
if [[ ${#hdds[@]} -eq "0" ]]; then
    ding
    echo -e "\n${Error}ERROR${Off} No drives found!" && exit 2
else
    echo -e "\nHDD/SSD models found: ${#hdds[@]}"
    num="0"
    while [[ $num -lt "${#hdds[@]}" ]]; do
        echo "${hdds[num]}"
        num=$((num +1))
    done
    echo
fi
```

I guess if this can be controlled by adding a parameter

**Comment by 007revad** [comment]
Which Synology NAS model? And which DSM version?

Are they SATA or SAS SSDs?

**Comment by 007revad** [comment]
I'm not seeing the issue in a NAS with just SATA SSDs and NVMes.

Are you using just NVMe drives?

**Comment by 007revad** [comment]
Do you want to try this new release https://github.com/007revad/Synology_HDD_db/releases/tag/v3.5.91

[commit c43662d](https://github.com/007revad/Synology_HDD_db/commit/c43662d)

**Comment by proxy2008** [comment]
Thank you for providing such an important and useful tool, and I will use it when reworking the system.
