### ISSUE TITLE
Questions about DS1621+ using Synology nvme expansion card.

### ISSUE THREAD

**Issue by lingyinsam** [007revad/Synology_HDD_db#309]
My device is DS1621+, and I hope to use the nvme expansion card of Group Hui through the pcie interface. However, I found in the introduction of the official website that DS1621+ does not support any nvme expansion cards. I would like to know if the Synology system can recognize the m2 hard drive installed with the nvme expansion card after I use your script. Thank you very much!

**Comment by 007revad** [comment]
See https://github.com/007revad/Synology_enable_M2_card

You'll need to run Synology_enable_M2_card first. Then run Synology_HDD_db

**Comment by lingyinsam** [comment]
I successfully installed E10M20-T1 on my DS1621+ and the system recognized it normally.With the highest gratitude!
![微信截图_20240630142912](https://github.com/007revad/Synology_HDD_db/assets/69802837/1b57754e-c8cc-4008-8d3d-d0c016bc9360)
![QQ截图20240630142845](https://github.com/007revad/Synology_HDD_db/assets/69802837/cc2fe433-0e1c-4681-9710-8c7e40ad4c79)
