### ISSUE TITLE
Failed to delete tmp files

### ISSUE THREAD

**Issue by aferende** [007revad/Synology_HDD_db#312]
Hi,
When the script is executed (scheduled at NAS startup), I find these warnings shown in the figure in the error log.
The script is correctly updated and executed but with these warnings (task scheduled with root permissions).

`syno_hdd_db.sh -r --autoupdate=0`

![Warnings](https://github.com/007revad/Synology_HDD_db/assets/13355101/95c41064-8e8d-41eb-9d3f-ec1c8df7fb56)

Ty,
Andrea.

**Comment by 007revad** [comment]
I've fixed this bug in https://github.com/007revad/Synology_HDD_db/releases/tag/v3.5.93 

I'm surprised nobody else has noticed this bug (including myself!). This bug has existed since Sep 2013 in v3.1.64. And it's also in 4 of my other scripts.
