### ISSUE TITLE
Error: "This script is NOT runnning on a Synology NAS!"... but it is!!

### ISSUE THREAD

**Issue by madmax-71** [007revad/Synology_HDD_db#333]
Hi, I tried running your script and received an error message claiming the script is not running on a Synology NAS.
But it is... Any ideas? BTW I am running DSM 7.2.1-69057 Update 5 on my DS723+.
Thanks
Alex

**Comment by arbitarytwist** [comment]
I have run the script on a DS723+ on Update 5 and it seems to be running.  Are you getting an error ?

**Comment by 007revad** [comment]
@madmax-71 

What does the following command return?
```
uname -a

```

**Comment by 007revad** [comment]
The syno_hdd_db.sh and syno_hdd_vendor_ids.txt need to be located in a shared folder on your Synology.

Then you need to enable SSH on Synology. https://kb.synology.com/en-global/DSM/tutorial/How_to_login_to_DSM_with_root_permission_via_SSH_Telnet

Then on the Mac mini you connect via SSH to the Synology and run the syno_hdd_db.sh script.

**Comment by madmax-71** [comment]
> Then on the Mac mini you connect via SSH to the Synology and run the syno_hdd_db.sh script.

That was the problem, I forgot to connect via SSH. Thanks for your help!
