### ISSUE TITLE
After working fine for several months, Warning Emails for 1st of Month

### ISSUE THREAD

**Issue by packetdog** [007revad/Synology_HDD_db#338]
Good day,

Your script has been working great, but the change seems to have reverted this week. I have a DS1823xs+ with 8 Samsung Evo 2TB drives in it. I was under the impression these script changes could be overwritten with DSM and/or potential app updates. I have 1 of 3 DS1823xs+ units that have magically started to show the warning status, none with a recent DSM or any app updates. This also triggered an email alert for each drive.

The DiskStation has been up for 62 days, no changes. The last DSM update was installed 62 days ago, and the last app updates as well. As far as I can tell nothing has changed. We also have 2 other DS1823xs+ units set up in an HA cluster with the same drives, and nothing happening there, both show healthy. 

Before I download and re-run the most current script, I thought I'd open an issue to see if there is anything I can gather off of the device to help with troubleshooting or prevention of this issue in the future?

**Comment by 007revad** [comment]
Maybe you didn't run the script with the -n or --noupdate option? It prevents DSM updating the compatible drive databases.

Or did someone download and install the latest Synology HDD/SSD Offline Update Pack?

**Comment by packetdog** [comment]
I'm sure I didn't run it with the -n or --noupdate option, I don't think I saw that. I just thought it was weird because it seemed to be unrelated to a DSM or application update.. and why after 62 days.. Just strange all around so I thought it was worth commenting here to help the greater community. If there's nothing else, I'll download the latest version of the script and run it with the -n option. :)

**Comment by 007revad** [comment]
This issue comes up every time Synology update their drive compatibility list.

I'm considering changing the script so it disables drive compatibility database updates even when the script is run without the -n or --noupdate option.

**Comment by packetdog** [comment]
FWIW, I ran it with the -n switch, and the Web UI updated immediately. As long as the team is aware. Thanks for the fast response.
