### ISSUE TITLE
E10M20-T1 displayed, but won't work.

### ISSUE THREAD

**Issue by strikedamic** [007revad/Synology_HDD_db#349]
Hello,
I've bought a Synology E10M20-T1 for my DS1621+ after it was listed to be compatible somewhere. Turns out it's not, at least not out of the box.
I'm a noob to this and I believe I've read somewhere that with your script, the E10M20-T1 can be made to work for the DS1621+, is that so? I ran the script successfully via Putty, but it listed "no PCIe cards found" although the card gets listed fine in the NAS's Control Panel, it just won't connect, no lights, nothing.

Could anyone please advise? Thank you so much.

**Comment by 007revad** [comment]
First you need to enable using the E10M20-T1 in the DS1621+ with https://github.com/007revad/Synology_enable_M2_card 

Then the syno_hdd_db script will allow you to create a storage pool and volume on the NVMe drives in the E10M20-T1

**Comment by strikedamic** [comment]
Christ @007revad I had hoped you didn't read this so quickly so I can use your other script and delete it ... but yeah, your script worked like a charm. Can't wait to finalize the 10G connections in my house to finally get a faster connection to my NAS. Many thanks!
