### ISSUE TITLE
this is off topic 

### ISSUE THREAD

**Issue by wonderingStars** [007revad/Synology_HDD_db#352]
im asking you because you have made so many apps for synology nas . if i send you my go project for mp4 conversion for video station could you make it in to an app for the nas . i just cant see  to make an spk file . if you cant just close this i will  understand

**Comment by 007revad** [comment]
99% of my repos contain only scripts. I know just enough about creating spk files to unpack, modify and repack someone else's spk file.

Have a look at
https://github.com/007revad/ScriptNotify 
https://github.com/toafez/DSM7DemoSPK

and
https://github.com/SynoCommunity/spksrc
https://github.com/rednoah/ant-spk

I wasn't even sure that go would run on a Synology but apparently you can compile a go binary to run on a Synology.
https://www.afox.dev/posts/compiling-go-for-synology-nas

But you'd also need to compile go binaries for other CPU arch types that Synology uses like armv8 and armv7.
