### ISSUE TITLE
Two Samsung PM991a storage pool/volume successfully created but no Trim option available.

### ISSUE THREAD

**Issue by omnimax2** [007revad/Synology_HDD_db#358]
Hi after intially using the  Synology_M2_volume script, I have two sasung pm991a 1T ssd's successfully created as a raid 0 storage pool/volume in a xenology 923+ 7.2 DSM system.  But no Trim option was seen, then Synology_HDD_db script was successfully applied.  But still no Trim option is avaialbe, please help.
![IMG_20240930_081339](https://github.com/user-attachments/assets/e2b5b11f-2b93-4614-b300-a877ea43a438)
![IMG_20240930_112231](https://github.com/user-attachments/assets/554d1cf0-7b31-4f1b-8100-02be33ba6abd)

**Comment by 007revad** [comment]
DSM does not support TRIM for RAID 0 NVMe storage pools.

For NVMe storage pools TRIM is only available for SHR, SHR-2, Basic, JBOD, RAID 1, 5, 6, 10 and F1.

**Comment by omnimax2** [comment]
> DSM does not support TRIM for RAID 0 NVMe storage pools.
> 
> For NVMe storage pools TRIM is only available for SHR, SHR-2, Basic, JBOD, RAID 1, 5, 6, 10 and F1.

thanks for the reply.
