### ISSUE TITLE
Whether 1821+ supports nvme to create storage pools？

### ISSUE THREAD

**Issue by wuai1024** [007revad/Synology_HDD_db#376]
At present, my eight 3.5-inch hard disks have been used up. I want to see if 1821+ supports hard disks with two nvme slots. Can I use this script to make 1821+ support nvme to create a storage pool?

**Comment by 007revad** [comment]
Yes. I use syno_hdd_db to allow me to create a storage pool on my DS1821+'s WD NVMe drives.

**Comment by wuai1024** [comment]
> Yes. I use syno_hdd_db to allow me to create a storage pool on my DS1821+'s WD NVMe drives.

Ok, thank you very much
