### ISSUE TITLE
A Quirk I Found

### ISSUE THREAD

**Issue by Huberdoggy** [007revad/Synology_HDD_db#381]
First of all, hats off to you on this phenomenal script. Thanks to this, I was able to utilize a WD SN770 to offload some intensive IO operations from my Exos array. I appreciate the fact you include a built in switch for auto updates, as there have been other tools where I’ve had to hack my own sed/grep functionality in order to ensure a release tag is grabbed.

One thing I encountered (and possibly just a one-off DSM thing) is that after the initial reboot, I had to actually click the notification that a new M.2 was available, in order to start the wizard for new storage pool creation. At first, I attempted to manually go into storage manager to kick it off after inspecting drive details. It was very strange, since the applet correctly showed all green checkmarks and that the drive could be used as a volume. So it should have been identical to just clicking said notification as a shortcut to get there. But instead, it would alert me with “You don’t have any supported devices to create another pool etc etc…”

As mentioned, this is solved by just clicking the notification to complete the initial flow. I just wanted to make you aware of it.

**Comment by 007revad** [comment]
Interesting. Thanks.
