### ISSUE TITLE
RS1221+ and E10M20 t1 card won`t recognise samsung nvme 

### ISSUE THREAD

**Issue by hack2spider** [007revad/Synology_HDD_db#382]
Hi All, 

I used to have a 1517+ 8 bays and unknowingly I purchased the card and realised laters that this won`t work due to the pcie being incompatible  so I ended up getting an RS1221+ knowing that the card works in this ... 

I used to run 2 Nvme cache drives on the DS1517+ with another card and they were working fine with DSM 7.x however now after moving everything to RS1221+ it seems that the nvme drives aren`t recognised at all .. when I removed the drives from the DS1517+ I have unmounted the volume as prompted by DSM on shutdown so the drives weren`t just pulled out so I`m sure they are healthy .. 

I have already downloaded some of your scripts and particularly the HDD_db-main and run the scripts however the output is interesting as the script doesn`t identify the M.2 PCIe card at all .. 

vlad@Synology:~/Synology_HDD_db-main$ sudo ./syno_hdd_db.sh
Password:
Synology_HDD_db v3.5.103
RS1221+ DSM 7.2.2-72806
StorageManager 1.0.0-00502

rs1221+_host_v7 version 8046

Running from: /volume1/homes/vlad/Synology_HDD_db-main/syno_hdd_db.sh

HDD/SSD models found:

ST6000VX001-2BD186,CV12,6001 GB
WD40EFRX-68N32N0,82.00A82,4000 GB
WD60EFZX-68B3FN0,81.00A81,6001 GB

No M.2 drives found

No M.2 PCIe cards found

No Expansion Units found

So i figured I probably have to run the M.2 card script and interestingly the script doesn`t really look for the M.2 pcie card but it looks for some configuration inside the files ..

vlad@Synology:~/Synology_enable_M2_card-3.1.16$ sudo ./syno_enable_m2_card.sh
Password:
Synology_enable_M2_card v3.1.16
RS1221+ DSM 7.2.2-72806

StorageManager 1.0.0-00502

Running from: /volume1/homes/vlad/Synology_enable_M2_card-3.1.16/syno_enable_m2_card.sh
1) E10M20-T1  3) M2D18      5) ALL
2) M2D20      4) M2D17      6) Quit
Select your M.2 Card: 1

E10M20-T1 NIC already enabled for RS1221+
E10M20-T1 NVMe already enabled for RS1221+
E10M20-T1 already exists in model.dtb

Finished

It`s probably worth mentioning that the card is phisically installed and iperf returns 9.75GB so the network side of it works fine however the nvme`s are not shown even on "nvme list"

vlad@Synology:~/Synology_enable_M2_card-3.1.16$ nvmelist
-sh: nvmelist: command not found
vlad@Synology:~/Synology_enable_M2_card-3.1.16$ nvme list
vlad@Synology:~/Synology_enable_M2_card-3.1.16$

is there anything that can be done about this scenario as I can`t find any scripts relating to this type of occurence .. 

Fdisk doesn`t list anyhting either ..
 sudo fdisk -l
Disk /dev/ram0: 640 MiB, 671088640 bytes, 1310720 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram1: 640 MiB, 671088640 bytes, 1310720 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram2: 640 MiB, 671088640 bytes, 1310720 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram3: 640 MiB, 671088640 bytes, 1310720 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram4: 640 MiB, 671088640 bytes, 1310720 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram5: 640 MiB, 671088640 bytes, 1310720 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram6: 640 MiB, 671088640 bytes, 1310720 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram7: 640 MiB, 671088640 bytes, 1310720 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram8: 640 MiB, 671088640 bytes, 1310720 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram9: 640 MiB, 671088640 bytes, 1310720 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram10: 640 MiB, 671088640 bytes, 1310720 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram11: 640 MiB, 671088640 bytes, 1310720 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram12: 640 MiB, 671088640 bytes, 1310720 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram13: 640 MiB, 671088640 bytes, 1310720 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram14: 640 MiB, 671088640 bytes, 1310720 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram15: 640 MiB, 671088640 bytes, 1310720 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/sata1: 3.7 TiB, 4000787030016 bytes, 7814037168 sectors
Disk model: WD40EFRX-68N32N0
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: gpt
Disk identifier: 49AA2A57-FF46-4F08-A3CA-001A05D641EB

Device         Start        End    Sectors  Size Type
/dev/sata1p1    2048    4982527    4980480  2.4G Linux RAID
/dev/sata1p2 4982528    9176831    4194304    2G Linux RAID
/dev/sata1p3 9437184 7813832351 7804395168  3.6T Linux RAID

Disk /dev/sata2: 5.5 TiB, 6001175126016 bytes, 11721045168 sectors
Disk model: WD60EFZX-68B3FN0
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: gpt
Disk identifier: CBCC8F9D-29BC-4BED-8EA0-58C3A870C4FB

Device          Start         End     Sectors  Size Type
/dev/sata2p1     8192    16785407    16777216    8G Linux RAID
/dev/sata2p2 16785408    20979711     4194304    2G Linux RAID
/dev/sata2p3 21241856 11720840351 11699598496  5.5T Linux RAID

Disk /dev/sata3: 5.5 TiB, 6001175126016 bytes, 11721045168 sectors
Disk model: ST6000VX001-2BD186
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: gpt
Disk identifier: 09123DAB-2F76-4704-A2E9-79FE1D983038

Device          Start         End     Sectors  Size Type
/dev/sata3p1     8192    16785407    16777216    8G Linux RAID
/dev/sata3p2 16785408    20979711     4194304    2G Linux RAID
/dev/sata3p3 21241856 11720840351 11699598496  5.5T Linux RAID

Disk /dev/sata4: 5.5 TiB, 6001175126016 bytes, 11721045168 sectors
Disk model: ST6000VX001-2BD186
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: gpt
Disk identifier: 6C7E30E1-9C96-4619-9B8B-07AE586C5EFD

Device          Start         End     Sectors  Size Type
/dev/sata4p1     8192    16785407    16777216    8G Linux RAID
/dev/sata4p2 16785408    20979711     4194304    2G Linux RAID
/dev/sata4p3 21241856 11720840351 11699598496  5.5T Linux RAID

Disk /dev/sata6: 5.5 TiB, 6001175126016 bytes, 11721045168 sectors
Disk model: WD60EFZX-68B3FN0
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: gpt
Disk identifier: 59929763-F4C6-4368-9468-C813DA05FA60

Device          Start         End     Sectors  Size Type
/dev/sata6p1     8192    16785407    16777216    8G Linux RAID
/dev/sata6p2 16785408    20979711     4194304    2G Linux RAID
/dev/sata6p3 21241856 11720840351 11699598496  5.5T Linux RAID

Disk /dev/sata7: 5.5 TiB, 6001175126016 bytes, 11721045168 sectors
Disk model: WD60EFZX-68B3FN0
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: gpt
Disk identifier: C9B2C8F3-AD58-4EA8-A147-692B487FD6F7

Device          Start         End     Sectors  Size Type
/dev/sata7p1     8192    16785407    16777216    8G Linux RAID
/dev/sata7p2 16785408    20979711     4194304    2G Linux RAID
/dev/sata7p3 21241856 11720840351 11699598496  5.5T Linux RAID

Disk /dev/sata5: 5.5 TiB, 6001175126016 bytes, 11721045168 sectors
Disk model: WD60EFZX-68B3FN0
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: gpt
Disk identifier: 6C7D10C2-3E79-42E9-B634-469D6C32FCD2

Device          Start         End     Sectors  Size Type
/dev/sata5p1     8192    16785407    16777216    8G Linux RAID
/dev/sata5p2 16785408    20979711     4194304    2G Linux RAID
/dev/sata5p3 21241856 11720840351 11699598496  5.5T Linux RAID

Disk /dev/sata8: 5.5 TiB, 6001175126016 bytes, 11721045168 sectors
Disk model: ST6000VX001-2BD186
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: gpt
Disk identifier: 0627F0BA-3277-41DA-A7E6-C5419837E2CA

Device          Start         End     Sectors  Size Type
/dev/sata8p1     8192    16785407    16777216    8G Linux RAID
/dev/sata8p2 16785408    20979711     4194304    2G Linux RAID
/dev/sata8p3 21241856 11720840351 11699598496  5.5T Linux RAID

Disk /dev/md0: 2.4 GiB, 2549940224 bytes, 4980352 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/loop0: 32 MiB, 33554432 bytes, 65536 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

Disk /dev/zram0: 1.8 GiB, 1877999616 bytes, 458496 sectors
Units: sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/zram1: 1.8 GiB, 1877999616 bytes, 458496 sectors
Units: sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/zram2: 1.8 GiB, 1877999616 bytes, 458496 sectors
Units: sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/zram3: 1.8 GiB, 1877999616 bytes, 458496 sectors
Units: sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/md1: 2 GiB, 2147418112 bytes, 4194176 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

GPT PMBR size mismatch (239649 != 245759) will be corrected by write.
Disk /dev/synoboot: 120 MiB, 125829120 bytes, 245760 sectors
Disk model: DiskStation
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 1DCFBA26-4DFE-4B04-823D-0773CB7E93CB

Device         Start    End Sectors Size Type
/dev/synoboot1  2048  67583   65536  32M EFI System
/dev/synoboot2 67584 239615  172032  84M Linux filesystem

Disk /dev/md2: 25.4 TiB, 27970944827392 bytes, 54630751616 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 65536 bytes / 458752 bytes

Disk /dev/mapper/cachedev_0: 25.4 TiB, 27970944827392 bytes, 54630751616 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 65536 bytes / 458752 bytes

I don`t want to spend a fortune for the SNV enterprise nvme`s clearly.. it`s just a robbery to pay £650 sterling pounds for to sticks delivered ! 

thanks in advance for support

**Comment by 007revad** [comment]
Your old DS1517+ did not support NVMe drives. It only supported M.2 SATA SSDs in either a M2D17 or M2D18. So I believe the problem is your M.2 drives are M.2 SATA SSDs. The E10M20-T1 only works with M.2 NVMe drives.

If you buy one or two 3rd party NVMe drives DSM will detect them. When you run syno_hdd_db again it will see the NVMe drive(s) and the E10M20-T and make DSM allow you create a storage pool and volume. 
- I've got WD Black NVMe drives in 2 of NAS and they work great as a volume.
- I've also got a Silicon Power UD90 NVMe drive in another NAS that seems okay (but has bad reviews on reddit).
