### ISSUE TITLE
Disks not getting verified on a RS2821RP+

### ISSUE THREAD

**Issue by MiranoVerhoef** [007revad/Synology_HDD_db#4]
Hello!,

First and foremost thank you for the effort you've put into making this.

I ran this on my own NAS with the following hardware:
* RS2821RP+
* 4 x ST10000NM001G-2MW103

Using your script it does add them, but it keeps saying Not-verified:

![afbeelding](https://user-images.githubusercontent.com/67699857/221825204-b761eff6-bac1-4472-8acb-cabe6a0270a0.png)

**Comment by 007revad** [comment]
Was that the first you ran the script? I notice that it showed your drive model was already in the .db files. If that was the 2nd time you ran the script that would explain why your drive model was found in the .db files the 2nd time.

Can you reboot the NAS and see if it still shows the drives as not supported.

**Comment by 007revad** [comment]
If rebooting after the disk optimizing has finished doesn't solve the problem there is an updated version available that will hopefully solve your issue. 
https://github.com/007revad/Synology_HDD_db/releases/tag/V1.0.6

**Comment by MiranoVerhoef** [comment]
Hey!

The NAS finished syncing this morning so i restarted it and it seems to be working! Is it reccomended to update the script anyway?

Thank you again for all the effort put in!

**Comment by 007revad** [comment]
Excellent!

If it's working you might as well stick with the script version you have.
