### ISSUE TITLE
No Expansion Units found (of course it's wrong)

### ISSUE THREAD

**Issue by kevin39** [007revad/Synology_HDD_db#413]
Hi,
After a reboot + DSM update my expansion unit display now the warning about my non verified disks... (your script was working from a long time ago)

I updated your script, running it again and I show it display "No Expansion Units found". I think there is a bug in a recent update ? No issue for the main unit, the warning is hidden.

What do you need to debug ?
My setup is SA3410 + RX1222sas 

best regards

**Comment by kevin39** [comment]
`Synology_HDD_db v3.5.106
SA3410 DSM 7.2.2-72806-2
StorageManager 1.0.0-00502

sa3410_host_v7 version 8037

Using options: --autoupdate=1 --noupdate
Running from: /volume1/homes/xxxxx/Synology_HDD_db/syno_hdd_db.sh

[0;36mThere is a newer version of this script available.[0m
Current version: v3.5.106
Latest version: v3.5.108
Downloading v3.5.108
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
100 396k 0 396k 0 0 590k 0 --:--:-- --:--:-- --:--:-- 590k

v3.5.108 syno_hdd_db.sh and changes.txt downloaded to: /volume1/homes/xxxxx/Synology_HDD_db

-------------------------------------------------------------------------------
Synology_HDD_db v3.5.108
SA3410 DSM 7.2.2-72806-2
StorageManager 1.0.0-00502

sa3410_host_v7 version 8037

Using options: --autoupdate=1 --noupdate
Running from: /volume1/homes/xxxxx/Synology_HDD_db/syno_hdd_db.sh

HDD/SSD models found: 2
ST18000NM000J-2TV103,SN02,18000 GB
ST18000NM000J-2TV103,SN04,18000 GB

M.2 drive models found: 1
SNV3510-800G,ECEM13.2,800 GB

M.2 PCIe card models found: 1
M2D20

No Expansion Units found

Updated [0;33mST18000NM000J-2TV103[0m in [0;36msa3410_host_v7.db[0m
Updated [0;33mST18000NM000J-2TV103[0m in [0;36msa3410_host_v7.db[0m
[0;33mSNV3510-800G[0m already exists in [0;36msa3410_host_v7.db[0m
[0;33mSNV3510-800G[0m already exists in [0;36msa3410_m2d20_v7.db[0m
[0;33mSNV3510-800G[0m already exists in [0;36msa3410_m2d20_v7.db.new[0m

[0;33mM2D20 NVMe[0m already enabled for [0;36mSA3410[0m
[0;33mM2D20[0m already exists in [0;36mmodel.dtb[0m

Support disk compatibility already enabled.

Support memory compatibility already enabled.

NVMe support already enabled.

M.2 volume support already enabled.

Drive db auto updates already disabled.

Creating pool in UI on drives in M.2 adaptor card already enabled.

DSM successfully checked disk compatibility.`

**Comment by 007revad** [comment]
There was a change in v3.5.102 related to detecting expansion units.
> Changed to use a faster method of detecting if an expansion unit is connected, for models with the syno_slot_mapping command.

The SA3410 does have the syno_slot_mapping command so the script would be using the faster method of detecting expansion units.

What does this command return?
```
sudo syno_slot_mapping | grep 'Eunit port' | awk '{print $5}'
```
If that returns nothing can you tell me what this command returns: 
```
sudo syno_slot_mapping
```

**Comment by kevin39** [comment]
Hi,

```
ash-4.4# syno_slot_mapping | grep 'Eunit port' | awk '{print $5}'
ash-4.4# syno_slot_mapping
System Disk
Internal Disk
01: /dev/sas12
02: /dev/sas6
03: /dev/sas3
04: /dev/sas11
05: /dev/sas5
06: /dev/sas8
07: /dev/sas2
08: /dev/sas10
09: /dev/sas4
10: /dev/sas1
11: /dev/sas7
12: /dev/sas9

Esata port count: 0
USB Device
01:
02:

PCIe Slot 1: M2D20
01: /dev/nvme1n1
02: /dev/nvme0n1
```

**Comment by 007revad** [comment]
So syno_slot_mapping does not work for SAS expansion units.

Does this find the drives in your expansion unit(s)?
```
sudo synodisk --enum -t ebox
```

**Comment by kevin39** [comment]
```
ash-4.4# synodisk --enum -t ebox
************ Disk Info ***************
>> Disk id: 9
>> Slot id: -1
>> Disk path: /dev/sas13
>> Disk model: ST18000NM000J-2TV103
>> Total capacity: 16764.00 GB
>> Tempeture: 32 C
************ Disk Info ***************
>> Disk id: 5
>> Slot id: -1
>> Disk path: /dev/sas14
>> Disk model: ST18000NM000J-2TV103
>> Total capacity: 16764.00 GB
>> Tempeture: 34 C
************ Disk Info ***************
>> Disk id: 2
>> Slot id: -1
>> Disk path: /dev/sas15
>> Disk model: ST18000NM000J-2TV103
>> Total capacity: 16764.00 GB
>> Tempeture: 35 C
************ Disk Info ***************
>> Disk id: 1
>> Slot id: -1
>> Disk path: /dev/sas16
>> Disk model: ST18000NM000J-2TV103
>> Total capacity: 16764.00 GB
>> Tempeture: 33 C
************ Disk Info ***************
>> Disk id: 12
>> Slot id: -1
>> Disk path: /dev/sas17
>> Disk model: ST18000NM000J-2TV103
>> Total capacity: 16764.00 GB
>> Tempeture: 32 C
************ Disk Info ***************
>> Disk id: 8
>> Slot id: -1
>> Disk path: /dev/sas18
>> Disk model: ST18000NM000J-2TV103
>> Total capacity: 16764.00 GB
>> Tempeture: 35 C
************ Disk Info ***************
>> Disk id: 4
>> Slot id: -1
>> Disk path: /dev/sas19
>> Disk model: ST18000NM000J-2TV103
>> Total capacity: 16764.00 GB
>> Tempeture: 35 C
************ Disk Info ***************
>> Disk id: 3
>> Slot id: -1
>> Disk path: /dev/sas20
>> Disk model: ST18000NM000J-2TV103
>> Total capacity: 16764.00 GB
>> Tempeture: 34 C
************ Disk Info ***************
>> Disk id: 11
>> Slot id: -1
>> Disk path: /dev/sas21
>> Disk model: ST18000NM000J-2TV103
>> Total capacity: 16764.00 GB
>> Tempeture: 33 C
************ Disk Info ***************
>> Disk id: 10
>> Slot id: -1
>> Disk path: /dev/sas22
>> Disk model: ST18000NM000J-2TV103
>> Total capacity: 16764.00 GB
>> Tempeture: 32 C
************ Disk Info ***************
>> Disk id: 7
>> Slot id: -1
>> Disk path: /dev/sas23
>> Disk model: ST18000NM000J-2TV103
>> Total capacity: 16764.00 GB
>> Tempeture: 36 C
************ Disk Info ***************
>> Disk id: 6
>> Slot id: -1
>> Disk path: /dev/sas24
>> Disk model: ST18000NM000J-2TV103
>> Total capacity: 16764.00 GB
>> Tempeture: 34 C
ash-4.4#
```

**Comment by 007revad** [comment]
I'll release a new version with a fix in a few hours and reply back.

**Comment by 007revad** [comment]
Try [v3.6.110](https://github.com/007revad/Synology_HDD_db/releases/tag/v3.6.110)

**Comment by kevin39** [comment]
Thank you, your fix works. Good job !
