### ISSUE TITLE
Reboot not necessary on db change

### ISSUE THREAD

**Issue by mh-muc** [007revad/Synology_HDD_db#5]
The reboot on changing the drive db is not necessary, just execute this and the drive db will be reloaded:

/usr/syno/sbin/synostgdisk --check-all-disks-compatibility

**Comment by 007revad** [comment]
Very nice. Thank you.

**Comment by 007revad** [comment]
I notice that that would work in DSM 6 but I'm not sure about DSM 7

In DSM 6 "synostgdisk --help" returns: 
`--check-all-disks-compatibility check all disk compatibility info.`

In DSM 7 "synostgdisk --help" returns: 
```
--get-dump      get the disk dump info.
--disk-activate <DISK_PATH>     activate a deactivated disk, only for debug.
--disk-deactivate <DISK_PATH>   deactivate the disk.
```

**Comment by mh-muc** [comment]
For me ist is working well with DSM 7.1.1-42962 Update 4  on RS2421+
