### ISSUE TITLE
Synology DSM 7.1.1-42962 Update 5 compatibility


### ISSUE THREAD

**Issue by aferende** [007revad/Synology_HDD_db#54]
Hi Dave,
could you please verify script compatibility with the new update 5 of DSM 7.1?

https://www.synology.com/en-global/releaseNote/DSM

**Comment by 007revad** [comment]
I don't see anything in the release notes that suggest the script wouldn't be compatible.

To test it myself would require downgrading from DSM 7.2 beta to DSM 7.1.1 update 5.

**Comment by aferende** [comment]
I have installed update 5.
Script run without any issue.
Top!
