### ISSUE TITLE
WD-SN850x NvME SSD's not found?

### ISSUE THREAD

**Issue by quadcom** [007revad/Synology_HDD_db#55]
Hey all.

I ran the script and the system still cannot see the 2 WD-SN850x NvME drives installed in order to create a cache pool.

Any ideas?

```
Synology_HDD_db v2.0.35
DS1522+ DSM 7.1.1-42962-4

HDD/SSD models found: 2
ST10000VN0004-1ZD101,SC60
ST14000NM001G-2KJ103,SN03

No M.2 drives found

No M.2 cards found

No Expansion Units found

ST10000VN0004-1ZD101 already exists in ds1522+_host_v7.db
ST10000VN0004-1ZD101 already exists in ds1522+_host_v7.db.new
ST14000NM001G-2KJ103 already exists in ds1522+_host_v7.db
ST14000NM001G-2KJ103 already exists in ds1522+_host_v7.db.new

Disabled support memory compatibility.

Disabled drive db auto updates.

    "ST10000VN0004-1ZD101": {
      "SC60": {
        "compatibility_interval": [
          {
            "compatibility": "support",
            "not_yet_rolling_status": "support",
            "fw_dsm_update_status_notify": false,
            "barebone_installable": true
          }
        ]
      },
      "default": {

    "ST14000NM001G-2KJ103": {
      "SN03": {
        "compatibility_interval": [
          {
            "compatibility": "support",
            "not_yet_rolling_status": "support",
            "fw_dsm_update_status_notify": false,
            "barebone_installable": true
          }
        ]
      },
      "default": {

DSM successfully checked disk compatibility.

```

![image](https://user-images.githubusercontent.com/7085931/231602107-9414f65f-dd6d-408b-b4b5-e5bfd585559d.png)

![image](https://user-images.githubusercontent.com/7085931/231602221-ca23aed4-ef9c-43f7-9785-25794c545e61.png)

![image](https://user-images.githubusercontent.com/7085931/231602352-4a5ecf26-ff06-4ba1-8d48-ff74c1729140.png)

**Comment by 007revad** [comment]
What does the following command return:
`for d in /sys/block/nvme*; do echo $d; done`

It should returns **/sys/block/nvme0n1** and **/sys/block/nvme1n1**

If it did see what these commands return:
`cat /sys/block/nvme0n1/device/model`

`cat /sys/block/nvme1n1/device/model`

`cat /sys/block/nvme0n1/device/firmware_rev`

`cat /sys/block/nvme1n1/device/firmware_rev`

**Comment by quadcom** [comment]
Hmmmm,

not in my case

```
XXXXX@DS1522:/$ for d in /sys/block/nvme*; do echo $d; done
/sys/block/nvme*
XXXXX@DS1522:/$
```

**Comment by quadcom** [comment]
I shut down the system and restarted it. When it came back up, slot 2 found the SSD. But not slot 1.

I then shut down the system to check slot 1  in case I somehow screwed up seating the drive. But I reseated slot 2 first by accident. I then reseated slot 1, plugged in power, and fired it back up.

Now it doesn't see either SSD installed again!

**Comment by quadcom** [comment]
I had a thought, because I was SSH with my user account on the NAS, I tried to sudo the command. But when I do that, it fails.

```
@DS1522:/$ sudo for d in /sys/block/nvme*; do echo $d; done
-sh: syntax error near unexpected token `do'

```

**Comment by quadcom** [comment]
```
XXXX@DS1522:/sys/block$  ls -a
.     dm-1   loop1  loop4  loop7  md2   ram1   ram12  ram15  ram4  ram7  sata1  sata4     zram0
..    dm-2   loop2  loop5  md0    md3   ram10  ram13  ram2   ram5  ram8  sata2  sata5     zram1
dm-0  loop0  loop3  loop6  md1    ram0  ram11  ram14  ram3   ram6  ram9  sata3  synoboot
XXXX@DS1522:/sys/block$
```

**Comment by quadcom** [comment]
A long shot, but do you know if a RAM requirement exists for NvME drives to become available? I have the stock 8GB. I never planned on running any containers or apps. This is strictly a file server for video media so I didn't see the need for more RAM.

**Comment by 007revad** [comment]
> @DS1522:/$ sudo for d in /sys/block/nvme*; do echo $d; done
> -sh: syntax error near unexpected token `do'

sudo doesn't like the for command so you need to do this:
sudo sh -c 'for d in /sys/block/nvme*; do echo $d; done'

But it probably won't make a difference to the result you're getting.

**Comment by 007revad** [comment]
> do you know if a RAM requirement exists for NvME drives to become available?

Not that I'm aware of. Memory requirements only seem to be for volumes larger than 108TB or when using deduplication or LUNs etc. 

I would try reseating the NVMe drives again. When I upgraded the memory on my DS1821+ I had to reseat the memory twice before it would boot up. And maybe try just 1 NVMe drive at a time to determine if one of the drives is faulty or if one of the M.2 slots is faulty.

**Comment by 007revad** [comment]
Have these NVMe drives been used in something else before you installed them in the Synology?

In the past I've installed drives that had been used in a PC and DSM ignored the drives as if they didn't exist. I had to put the drives back in a PC and delete all partitions on the drives. After that DSM saw the drives.

**Comment by quadcom** [comment]
These two were brand new out of the box. 

It's too bad we can't see in the bios of the MB to see what hardware it sees. I held Synology in high regard after I bought my DS1515+. But this experience, with overly restricting media is pissing me off!

Thinking I should have built my own TruNas box instead!
