### ISSUE TITLE
SSD Volume Support in older NAS models

### ISSUE THREAD

**Issue by jakemauer** [007revad/Synology_HDD_db#61]
Hi Dave, 

First thanks for writing and maintaining this script. I have a DS1019+ with two 512gb M.2 SSDs that I had been using as a RAID1 volume. I set up the volume via the commandline using instructions that I found on Reddit and it has been performing just fine. 

I found this script today and decided to give it a shot to see if I could create an SSD storage Volume via the DSM. I deleted my existing volume and ran the script, then rebooted, however the DSM is still saying that I can't create a storage pool because I don't have any drives that meet the requirements. 

Is creating SSD storage volumes in "unsupported" older NAS models actually a thing this script should allow or have I misunderstood? 

Here's what I see in the drive requirements modal window: 
<img width="778" alt="image" src="https://user-images.githubusercontent.com/361568/233216201-9d283d44-8d11-4a48-a9fe-54385633fb32.png">

Thanks for your time!

**Comment by 007revad** [comment]
The M.2 volume part of the Synology_HDD_db script only seems to work on newer models. I do have another script that works on all models with DSM 7.1.1 or newer.
https://github.com/007revad/Synology_M2_volume

**Comment by jakemauer** [comment]
oh wow I didn't realize you had that separate script. Thank you!
