### ISSUE TITLE
double free or corruption (out)

### ISSUE THREAD

**Issue by jk7gr** [007revad/Synology_HDD_db#64]
Dear @007revad ,
I wanted to test your script on my DS918+ NAS running DSM 7.1.1-42962 Update 5.

Unfortunately, it doesn't like it. I am getting a "double free or corruption (out)" message and I don't know what it is.
I have exactly the same error message with your other script "syno_create_m2_volume.sh" as well.

example below: 
$ sudo -i /volume1/docker/syno_hdd_db.sh -h
Password:
double free or corruption (out)
Aborted

**Comment by jk7gr** [comment]
I appreciate the immediate response. 
No joy,
I am using Putty on a Win11 machine.
I am pasting the output of the terminal:


synoadmin@ds918:~$ sudo -i
Password:
root@ds918:~#
root@ds918:~# chmod u+x /volume1/docker/syno_hdd_db.sh
root@ds918:~# /volume1/docker/syno_hdd_db.sh -h
double free or corruption (out)
Aborted (core dumped)
root@ds918:~#

**Comment by 007revad** [comment]
That error message 
double free or corruption (out)
Aborted (core dumped)
means that the something tried to twice to free the same block of memory, or that something in memory was overwritten that shouldn't have been. But the script hasn't even started when that error ocurred.

Are you able to run other scripts? Any script?

Even one that just contains:
```
#!/usr/bin/env bash
echo "Hello world"
```
What does the following command return:
`free -m`

**Comment by jk7gr** [comment]
You are right... I cannot run any script...
Very strange. I used to be able to, but it seems not anymore. Any idea what should be looking at?
the extract of free -m is below. I don't know if is good or bad
![image](https://user-images.githubusercontent.com/17036347/234301995-612e715c-f73a-4beb-9595-9eb1647fea73.png)

**Comment by jk7gr** [comment]
> You are right... I cannot run any script... Very strange. I used to be able to, but it seems not anymore. Any idea what should be looking at? the extract of free -m is below. I don't know if is good or bad ![image](https://user-images.githubusercontent.com/17036347/234301995-612e715c-f73a-4beb-9595-9eb1647fea73.png)

I managed to understand and troubleshoot.
I simply changed the first line of your script 

from:
#!/usr/bin/env bash

to:
#!/bin/bash

After that it worked. I don't know what this really means. :)

**Comment by 007revad** [comment]
That means your environment variables are messed up (at least for your user account). Maybe when you update to DSM 7.2 it will fix them - or maybe not :)

If you're curious, what do these 2 commands return:
`echo $PATH`

`env`
