### ISSUE TITLE
Samsung 970 listed as incompatible on 1621+ when trying to create storage pool

### ISSUE THREAD

**Issue by MarkErik** [007revad/Synology_HDD_db#7]
<img width="747" alt="Screen Shot 2023-03-09 at 5 16 48 PM" src="https://user-images.githubusercontent.com/23254168/224172747-12ba0cac-39aa-44eb-b895-03d772323f19.png">

I've run the script (and tried running it again):
```
Samsung SSD 970 EVO Plus 2TB already exists in ds1621+_host_v7.db
Samsung SSD 970 EVO Plus 2TB already exists in ds1621+_host_v7.db.new
```

Is there a different database that gets checked for the new feature in DSM 7.2 where creating storage pools from NVME drives is supported in the 1621+?

**Comment by 007revad** [comment]
This is actually something I can test myself as I have a DS1821+. I was reluctant to try DSM 7.2 beta but I now I have a reason to try it to see how Synology is blocking 3rd party NVMe drives. It might take me a few days to figure out.

**Comment by linguowei** [comment]
@007revad Looking forward to your test results

**Comment by MarkErik** [comment]
@007revad I wanted to ask whether in the ReadMe when it says: 
_Bypass_ unsupported M.2 drives for use as volumes in DSM 7.2 (for models that supported M.2 volumes).
Do you mean "Allow"?

**Comment by 007revad** [comment]
Yes.

**Comment by ctrlaltdelete007** [comment]
Maybe this should be added:
/etc.default/synoinfo.conf

the following parameter has to be changed to "yes"

support_m2_pool="no"

**Comment by 007revad** [comment]
support_m2_pool="yes" is already set on models that support M.2 volumes. And on models that don't officially support M.2 volumes my script sets it to yes, or adds the line if it's missing.

**Comment by 007revad** [comment]
I've written another script that creates the storage pool for you and you can then go into DSM, select Online assemble and then create the volume (without any stupid warnings from DSM).

https://github.com/007revad/Synology_M2_volume

**Comment by 007revad** [comment]
> enabling storage pool is not synlogy with ssd: https://xpenology.com/forum/topic/67961-use-nvmem2-hard-drives-as-storage-pools-in-synology/

Unfortunately that didn't work on my DS1821+ with DSM 7.2 beta.

**Comment by inkpool** [comment]
Do you still have a plan to support 3rd party NVMe SSD creating Volume with GUI?

**Comment by 007revad** [comment]
@inkpool Sorry, I didn't see your comment until just now.

I've written another script that enables creating M.2 storage pools and volumes all from within Storage Manager.
https://github.com/007revad/Synology_enable_M2_volume 

And also another script that does exactly the same as Synology_enable_M2_volume but also enables Data Deduplication on any brand SSDs, even on unsupported models.
https://github.com/007revad/Synology_enable_Deduplication

Using Data Deduplication from the GUI is very cool. I hope to be able to make it work on HDDs as well.

**Comment by 007revad** [comment]
`echo 1 > /run/synostorage/disks/nvme0n1/m2_pool_support`

I've seen this mentioned a month ago on both synology-forum.de and xpenology.com and again a week ago here on reddit, but the comments were always short and vague.

Your comment has it clear to me now. Thank you.

**Comment by 007revad** [comment]
@inkpool @ctrlaltdelete007 @linguowei @MarkErik 

v2.0.35 just released and now, thanks to @nicolerenee, allows creating the storage pool and volume from Storage Manager, for any M.2 drive(s).

**Comment by 007revad** [comment]
@nicolerenee What Synology model do you have and which DSM version are running?

**Comment by hawie** [comment]
/usr/syno/sbin/synostgdisk missing, any idea?
Msg:
Synology_HDD_db v2.0.35
DS918+ DSM 6.2.3-25426-3 

HDD/SSD models found: 1
CT2000MX500SSD1,033

M.2 drive models found: 1
SanDisk Ultra 3D NVMe,21705000

No M.2 cards found

No Expansion Units found

Backed up ds918+_host.db
Added CT2000MX500SSD1 to ds918+_host.db
Added CT2000MX500SSD1 to ds918+_host.db.new
Added SanDisk Ultra 3D NVMe to ds918+_host.db
Added SanDisk Ultra 3D NVMe to ds918+_host.db.new

Backed up synoinfo.conf

Re-enabled support disk compatibility.

Enabled M.2 volume support.

Disabled drive db auto updates.
**./syno_hdd_db.sh: line 1016: /usr/syno/sbin/synostgdisk: No such file or directory**

You may need to reboot the Synology to see the changes.

**Comment by hawie** [comment]
> /usr/syno/sbin/synostgdisk missing, any idea? Msg: Synology_HDD_db v2.0.35 DS918+ DSM 6.2.3-25426-3
> 
> HDD/SSD models found: 1 CT2000MX500SSD1,033
> 
> M.2 drive models found: 1 SanDisk Ultra 3D NVMe,21705000
> 
> No M.2 cards found
> 
> No Expansion Units found
> 
> Backed up ds918+_host.db Added CT2000MX500SSD1 to ds918+_host.db Added CT2000MX500SSD1 to ds918+_host.db.new Added SanDisk Ultra 3D NVMe to ds918+_host.db Added SanDisk Ultra 3D NVMe to ds918+_host.db.new
> 
> Backed up synoinfo.conf
> 
> Re-enabled support disk compatibility.
> 
> Enabled M.2 volume support.
> 
> Disabled drive db auto updates. **./syno_hdd_db.sh: line 1016: /usr/syno/sbin/synostgdisk: No such file or directory**
> 
> You may need to reboot the Synology to see the changes.

works fine with 7.2 beta.

**Comment by MarkErik** [comment]
I wanted to share that using the script I was able to create a Storage Pool in the Synology GUI for my Samsung 970 EVO PLUS in the 7.2 Beta. Being able to have it recognized as an officially supported drive is great because then I could also enable file encryption for the Volume.

However...

For anyone else who has also created a SSD volume in 7.2 - does it seem like it is less performant than what you would expect?

In my 1621+ (32GB RAM) I have a 2TB Samsung 970 EVO PLUS as an encrypted volume, and a 6x14TB WD RAID10, with a 20TB encrypted volume.

If I run the ATTO Benchmark, the RAID10 is getting higher IOPS (almost 2x) for the small file sizes than the SSD. Maybe I am mistaken, but I thought that the SSD would be much better.

Here's the charts (look at the scale on the left):

This is for the SSD
<img width="1117" alt="Screen Shot 2023-04-14 at 10 22 49 AM" src="https://user-images.githubusercontent.com/23254168/232072484-becba01f-835f-4e78-afba-d0da3ed0d0b1.png">

This is for the RAID10
<img width="1118" alt="Screen Shot 2023-04-14 at 10 14 17 AM" src="https://user-images.githubusercontent.com/23254168/232072576-bb2b0445-9ee3-492d-b547-5477ad76f5c0.png">

Also, I am seeing some strange dips on the disk writes, and the reads look messy in the AJA 64GB test for the SSD
<img width="916" alt="Screen Shot 2023-04-14 at 10 28 16 AM" src="https://user-images.githubusercontent.com/23254168/232072826-77176ad6-b6d5-4be9-97fb-374f8218783e.png">

Compared to the more consistent writes on the RAID10
<img width="914" alt="Screen Shot 2023-04-14 at 10 35 55 AM" src="https://user-images.githubusercontent.com/23254168/232074637-bbaf501c-cb8a-4a4c-b9de-7365b3137e96.png">

**Comment by 007revad** [comment]
@MarkErik I've not seen any real benefit from using NVMe drives as a volume or a cache. 

But I'd actually be really happy if I was getting your read and write speeds on my DS1821+. With 32G of ECC memory and a E10G18-T1 10G card I only get 410 MB/s writes and 280 MB/s reads.

DS1821+ AJA 64GB test for a WD Black SN770 NVMe (no encryption or data checksums).
![image](https://user-images.githubusercontent.com/39733752/232288485-5d05201e-b5e9-4c1d-859b-12ac20340d9f.png)

DS1821+ AJA 64GB test for a 4x 16TB Ironwolf SHR array (no encryption and each drive's write cache disabled).
![image](https://user-images.githubusercontent.com/39733752/232288466-3838cc31-6572-4063-8a0b-9cf9a182f4e6.png)

**Comment by MarkErik** [comment]
@007revad Interesting about your speeds, especially the NVME, since we have nearly the same NAS hardware configuration (same amount of RAM, same 10G card).

A few points about my config at the moment is that the RAID10 (6 x shucked 14TB WD USB drives that turned out to be WD140EDGZ) is empty, so my read and write speeds are ideal. At the moment I also don't have any other services running on my NAS.

Your SHR write speeds seems quite good, from many comments indicating that SHR write speed is typically that of a single drive. But in the same vein, reads where meant to be N-1 speed of the number of drives, so something looks a bit off on that for you.

What I've noticed is that the SSD volume seems to perform best right after a reboot, whereas the RAID10 performs similar regardless.

I found some benchmark numbers from testing on the previous version of DSM (7.1), using Blackmagic, comparing the command-line created SSD volume, to the RAID10 - and using a 3GB file (so that it would supposedly cache the entire operation in RAM), the SSD volume performed about 100MB/s slower than the RAID10. But then after a reboot, the SSD performed better.

So across different DSM versions, with and without encryption, the SSD volume seems to be more temperamental.

I have a 500GB Samsung 970 EVO PLUS in the second slot that I was going to use as a cache drive for the RAID10, but I'll test it today as a volume, to see how it behaves performance-wise.

**Comment by inkpool** [comment]
I did some tests, the performance of NVMe volume is not significant better than HDD volume. I have a SN570 NVMe RAID0 and a HDD RAID 5. So disappointed.

**Comment by inkpool** [comment]
The single drive, raid1 and raid0 of NVMe volume did not show much difference. 

One good thing is we could achieve nearly 8-drive HDD RAID5 performance with a single NVMe drive.

**Comment by MarkErik** [comment]
FYI: No problems doing the upgrade from 7.2 Beta to 7.2 RC. All the SSD volumes that I had created were still there working fine.
