### ISSUE TITLE
Script Command Not Found

### ISSUE THREAD

**Issue by shiphted** [007revad/Synology_HDD_db#75]
I downloaded the tar file to /volume1/scripts/Synology_HDD_db-2.2.45/syno_hdd_db.sh

I am on an RS2423+ on the newest firmware

I used the command 
sudo /volume1/scripts/Synology_HDD_db-2.2.45/syno_hdd_db.sh -nr

Error I get:
sudo: /volume1/scripts/Synology_HDD_db-2.2.45/syno_hdd_db.sh: command not found

Any reason why or is it just something I'm doing wrong?

**Comment by 007revad** [comment]
You need to replace /volume1/scripts/ with the volume and folder where the script is located on your Synology.

**Comment by shiphted** [comment]
Interesting. Ill try to figure that out as I just ssh'ed in and su root.

**Comment by shiphted** [comment]
> You need to replace /volume1/scripts/ with the volume and folder where the script is located on your Synology.

So when I am in the directory of the file and i issue pwd command it shows the same path as listed above. Its gotta be something simple im missing.

**Comment by 007revad** [comment]
So you do have the script in a shared folder named scripts on volume1

What does the following command return: `ls /volume1/scripts/`

**Comment by shiphted** [comment]
I figured it out. I ended up uploading the script rather than wget from ssh.
