### ISSUE TITLE
ERROR 6a Failed to update ds1821+_host_v7.db

### ISSUE THREAD

**Issue by very-old-guy** [007revad/Synology_HDD_db#77]
Trying to update the drive listing and I get this error message.  

Synology_HDD_db v2.2.45
DS1821+ DSM 7.2-64551 RC
Using options: -nr

HDD/SSD models found: 6
CT2000BX500SSD1,061
CT2000MX500SSD1,033
WD80EFAX-68KNBN0,0A81
WD80EFAX-68LHPN0,0A83
WD80EFBX-68AZZN0,0A85
WD80EFZX-68UW8N0,0A83

M.2 drive models found: 2
KINGSTON SA2000M8/1000G,V0304B0
SA2000M8/1TB,T1103F0L

No M.2 cards found

No Expansion Units found

CT2000BX500SSD1 already exists in ds1821+_host_v7.db
CT2000MX500SSD1 already exists in ds1821+_host_v7.db
WD80EFAX-68KNBN0 already exists in ds1821+_host_v7.db
WD80EFAX-68LHPN0 already exists in ds1821+_host_v7.db
WD80EFBX-68AZZN0 already exists in ds1821+_host_v7.db
WD80EFZX-68UW8N0 already exists in ds1821+_host_v7.db
sed: -e expression #1, char 33: unknown option to `s'

ERROR 6a Failed to update ds1821+_host_v7.db
sed: -e expression #1, char 21: unknown option to `s'

ERROR 6a Failed to update ds1821+_host_v7.db

Support disk compatibility already enabled.

Support memory compatibility already disabled.

Max memory already set to 32 GB.

M.2 volume support already enabled.

Drive db auto updates already disabled.

DSM successfully checked disk compatibility.

**Comment by 007revad** [comment]
It looks like it's the / in the NVMe drives' model names that's causing the error. 
KINGSTON SA2000M8**/**1000G
SA2000M8**/**1TB

They both appear to be 1TB Kingston SA2000M8 so I'm curious why their returning different model names. 

I'll run some tests to reproduce the error so I can fix it.

**Comment by 007revad** [comment]
Can you try this pre-release version and confirm if it fixes your issue.

https://github.com/007revad/Synology_HDD_db/releases/tag/v2.2.46

**Comment by very-old-guy** [comment]
Thank you.  I am going to reply to this in two parts as I have been having one of the NVMe drives fail and the volume fall over.  I have removed one that I think is a problem and it was added to the database ok.  I will reinstall the second one and see what happens from there to see if the issue with failure was somehow related to the unrecognised drive.  Here is the results from the first run.  I will also update to full version of 7.2 before doing the second one.

Synology_HDD_db v2.2.47
DS1821+ DSM 7.2-64551 RC
Using options: 

HDD/SSD models found: 6
CT2000BX500SSD1,061
CT2000MX500SSD1,033
WD80EFAX-68KNBN0,0A81
WD80EFAX-68LHPN0,0A83
WD80EFBX-68AZZN0,0A85
WD80EFZX-68UW8N0,0A83

M.2 drive models found: 1
SA2000M8/1TB,T1103F0L

No M.2 cards found

No Expansion Units found

CT2000BX500SSD1 already exists in ds1821+_host_v7.db
CT2000MX500SSD1 already exists in ds1821+_host_v7.db
WD80EFAX-68KNBN0 already exists in ds1821+_host_v7.db
WD80EFAX-68LHPN0 already exists in ds1821+_host_v7.db
WD80EFBX-68AZZN0 already exists in ds1821+_host_v7.db
WD80EFZX-68UW8N0 already exists in ds1821+_host_v7.db
Added SA2000M8/1TB to ds1821+_host_v7.db

Support disk compatibility already enabled.

Support memory compatibility already enabled.

M.2 volume support already enabled.

Drive db auto updates already enabled.

DSM successfully checked disk compatibility.

You may need to reboot the Synology to see the changes.

**Comment by very-old-guy** [comment]
HI,

Found and successfully added the second drive.  Unfortunately did not fix my failure issue.  Thank you for your assistance.
