### ISSUE TITLE
Syntax Error?

### ISSUE THREAD

**Issue by Inch-high** [007revad/Synology_HDD_db#8]
/volume1/homes/name/syno_hdd_db.sh -showedits
/volume1/homes/name/syno_hdd_db.sh: line 8: syntax error near unexpected token `newline'

/volume1/homes/name/syno_hdd_db.sh: line 8: !DOCTYPE html

Am I doing something wrong? I'm trying to run this on an RS3618xs. 

Cheers!

**Comment by 007revad** [comment]
Did you edit the syno_hdd_db.sh file in notepad?

Or did you download the github webpage?

You should download the script via one of the 3 links shown in this picture:
![git_release_download](https://user-images.githubusercontent.com/39733752/224510234-fdd424c9-2a8d-4207-b305-60b9c5a677b3.png)

**Comment by Inch-high** [comment]
Yep I'm an idiot... not sure why I didn't do that (i normally download from releases). Sorry!
