### ISSUE TITLE
Before the upgrade, I used NVME through SSH to upgrade the storage space. After restarting, it became unusable and the display version was not supported. Can I still recover through this script? Is all the data present after the recovery thanks

### ISSUE THREAD

**Issue by alongty** [007revad/Synology_HDD_db#83]

**Comment by 007revad** [comment]
If you run this script it won't make this any worse.

Run the script and reboot the NAS. Then check in storage manager if it shows a link to do an "Online Assemble".

**Comment by alongty** [comment]
After using this script, everything has returned to normal. Thank you  respect
