### ISSUE TITLE
Lost access to Storage Manager on DSM 7.2-64561 (DS923+)

### ISSUE THREAD

**Issue by fish-2023** [007revad/Synology_HDD_db#84]
Hi, 

I have ran the syno_hdd_db.sh script on my DS923+ and after reboot I still couldn't create an M2 storage pool. I have then run the script again to restore the previous settings before trying anything else. After another reboot the Storage Manager was gone.
This seems similar to #73 but on the final version of 7.2.

The model is missing within the Info Center: https://imgur.com/a/B8SV4WU

I run get_syno_model.sh and this is the output:
```
unamee:
synology_r1000_923+

/etc/synoinfo.conf unique:
synology_r1000_923+

/etc.defaults/synoinfo.conf unique:
synology_r1000_923+

/etc/synoinfo.conf upnpmodelname:
DS923+

/etc.defaults/synoinfo.conf upnpmodelname:
DS923+

/proc/cmdline syno_hw_version:
DS923+

/rpco/sys/kernel syno_hw_version:
DS923+
```

I have also checked to see if the config file was corrupt in some way, but this is the only thing diff could see:
```
max-admin@SynologyNAS:~$ sudo diff syno_conf_after_first_attempt.txt /etc.defaults/synoinfo.conf
Password: 
204c204
< support_memory_compatibility="no"
---
> support_memory_compatibility="yes"
328a329
> 

```

I have tried the "Restore DSM configurations" from the "Update & Restore" menu but that didn't help...

Do you have any pointers on how to fix my config?
Thank you

**Comment by fish-2023** [comment]
As an additional note, these are the times I have ran the script.
If I remember correctly, after the restore and the reboot, the Storage Manager was still there.
The 3rd run was to include the "-n" since I thought the first run might have not worked because of that. I hope this is helpful.


1. sudo ./syno_hdd_db.sh --ram --showedits
```
Synology_HDD_db v2.2.47
DS923+ DSM 7.2-64561 
Using options: --ram --showedits

HDD/SSD models found: 3
ST4000VN000-1H4168,SC44
ST8000VN004-2M2101,SC60
ST8000VN004-3CP101,SC60

M.2 drive models found: 1
CT1000P3PSSD8,P9CR40A

No M.2 cards found

No Expansion Units found

Backed up ds923+_host_v7.db.new
Added ST4000VN000-1H4168 to ds923+_host_v7.db
Added ST4000VN000-1H4168 to ds923+_host_v7.db.new
Added ST8000VN004-2M2101 to ds923+_host_v7.db
Added ST8000VN004-2M2101 to ds923+_host_v7.db.new
ST8000VN004-3CP101 already exists in ds923+_host_v7.db
ST8000VN004-3CP101 already exists in ds923+_host_v7.db.new
Added CT1000P3PSSD8 to ds923+_host_v7.db
Added CT1000P3PSSD8 to ds923+_host_v7.db.new

Backed up synoinfo.conf

Support disk compatibility already enabled.

Disabled support memory compatibility.

Max memory already set to 32 GB.

M.2 volume support already enabled.

Drive db auto updates already enabled.

    "ST4000VN000-1H4168": {
      "SC44": {
        "compatibility_interval": [
          {
            "compatibility": "support",
            "not_yet_rolling_status": "support",
            "fw_dsm_update_status_notify": false,
            "barebone_installable": true
          }
        ]
      },
      "default": {

    "ST8000VN004-2M2101": {
      "SC60": {
        "compatibility_interval": [
          {
            "compatibility": "support",
            "not_yet_rolling_status": "support",
            "fw_dsm_update_status_notify": false,
            "barebone_installable": true
          }
        ]
      },
      "default": {

    "ST8000VN004-3CP101": {
      "SC60": {
        "compatibility_interval": [
          {
            "compatibility": "support",
            "not_yet_rolling_status": "support",
            "fw_dsm_update_status_notify": false,
            "barebone_installable": true,
            "smart_test_ignore": false,
            "smart_attr_ignore": false
          }
        ]

    "CT1000P3PSSD8": {
      "P9CR40A": {
        "compatibility_interval": [
          {
            "compatibility": "support",
            "not_yet_rolling_status": "support",
            "fw_dsm_update_status_notify": false,
            "barebone_installable": true
          }
        ]
      },
      "default": {

DSM successfully checked disk compatibility.

You may need to reboot the Synology to see the changes.

```

2. sudo ./syno_hdd_db.sh --restore
```
Synology_HDD_db v2.2.47
DS923+ DSM 7.2-64561 
Using options: --restore

Restored synoinfo.conf
Restored rx418_v7.db
Restored rx415_v7.db
Restored rx1214_v7.db
Restored ds923+_host_v7.db
Restored dx513_v7.db
Restored rx1217_v7.db
Restored dx1215ii_v7.db
Restored ds923+_host_v7.db.new
Restored rx1214rp_v7.db
Restored rx1216sas_v7.db
Restored rx1211rp_v7.db
Restored rx1211_v7.db
Restored dx517_v7.db
Restored dx1211_v7.db
Restored dx1215_v7.db
Restored rx1213sas_v7.db
Restored rx1217sas_v7.db
Restored rxd1219sas_v7.db
Restored rx1217rp_v7.db
Restored rx6022sas_v7.db
Restored dx213_v7.db

Restore successful.
```
3. sudo ./syno_hdd_db.sh -nr --showedits > 1_log.txt
output:
```
Backed up ds923+_host_v7.db
Backed up ds923+_host_v7.db.new
ST8000VN004-3CP101 already exists in ds923+_host_v7.db
ST8000VN004-3CP101 already exists in ds923+_host_v7.db.new

Backed up synoinfo.conf
```
log:
```
Synology_HDD_db v2.2.47
DS923+ DSM 7.2-64561 
Using options: -nr --showedits

HDD/SSD models found: 3
ST4000VN000-1H4168,SC44
ST8000VN004-2M2101,SC60
ST8000VN004-3CP101,SC60

M.2 drive models found: 1
CT1000P3PSSD8,P9CR40A

No M.2 cards found

No Expansion Units found

Added ST4000VN000-1H4168 to ds923+_host_v7.db
Added ST4000VN000-1H4168 to ds923+_host_v7.db.new
Added ST8000VN004-2M2101 to ds923+_host_v7.db
Added ST8000VN004-2M2101 to ds923+_host_v7.db.new
Added CT1000P3PSSD8 to ds923+_host_v7.db
Added CT1000P3PSSD8 to ds923+_host_v7.db.new

Support disk compatibility already enabled.

Disabled support memory compatibility.

Max memory already set to 32 GB.

M.2 volume support already enabled.

Disabled drive db auto updates.

    "ST4000VN000-1H4168": {
      "SC44": {
        "compatibility_interval": [
          {
            "compatibility": "support",
            "not_yet_rolling_status": "support",
            "fw_dsm_update_status_notify": false,
            "barebone_installable": true
          }
        ]
      },
      "default": {

    "ST8000VN004-2M2101": {
      "SC60": {
        "compatibility_interval": [
          {
            "compatibility": "support",
            "not_yet_rolling_status": "support",
            "fw_dsm_update_status_notify": false,
            "barebone_installable": true
          }
        ]
      },
      "default": {

    "ST8000VN004-3CP101": {
      "SC60": {
        "compatibility_interval": [
          {
            "compatibility": "support",
            "not_yet_rolling_status": "support",
            "fw_dsm_update_status_notify": false,
            "barebone_installable": true,
            "smart_test_ignore": false,
            "smart_attr_ignore": false
          }
        ]

    "CT1000P3PSSD8": {
      "P9CR40A": {
        "compatibility_interval": [
          {
            "compatibility": "support",
            "not_yet_rolling_status": "support",
            "fw_dsm_update_status_notify": false,
            "barebone_installable": true
          }
        ]
      },
      "default": {

DSM successfully checked disk compatibility.

You may need to reboot the Synology to see the changes.
```

**Comment by 007revad** [comment]
I notice that the ST8000VN004-3CP101 which was already in the .db files contains 2 new lines that weren't in previous DSM version's db files:
```
            "smart_test_ignore": false,
            "smart_attr_ignore": false
```
I wonder if the other drives not having those 2 lines is a problem.

There is 1 change that --restore does not undo:
`echo 1 > /run/synostorage/disks/nvme0n1/m2_pool_support`

You could try the following:
`echo 0 > /run/synostorage/disks/nvme0n1/m2_pool_support`

I've downloaded the DSM_DS923+_64561.pat file, unpacked it and attached the default synoinfo.conf and disk compatability db files for you - hoping they'll get your Synology working again.
[synoinfo.zip](https://github.com/007revad/Synology_HDD_db/files/11612409/synoinfo.zip)
[DiskCompatibilityDB.zip](https://github.com/007revad/Synology_HDD_db/files/11612418/DiskCompatibilityDB.zip)

**Comment by fish-2023** [comment]
I'll be able to try the suggested steps in a few hours. In the meantime I'm backing up some important data just in case.
Thank you!

**Comment by fish-2023** [comment]
Quick update, I have decided to reset the NAS and reinstall DSM.
I have backed up the settings locally (but they were backed up also on the cloud) and restored them right after the reset. Everything seems to be looking fine 🤞, and I didn't lose any data.

One thing I forgot to mention previously is that I was on 7.1 and I have [manually] updated to 7.2.
This time I have installed 7.2 directly.

Thanks for the support!

**Comment by fish-2023** [comment]
OK, wrapping this up.
I guess I didn't really understand how the script[s] worked...
After the reset, I have run the Synology_HDD_db again, restarted and the ran Synology_M2_volume one.
I have now a working volume on the two m2 drives 🎉

I guess the first time I didn't understand what the 1st script was supposed to do and so I reverted the operation. The "restore" operation must have broken something, but I guess the script did what it was supposed to do...

Thanks again, I bought you a beer 😉

**Comment by fish-2023** [comment]
The "restore" operation might have caused problems, but on a second run the script[s] worked without any problem.

**Comment by 007revad** [comment]
> The "restore" operation might have caused problem

Thank you for pointing that out.

I just tested the restore option on a DS720+ running 7.2 and it had the same issues as you. I found a couple of likely causes and edited them by hand. After that I rebooted and everything was back to normal.

I'll have an updated version of the script online soon (after some more testing).

**Comment by fish-2023** [comment]
I'm happy to hear that reporting the issue is helping. Thanks again for the work you do
