### ISSUE TITLE
一个问题，请教。

### ISSUE THREAD

**Issue by pengliscu** [007revad/Synology_HDD_db#85]
一个问题，请教。
![QQ图片20230603230031](https://github.com/007revad/Synology_HDD_db/assets/134192605/b13faf09-0fea-4bb6-89e0-98e433dfd4fc)

**Comment by pengliscu** [comment]
can not  run the  Synology HDD db

**Comment by 007revad** [comment]
You've downloaded the wrong file. 

1. See https://github.com/007revad/Synology_HDD_db/blob/main/images/how_to_download.png
2. Then unzip the zip file and run the syno_hdd_db.sh file.

**Comment by pengliscu** [comment]
> You've downloaded the wrong file. You actually downloaded the webpage.
> 
> 1. See https://github.com/007revad/Synology_HDD_db/blob/main/images/how_to_download.png
> 2. Then unzip the zip file and run the syno_hdd_db.sh file.

谢谢已经成功运行，讽刺感谢。
