### ISSUE TITLE
DS918+ 7.2-64561 problem

### ISSUE THREAD

**Issue by hawie** [007revad/Synology_HDD_db#86]
Hi there is a problem with  dsm7.2release.
I tried v2.0.35 with dsm7.2beta, and the storage pool is recognized normally.
But v2.0.35, v2.2.47, v2.3.48RC with dsm7.2release, does not work.
need help...

console logs：
**ash-4.4#** ./syno_hdd_db.sh -nr
Synology_HDD_db **v2.0.35**
DS918+ DSM 7.2-64561 

There is a newer version of this script available.
Current version: v2.0.35
Latest version:  v2.2.47
Do you want to download v2.2.47 now? [y/n]
y
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
curl: (28) Resolving timed out after 5000 milliseconds
ERROR  Failed to download Synology_HDD_db-2.2.47.tar.gz!
**./syno_hdd_db.sh: line 493: /run/synostorage/disks/$(basename -- "$d")/m2_pool_support: No such file or directory**

HDD/SSD models found: 1
CT2000MX500SSD1,033

M.2 drive models found: 1
aigo NVMe SSD P7000Z 2TB,H230407a

No M.2 cards found

No Expansion Units found

Insert firmware version
Updated CT2000MX500SSD1 to ds918+_host_v7.db
Insert firmware version
Updated CT2000MX500SSD1 to ds918+_host_v7.db.new
Append drive and firmware
Added aigo NVMe SSD P7000Z 2TB to ds918+_host_v7.db
Append drive and firmware
Added aigo NVMe SSD P7000Z 2TB to ds918+_host_v7.db.new

Backed up synoinfo.conf

Re-enabled support disk compatibility.

Enabled M.2 volume support.

Disabled drive db auto updates.

DSM successfully checked disk compatibility.
<br>

**ash-4.4#** ./syno_hdd_db.sh -nr
Synology_HDD_db **v2.2.47**
DS918+ DSM 7.2-64561 
Using options: -nr
**./syno_hdd_db.sh: line 625: /run/synostorage/disks/$(basename -- "$d")/m2_pool_support: No such file or directory**

HDD/SSD models found: 1
CT2000MX500SSD1,033

M.2 drive models found: 1
aigo NVMe SSD P7000Z 2TB,H230407a

No M.2 cards found

No Expansion Units found

Backed up ds918+_host.db.new
Backed up ds918+_host_v7.db.new
CT2000MX500SSD1 already exists in ds918+_host_v7.db
CT2000MX500SSD1 already exists in ds918+_host.db
CT2000MX500SSD1 already exists in ds918+_host.db.new
CT2000MX500SSD1 already exists in ds918+_host_v7.db.new
aigo NVMe SSD P7000Z 2TB already exists in ds918+_host_v7.db
Added aigo NVMe SSD P7000Z 2TB to ds918+_host.db
Added aigo NVMe SSD P7000Z 2TB to ds918+_host.db.new
aigo NVMe SSD P7000Z 2TB already exists in ds918+_host_v7.db.new

Re-enabled support disk compatibility.

Support memory compatibility already disabled.
**./syno_hdd_db.sh: line 1066: Size:: syntax error in expression (error token is ":")**

M.2 volume support already enabled.

Drive db auto updates already disabled.

DSM successfully checked disk compatibility.

You may need to reboot the Synology to see the changes.
<br>

**ash-4.4#** ./syno_hdd_db.sh -nr
Synology_HDD_db **v2.3.48**
DS918+ DSM 7.2-64561 
Using options: -nr
**./syno_hdd_db.sh: line 686: /run/synostorage/disks/$(basename -- "$d")/m2_pool_support: No such file or directory**

HDD/SSD models found: 1
CT2000MX500SSD1,033

M.2 drive models found: 1
aigo NVMe SSD P7000Z 2TB,H230407a

No M.2 cards found

No Expansion Units found

CT2000MX500SSD1 already exists in ds918+_host_v7.db
CT2000MX500SSD1 already exists in ds918+_host.db
CT2000MX500SSD1 already exists in ds918+_host.db.new
CT2000MX500SSD1 already exists in ds918+_host_v7.db.new
aigo NVMe SSD P7000Z 2TB already exists in ds918+_host_v7.db
aigo NVMe SSD P7000Z 2TB already exists in ds918+_host.db
aigo NVMe SSD P7000Z 2TB already exists in ds918+_host.db.new
aigo NVMe SSD P7000Z 2TB already exists in ds918+_host_v7.db.new

Re-enabled support disk compatibility.

Support memory compatibility already disabled.
**./syno_hdd_db.sh: line 1127: Size:: syntax error in expression (error token is ":")**

M.2 volume support already enabled.

Drive db auto updates already disabled.

DSM successfully checked disk compatibility.

You may need to reboot the Synology to see the changes.
ash-4.4#

**Comment by 007revad** [comment]
What do the following commands return?

`cat /run/synostorage/disks/nvme0n1/m2_pool_support`

ls /run/synostorage/disks

`ls /run/synostorage/disks/nvme0n1 | grep m2_pool_support`

`sudo dmidecode -t memory | grep -i 'size'`
<br>

The 033 firmware version of the SATA SSDs looks too short: CT2000MX500SSD1,**033**
I'm not sure about the model name of your NVMe drives: "**aigo NVMe SSD P7000Z 2TB**,H230407a"

Can you please attach a screenshot of "Storage Manager > HDD/SSD" so I can see what Storage Manager shows as the model names and firmware versions.

**Comment by hawie** [comment]
ash-4.4# cat /run/synostorage/disks/nvme0n1/m2_pool_support
cat: /run/synostorage/disks/nvme0n1/m2_pool_support: No such file or directory

ash-4.4# ls /run/synostorage/disks/nvme0n1 | grep m2_pool_support
ls: cannot access '/run/synostorage/disks/nvme0n1': No such file or directory

ash-4.4# sudo dmidecode -t memory | grep -i 'size'
	Size: 4096 MB
	Non-Volatile Size: None
	Volatile Size: 4 GB
	Cache Size: None
	Logical Size: None
	Size: 4096 MB
	Non-Volatile Size: None
	Volatile Size: 4 GB
	Cache Size: None
	Logical Size: None

ash-4.4# ls -al /run/synostorage/disks/
total 0
drwxr-xr-x 4 root root   80 Jun  6 10:48 .
drwxr-xr-x 5 root root  240 Jun  6 10:48 ..
drwxr-xr-x 2 root root 1100 Jun  6 12:02 sda
drwxr-xr-x 2 root root 1100 Jun  6 12:02 sdb

ash-4.4# fdisk -l /dev/nvme0n1
Disk /dev/nvme0n1: 1.9 TiB, 2048408248320 bytes, 4000797360 sectors
Disk model: aigo NVMe SSD P7000Z 2TB                
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xab76187d

Storage Manager > HDD/SSD, no NVMe SSD shows, only SATA ssd. 
screenshot: http://usa1.cyder.club/dsm.png

**Comment by 007revad** [comment]
So the CT2000MX500SSD1 firmware version should be M3CR033 and not 033. Your the 3rd person in the last week with this issue of the script cropping the firmware to the last 3 characters.

Does this return the size of your memory:
sudo dmidecode -t memory | grep [Ss]ize

Has the DS918+ ever shown the NVMe drives as Cache drives in storage manager?

I can see that your DS918+ had DSM 6 on it and was updated to DSM 7. But in some ways it's acting like DSM 6 (naming the drive's as sda, sdb instead of sata1, sata2). DSM 6 has a file that DSM 7 does not: /etc.defaults/support_ssd.db (so DSM 7 should be using that file).

**Comment by hawie** [comment]
Yes, upgraded from DSM6.2.3.

1. The previous version was 7.2beta, 7.2-64216, using v2.0.35, which supports storage pools and Cache drives, but at that time _Sandisk Ultra 3D 2TB (WD SN550 NVMe)_ was used.

2. Upgrade to 7.2release, 7.2-64561, M.2 NVMe changed to the current model, _aigo NVMe SSD P7000Z 2TB_.  

3. /etc.defaults/support_ssd.db not found.
`ash-4.4# cd /etc.defaults/
ash-4.4# ls suppo*
ls: cannot access 'suppo*': No such file or directory`

4. commands return
```
ash-4.4# cat "/sys/block/sda/device/rev"
033 
ash-4.4# cat "/sys/block/sdb/device/rev"
033 
ash-4.4# cat "/sys/block/sda/device/firmware_rev"
cat: /sys/block/sda/device/firmware_rev: No such file or directory
ash-4.4# cat "/sys/block/sdb/device/firmware_rev"
cat: /sys/block/sdb/device/firmware_rev: No such file or directory

```
The total physical memory of the host is 8GB, 4GB*2. I don't know if this result corresponds to the same.

**Comment by 007revad** [comment]
It looks like Synology has changed smartctl to not return the full firmware version. If I was a conspiracy theorist I'd think they were deliberately trying to break my script.
- Only the **last** 4 characters of HDD and SATA SSD firmware versions are returned by smartctl in DSM 7.2
- Only the **first** 4 characters of HDD and SATA SSD firmware versions are returned by smartctl in DSM 6.2.4 Update 7

I've found a solution that will work in DSM 7.2 and 6.2.4 Update 7 (but I have no idea if it will break the script for older DSM versions).

Unfortunately none of this solves the puzzle of why your new NVMe drives don't appear in storage manager. Until they are visible in storage manager (as either cache drives or M.2 drives) I can't see the script making any difference.

Though I am curious what the following command returns:
`sudo syno_hdd_util --ssd_detect`

**Comment by hawie** [comment]
> none of this solves the puzzle of why your new NVMe drives don't appear in storage manager.
(-:
I'll try it later with a previous NVMe drive.

**Comment by hawie** [comment]
fresh install, using new hdd
v2.3.48RC
```
Synology_HDD_db v2.3.48
DS918+ DSM 7.2-64561 
Using options: -nr

HDD/SSD models found: 1
WD2003FYYS-02W0B0,1D01

M.2 drive models found: 1
aigo NVMe SSD P7000Z 2TB,H230407a

No M.2 cards found

No Expansion Units found

WD2003FYYS-02W0B0 already exists in ds918+_host_v7.db
aigo NVMe SSD P7000Z 2TB already exists in ds918+_host_v7.db

Re-enabled support disk compatibility.

Support memory compatibility already disabled.
./syno_hdd_db.sh: line 1127: Size:: syntax error in expression (error token is ":")

M.2 volume support already enabled.

Drive db auto updates already disabled.

DSM successfully checked disk compatibility.

You may need to reboot the Synology to see the changes.
```
v2.0.35
```
Synology_HDD_db v2.0.35
DS918+ DSM 7.2-64561 

There is a newer version of this script available.
Current version: v2.0.35
Latest version:  v2.2.47
Do you want to download v2.2.47 now? [y/n]
n

HDD/SSD models found: 1
WD2003FYYS-02W0B0,1D01

M.2 drive models found: 1
aigo NVMe SSD P7000Z 2TB,H230407a

No M.2 cards found

No Expansion Units found

WD2003FYYS-02W0B0 already exists in ds918+_host_v7.db
aigo NVMe SSD P7000Z 2TB already exists in ds918+_host_v7.db

Re-enabled support disk compatibility.

M.2 volume support already enabled.

Drive db auto updates already disabled.

DSM successfully checked disk compatibility.
```

v2.2.47
```
Synology_HDD_db v2.2.47
DS918+ DSM 7.2-64561 
Using options: -nr

HDD/SSD models found: 1
WD2003FYYS-02W0B0,1D01

M.2 drive models found: 1
aigo NVMe SSD P7000Z 2TB,H230407a

No M.2 cards found

No Expansion Units found

WD2003FYYS-02W0B0 already exists in ds918+_host_v7.db
aigo NVMe SSD P7000Z 2TB already exists in ds918+_host_v7.db

Re-enabled support disk compatibility.

Support memory compatibility already disabled.
./syno_hdd_db-new-but-notok.sh: line 1066: Size:: syntax error in expression (error token is ":")

M.2 volume support already enabled.

Drive db auto updates already disabled.

DSM successfully checked disk compatibility.

You may need to reboot the Synology to see the changes.
```
same results, after reboot:
storage pools:  not support
Cache drives: ok

if not reboot:
storage pools: ok
Cache drives: ok

```
# cat /run/synostorage/disks/nvme0n1/m2_pool_support 
1
# reboot
# cat /run/synostorage/disks/nvme0n1/m2_pool_support 
0
```

**Comment by hawie** [comment]
Synology_enable_M2_volume works OOB.  thx!
```
Synology_enable_M2_volume v1.0.6
DS918+ DSM 7.2-64561 

Using options: 
Backup successful.

Checking file.
188842 = 2e1aa
0002e1aa: 803E 00B8 0100 0000 7524 488B

Editing file.

Checking if file was successfully edited.
188842 = 2e1aa
0002e1aa: 803E 00B8 0100 0000 9090 488B
File successfully edited.

You can now create your M.2 storage pool in Storage Manager.

M.2 volume support already enabled.

The Synology needs to restart.
Type yes to reboot now.
Type anything else to quit (if you will restart it yourself).
```
only little unexpected,
an additional message appears to MX500 SATA SSD Drive:
`Firmware version:  M3CR033 (**Unrecognized firmware version, please update the drive database**)`

hope your next version, thx again for your great work!!!

**Comment by 007revad** [comment]
> an additional message appears to MX500 SATA SSD Drive:
> `Firmware version: M3CR033 (Unrecognized firmware version, please update the drive database)`

That would be because the script added 033 as the firmware version in the db file instead of M3CR033.

**Comment by 007revad** [comment]
Do you want to try [Synology_HDD_db v2.3.49-RC](https://github.com/007revad/Synology_HDD_db/releases/tag/v2.3.49-RC) and see if it fixes your issues?

**Comment by hawie** [comment]
ash-4.4# ./syno_hdd_db.sh -nr
```
Synology_HDD_db v2.3.49
DS918+ DSM 7.2-64561 
Using options: -nr

ERROR No drives found!
```
ash-4.4#

**Comment by hawie** [comment]
v2.0.35 Minor change,  works for me:
diff -uNr syno_hdd_db.sh-PRI  syno_hdd_db.sh 
```
--- syno_hdd_db.sh-PRI	2023-06-12 13:58:23.341927026 +0800
+++ syno_hdd_db.sh	2023-06-12 14:04:05.369305645 +0800
@@ -426,6 +426,9 @@
 
         fwrev=$(cat "$1/device/rev")
         fwrev=$(printf "%s" "$fwrev" | xargs)  # trim leading and trailing white space
+		if [ $fwrev == "033" ]; then
+			fwrev="M3CR033"
+		fi
 
         if [[ $hdmodel ]] && [[ $fwrev ]]; then
             hdlist+=("${hdmodel},${fwrev}")
```

**Comment by 007revad** [comment]
> ERROR No drives found!
Oops! :(

Try v2.3.51-RC
https://github.com/007revad/Synology_HDD_db/releases/tag/v2.3.51-RC

**Comment by hawie** [comment]
> > ERROR No drives found!
> > Oops! :(
> 
> Try v2.3.51-RC https://github.com/007revad/Synology_HDD_db/releases/tag/v2.3.51-RC

ash-4.4# ./syno_hdd_db.sh -nr
```
Synology_HDD_db v2.3.51
DS918+ DSM 7.2-64561 
Using options: -nr

HDD/SSD models found: 1
CT2000MX500SSD1,M3CR033

M.2 drive models found: 1
aigo NVMe SSD P7000Z 2TB,H230407a

No M.2 cards found

No Expansion Units found

CT2000MX500SSD1 already exists in ds918+_host_v7.db
CT2000MX500SSD1 already exists in ds918+_host.db
CT2000MX500SSD1 already exists in ds918+_host.db.new
CT2000MX500SSD1 already exists in ds918+_host_v7.db.new
aigo NVMe SSD P7000Z 2TB already exists in ds918+_host_v7.db
aigo NVMe SSD P7000Z 2TB already exists in ds918+_host.db
aigo NVMe SSD P7000Z 2TB already exists in ds918+_host.db.new
aigo NVMe SSD P7000Z 2TB already exists in ds918+_host_v7.db.new

Support disk compatibility already enabled.

Support memory compatibility already disabled.

ERROR Memory size is not numeric: 'Size:'

ERROR Memory size is not numeric: 'Size:'

ERROR Memory size is not numeric: 'Size:'

ERROR Memory size is not numeric: 'Size:'

ERROR Memory size is not numeric: 'Size:'

ERROR Memory size is not numeric: 'Size:'

ERROR Memory size is not numeric: 'Size:'

ERROR Memory size is not numeric: 'Size:'

Max memory already set to 8 GB.

M.2 volume support already enabled.

Drive db auto updates already disabled.

DSM successfully checked disk compatibility.

You may need to reboot the Synology to see the changes.
```

**Comment by 007revad** [comment]
Thank you.

> ash-4.4# sudo -i IFS=$'\n' read -r -d '' -a array < <(dmidecode -t memory | grep "[Ss]ize")
> ash-4.4# for f in "${!array[@]}"; do echo "'${array[f]}'";  r=$(printf %s "${array[num]}" | awk '{print $2}'); echo "'$r'"; done
Both these commands probably returned nothing because you're using ash instead sh. But I got what I needed from the "dmidecode -t memory" command.

On my DS1821+ and DS720+ I don't get these lines:
> 	Memory Technology: DRAM
> 	Memory Operating Mode Capability: Volatile memory
> 	Firmware Version: Not Specified
> 	Module Manufacturer ID: Bank 1, Hex 0xCE
> 	Module Product ID: Unknown
> 	Memory Subsystem Controller Manufacturer ID: Unknown
> 	Memory Subsystem Controller Product ID: Unknown
> 	Non-Volatile Size: None
> 	Volatile Size: 4 GB
> 	Cache Size: None
> 	Logical Size: None

And these 4 are causing the errors.
> 	Non-Volatile Size: None
> 	Volatile Size: 4 GB
> 	Cache Size: None
> 	Logical Size: None

I've fixed it in [v2.3.51-RC](https://github.com/007revad/Synology_HDD_db/releases/tag/v2.3.51-RC) and it works for me, but the real test will be if it works for you.

**Comment by hawie** [comment]
v2.3.53-RC, version not changed, line 1066 syntax error in expression
```
ash-4.4# ./syno_hdd_db.sh -nr 
Synology_HDD_db v2.2.47
DS918+ DSM 7.2-64561 
Using options: -nr

HDD/SSD models found: 1
CT2000MX500SSD1,033

M.2 drive models found: 1
aigo NVMe SSD P7000Z 2TB,H230407a

No M.2 cards found

No Expansion Units found

Updated CT2000MX500SSD1 to ds918+_host_v7.db
CT2000MX500SSD1 already exists in ds918+_host.db
CT2000MX500SSD1 already exists in ds918+_host.db.new
aigo NVMe SSD P7000Z 2TB already exists in ds918+_host_v7.db
aigo NVMe SSD P7000Z 2TB already exists in ds918+_host.db
aigo NVMe SSD P7000Z 2TB already exists in ds918+_host.db.new

Support disk compatibility already enabled.

Support memory compatibility already disabled.
./syno_hdd_db.sh: line 1066: Size:: syntax error in expression (error token is ":")

M.2 volume support already enabled.

Drive db auto updates already disabled.

DSM successfully checked disk compatibility.

You may need to reboot the Synology to see the changes.
```

**Comment by hawie** [comment]
v2.3.51-RC, try again
```
ash-4.4# ./syno_hdd_db.sh -nr
Synology_HDD_db v2.3.51
DS918+ DSM 7.2-64561 
Using options: -nr

HDD/SSD models found: 1
CT2000MX500SSD1,M3CR033

M.2 drive models found: 1
aigo NVMe SSD P7000Z 2TB,H230407a

No M.2 cards found

No Expansion Units found

Updated CT2000MX500SSD1 to ds918+_host_v7.db
CT2000MX500SSD1 already exists in ds918+_host.db
CT2000MX500SSD1 already exists in ds918+_host.db.new
aigo NVMe SSD P7000Z 2TB already exists in ds918+_host_v7.db
aigo NVMe SSD P7000Z 2TB already exists in ds918+_host.db
aigo NVMe SSD P7000Z 2TB already exists in ds918+_host.db.new

Support disk compatibility already enabled.

Support memory compatibility already disabled.

ERROR Memory size is not numeric: 'Size:'

ERROR Memory size is not numeric: 'Size:'

ERROR Memory size is not numeric: 'Size:'

ERROR Memory size is not numeric: 'Size:'

ERROR Memory size is not numeric: 'Size:'

ERROR Memory size is not numeric: 'Size:'

ERROR Memory size is not numeric: 'Size:'

ERROR Memory size is not numeric: 'Size:'

Max memory already set to 8 GB.

M.2 volume support already enabled.

Drive db auto updates already disabled.

DSM successfully checked disk compatibility.

You may need to reboot the Synology to see the changes.
ash-4.4# 
```

**Comment by 007revad** [comment]
Sorry, I obviously wasn't having a good day yesterday. The v2.3.53-RC release actually contained v2.2.47 !?!?!

Please try [v2.3.54-RC](https://github.com/007revad/Synology_HDD_db/releases/tag/v2.3.54-RC)

**Comment by hawie** [comment]
v2.3.54-RC
Confirmed working for my special upgraded DS918+
Thank you for all your efforts!
```
ash-4.4# ./syno_hdd_db.sh -nr
Synology_HDD_db v2.3.54
DS918+ DSM 7.2-64561 
Using options: -nr

HDD/SSD models found: 1
CT2000MX500SSD1,M3CR033

M.2 drive models found: 1
aigo NVMe SSD P7000Z 2TB,H230407a

No M.2 PCIe cards found

No Expansion Units found

CT2000MX500SSD1 already exists in ds918+_host_v7.db
CT2000MX500SSD1 already exists in ds918+_host.db
CT2000MX500SSD1 already exists in ds918+_host.db.new
aigo NVMe SSD P7000Z 2TB already exists in ds918+_host_v7.db
aigo NVMe SSD P7000Z 2TB already exists in ds918+_host.db
aigo NVMe SSD P7000Z 2TB already exists in ds918+_host.db.new

Support disk compatibility already enabled.

Support memory compatibility already disabled.

Max memory already set to 8 GB.

M.2 volume support already enabled.

Drive db auto updates already disabled.

DSM successfully checked disk compatibility.

You may need to reboot the Synology to see the changes.
ash-4.4# 
```
