### ISSUE TITLE
Interesting output after running script

### ISSUE THREAD

**Issue by TheCableGuy99** [007revad/Synology_HDD_db#88]
Hi,

I just updated the script and thought i'd run it then noticed something interesting:

```root@SHS1:/volume1# ./syno_hdd_db.sh
Synology_HDD_db v2.2.47
DS1821+ DSM 7.2-64551 RC
Using options:

HDD/SSD models found: 6
ST8000DM0004-1ZC11G,DN01
WD60EFAX-68JH4N1,0A83
WD60EFAX-68SHWN0,0A82
WD60EFRX-68L0BN1,0A82
WD60EFRX-68MYMN1,0A82
WD60EFZX-68B3FN0,0A81

M.2 drive models found: 2
Samsung SSD 970 EVO Plus 1TB,1B2QEXM7
Samsung SSD 970 EVO Plus 1TB,2B2QEXM7

No M.2 cards found

Expansion Unit models found: 1
DX517

Added ST8000DM0004-1ZC11G to ds1821+_host_v7.db
Added ST8000DM0004-1ZC11G to dx517_v7.db
Added WD60EFAX-68JH4N1 to ds1821+_host_v7.db
Added WD60EFAX-68JH4N1 to dx517_v7.db
Added WD60EFAX-68SHWN0 to ds1821+_host_v7.db
Updated WD60EFAX-68SHWN0 to dx517_v7.db
Added WD60EFRX-68L0BN1 to ds1821+_host_v7.db
Updated WD60EFRX-68L0BN1 to dx517_v7.db
Added WD60EFRX-68MYMN1 to ds1821+_host_v7.db
Updated WD60EFRX-68MYMN1 to dx517_v7.db
Updated WD60EFZX-68B3FN0 to ds1821+_host_v7.db
Updated WD60EFZX-68B3FN0 to dx517_v7.db
Added Samsung SSD 970 EVO Plus 1TB to ds1821+_host_v7.db
Updated Samsung SSD 970 EVO Plus 1TB to ds1821+_host_v7.db

Support disk compatibility already enabled.

Support memory compatibility already enabled.

M.2 volume support already enabled.

Drive db auto updates already enabled.

DSM successfully checked disk compatibility.

You may need to reboot the Synology to see the changes.
```

Note it finds my 2 M.2 cards then says immediately after that there are non found. I'm not sure if this is a problem or not, or just a small bug but thought it was best to report it.

Also, have you implemented the auto-update feature yet? If so, how do I enable it please?

Thanks.

**Comment by 007revad** [comment]
> HDD/SSD models found: 6
> ST8000DM0004-1ZC11G,DN01
> WD60EFAX-68JH4N1,0A83
> WD60EFAX-68SHWN0,0A82
> WD60EFRX-68L0BN1,0A82
> WD60EFRX-68MYMN1,0A82
> WD60EFZX-68B3FN0,0A81

The HDDs are all showing only the last 4 characters of their firmware version. This is due to a change in DSM 7.2

> No M.2 cards found

That is actually referring to PCIe cards that you can install M.2 drives on like the M2D20, M2D18 and E10M20-T1.
I should change the "**No M.2 cards found**" to "**No M.2 PCIe cards found**" to make it clearer.

I've fixed the HDD 4 character firmware version issue and added auto-update, but the release is still RC.
https://github.com/007revad/Synology_HDD_db/releases/tag/v2.3.51-RC

The --autoupdate=[age] option requires a digit for the number of days after new version is released to wait before updating. You can use --autoupdate=0 to update right away. The script also reloads itself so when you run it unattended (scheduled) it can update itself and run the new version.

**Comment by TheCableGuy99** [comment]
> 

I didn't actually notice the lack of digits on the firmware version but glad to know it's another bug squished :)

Thanks for confirming what the M.2 line means also :)

And I really like how you've added that it will update itself and then run itself again. I'm going to wait for the official release though to be sure it's good :)

Just to confirm though, when I do set it, my current script is set in Synology Task manager with the script as follows:
/volume1/syno_hdd_db.sh

Would I change this to:
/volume1/syno_hdd_db.sh --autoupdate=0

or does it need to go in some quotes because there's a space like so:
"/volume1/syno_hdd_db.sh --autoupdate=0"

Thanks for all your help :)

**Comment by TheCableGuy99** [comment]
@70m7E I don't think you need both scripts, I think the syno_hdd_db.sh script does it all.... but i'm not 100% so maybe @007revad could confirm? 

I'm running M.2's as volumes and i'm only running the syno_hdd_db.sh script at boot personally.

**Comment by 007revad** [comment]
> May I just ask here for the "unattended" - do you recommend scheduled tasks as root at shutdown or boot-up when running both hdd_db and enable_m2 script? The guide recommends both depending on script.

Yes, I if you need the enable_m2 script I would add it to the same schedule as hdd_db, so you'd have 2 lines in the scheduled task: 1 for each script.

**Comment by 007revad** [comment]
@TheCableGuy99

> Would I change this to:
> /volume1/syno_hdd_db.sh --autoupdate=0

Yes. 

You would need quotes if the path had a space, and then you'd only quote the path/filename part like:
"/volume1/my path/syno_hdd_db.sh" --autoupdate=0

If you want to also use the -n and -f options you'd use:
/volume1/syno_hdd_db.sh --autoupdate=0 -nf

Or
/volume1/syno_hdd_db.sh --autoupdate=0 -n -f
